import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import Tile3 from "./components/tile3";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", ariacurrent: "page", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "디바이스별 FCM 토큰 등록/해제 API (MSG-178)" },
    { text: "커밋된 이벤트의 알림이 유실되지 않는 발송 파이프라인 (MSG-179)" },
    { text: "카테고리별 수신 on/off 설정 + 발송 시 필터 (MSG-180)" },
    { text: "구현된 이벤트 소스 3종 트리거 연동 (MSG-181)" }
];
const Tile_data = [
    { text: "FR-1", text2: "FCM 토큰 등록은 ", text3: "UPSERT", text4: " — fcm_token이 PK라 재로그인·재등록 시 충돌 없이 user_id·last_used_at 갱신 (위키 Notification API 확정)", text5: "178" },
    { text: "FR-2", text2: "토큰 해제는 ", text3: "멱등", text4: " — 없는 토큰 삭제도 성공 응답. 계정 삭제 시 FK CASCADE로 정리", text5: "178" },
    { text: "FR-3", text2: "커밋된 도메인 이벤트의 알림 요청은 프로세스 재시작·브로커/FCM 장애에도 ", text3: "유실되지 않는다", text4: " — 비즈니스 트랜잭션과 알림 요청 기록이 원자적", text5: "179" }
];
const Tile2_data = [
    { text: "FR-4", text2: "발송 실패는 재시도된다 — 상한 초과 시 DEAD 상태로 격리(무한 재시도 금지)하고 운영자가 식별 가능", text3: "179" },
    { text: "FR-5", text2: "FCM이 무효 토큰(UNREGISTERED 등)을 응답하면 해당 push_tokens 행을 자동 정리한다", text3: "179" },
    { text: "FR-6", text2: "같은 이벤트로 같은 사용자에게 중복 발송되지 않는다 — 이벤트 키 기반 멱등 (at-least-once 전달의 짝)", text3: "179" },
    { text: "FR-7", text2: "사용자는 카테고리(BADGE·HOTZONE·REMIND)별 수신 on/off를 저장·조회할 수 있다. 기본값 전부 on (opt-out 모델)", text3: "180" },
    { text: "FR-8", text2: "off 카테고리의 알림은 발송 단계에서 걸러진다 — 이벤트 기록은 남되 발송 안 함", text3: "180" },
    { text: "FR-9", text2: "뱃지 발급 시 해당 사용자에게 알림이 발송된다", text3: "181" },
    { text: "FR-10", text2: "내 점령 격자가 핫구역에 신규 진입하면 알림이 발송된다 (진입 검출 주기·방식은 스펙 확정 — 핫존은 조회 시점 계산이라 이벤트가 자연 발생하지 않음)", text3: "181" },
    { text: "FR-11", text2: "스트릭이 끊기기 전(당일 미업로드) 리마인드가 배치로 발송된다", text3: "181" },
    { text: "FR-12", text2: "사용자·카테고리별 발송 상한(전송률 제한)이 적용된다 — 알림 피로로 인한 전체 off 방지. 기본값: HOTZONE 1건/일 · REMIND 1건/일 · BADGE 무제한(사용자 액션 직결·희소). 수치는 설정값으로 조정 가능", text3: "179" }
];
const Tile3_data = [
    { text: "보안", text2: "FCM 서비스 계정 키는 환경변수/파일 마운트로 주입, 레포 커밋 금지" },
    { text: "운영 가시성", text2: "발송 상태(대기·발송·실패·DEAD)가 집계 쿼리로 확인 가능 — 성공률·유실 여부를 숫자로 말할 수 있어야 함(커리어 목표와 직결)" },
    { text: "데이터 정합", text2: "기존 테이블 소급 없음. push_tokens는 스키마 무변경, 신규 테이블(발송 기록·알림 설정)만 추가" }
];
const ListRow2_data = [
    { text: "발송 구조 = Outbox + Kafka 릴레이 + 컨슈머 (이번 묶음에 Kafka 도입)", text2: ": 학습 목표 우선 —\n단일 브로커 운영 부담과 구현 복잡도 증가를 인지하고 수용. outbox는 이중 쓰기 문제\n(DB 커밋과 브로커 발행의 원자성) 때문에 Kafka 도입과 무관하게 필수 유지." },
    { text: "MSG-181 트리거 = 구현된 소스 3종", text2: ": 뱃지 발급 · 핫구역 진입 · 스트릭 리마인드.\n친구 활동은 friend 도메인 구현 후 후속 티켓." },
    { text: "전송률 제한 MVP 포함", text2: ": 간단한 사용자·카테고리별 상한 (FR-12 기본값)." }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n40"],
    ["n41"],
    ["n42"],
    ["n43"]
];
const Tile_cids: string[][] = [
    ["n62", "n63", "n64", "n65", "n66", "n67"],
    ["n68", "n69", "n70", "n71", "n72", "n73"],
    ["n74", "n75", "n76", "n77", "n78", "n79"]
];
const Tile2_cids: string[][] = [
    ["n80", "n81", "n82", "n83", "n84"],
    ["n85", "n86", "n87", "n88", "n89"],
    ["n90", "n91", "n92", "n93", "n94"],
    ["n95", "n96", "n97", "n98", "n99"],
    ["n100", "n101", "n102", "n103", "n104"],
    ["n105", "n106", "n107", "n108", "n109"],
    ["n110", "n111", "n112", "n113", "n114"],
    ["n115", "n116", "n117", "n118", "n119"],
    ["n120", "n121", "n122", "n123", "n124"]
];
const Tile3_cids: string[][] = [
    ["n143", "n144", "n145"],
    ["n146", "n147", "n148"],
    ["n149", "n150", "n151"]
];
const ListRow2_cids: string[][] = [
    ["n204", "n205"],
    ["n206", "n207"],
    ["n208", "n209"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const Tile_styles = [
    { className: "max-md:h-[196.1px]" },
    { className: "max-md:h-[8.0625rem]" },
    { className: "max-md:h-[196.1px]" }
];
const ListRow2_styles = [
    { className: "h-21 max-md:h-49" },
    { className: "h-14 max-md:h-21" },
    { className: "h-7 max-md:h-14" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/prd">
              ← 제품 요구사항
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              MSG-178 알림 시스템 — FCM 푸시 파이프라인 (공유 PRD)
            </h1>
            {" "}
            <ul className="flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              <li className="border border-solid border-clr-1 list-item py-[0.1875rem] px-[0.5625rem] rounded-[999px] text-primary [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[0.88px] uppercase whitespace-nowrap text-nowrap bg-surface-6" data-cid="n22">
                검토됨
              </li>
              <li className="border border-solid border-surface list-item py-[0.1875rem] px-[0.5625rem] rounded-[999px] text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[0.88px] uppercase whitespace-nowrap text-nowrap" data-cid="n23">
                출처 저장소
              </li>
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n24">
            <blockquote className="border-l-[3px] border-solid border-l-surface block my-[1.2rem] py-0.5 pl-4.5 text-muted" data-cid="n25">
              <p className="block my-4 text-muted-foreground" data-cid="n26">
                티켓: MSG-178 · MSG-179 · MSG-180 · MSG-181 (알림 에픽 하위 4종 커버) · 작성일: 2026-08-03 · 작성: prd-writer 상태: 검토됨 (2026-08-03 성민 승인 — 발송 구조 Kafka 포함·트리거 3종·전송률 제한 확정 반영)
              </p>
              {" "}
            </blockquote>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n27" data-component="heading" id="1-문제-상황">
              1. 문제 상황
            </h2>
            {" "}
            <p className="h-28 block my-4 text-muted-foreground max-md:h-63 md:max-lg:h-35" data-cid="n28">
              {"알림 기능이 전무하다. V1 스키마에 "}
              <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n29">
                push_tokens
              </code>
              {" 테이블(fcm_token 자연키 PK · platform IOS/ANDROID/WEB)만 있고 소비하는 코드가 0이다(실측: "}
              <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n30">
                com.msg.fillmap
              </code>
              {" 하위에 notification 패키지·FCM 참조 없음). IA “설정 > 알림 설정” 화면과 SA Notification 역할이 정의돼 있으나 미구현이고, 서비스의 리텐션 루프(스트릭·핫구역·뱃지)가 앱 밖의 사용자를 다시 부를 수단이 없다."}
            </p>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-49" data-cid="n31">
              {"이 작업은 단순 FCM 호출 붙이기가 아니다 — "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n32">
                대규모 시스템 설계의 알림 시스템 원칙
              </strong>
              (유실 방지 · 중복 최소화 · opt-out · 전송률 제한 · 재시도)을 실제 서비스 규모에 맞게 적용하는 것이 목표다 (2026-08-03 성민 지시 — 학습·커리어 목적 포함, 측정 가능한 보장 수준을 남긴다).
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n33" data-component="heading" id="2-목적--목표">
              2. 목적 · 목표
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n34">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n35">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n36">
                  목적
                </strong>
                : 도메인 이벤트(뱃지 발급·핫구역 진입·스트릭 리마인드)를 FCM 푸시로 전달하는 발송 파이프라인을 유실 없이 구축한다.
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n37">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n38">
                  목표
                </strong>
                {": "}
                <ul className="block pl-[1.35rem] [list-style-type:circle] list-outside" data-cid="n39">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} />)}
                </ul>
                {" "}
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n44">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n45">
                  비목표(스코프 제외)
                </strong>
                {": "}
                <ul className="block pl-[1.35rem] [list-style-type:circle] list-outside" data-cid="n46">
                  <li className="h-7 list-item my-[0.3rem] max-md:h-21 md:max-lg:h-14" data-cid="n47">
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n48">
                      친구 활동 알림
                    </strong>
                    {" — friend 도메인 자체가 미구현. 도메인 구현 후 후속 티켓 (2026-08-03 확정)"}
                  </li>
                  <li className="h-14 list-item my-[0.3rem] max-md:h-28" data-cid="n49">
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n50">
                      알림 이력/읽음 API
                    </strong>
                    (IA의 알림 목록 화면) — 티켓 범위 밖. 발송 기록 테이블이 남으므로 후속 티켓에서 조회 API만 얹으면 됨
                  </li>
                  <li className="list-item my-[0.3rem]" data-cid="n51">
                    SMS·이메일 채널 — MVP는 FCM 푸시 단일 채널. 단 발송기는 채널 추상화 뒤에 둔다
                  </li>
                  <li className="list-item my-[0.3rem]" data-cid="n52">
                    FCM vs SSE 논쟁 — 티켓 4종이 FCM 전제로 확정돼 있어 FCM으로 간주
                  </li>
                </ul>
                {" "}
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n53" data-component="heading" id="3-기능-요구사항">
              3. 기능 요구사항
            </h2>
            {" "}
            <table className="h-[50.2625rem] block min-w-full max-w-full my-[1.05rem] overflow-auto text-sm leading-[1.5625rem] [border-collapse:collapse] [border-spacing:2px] max-md:h-[121.625rem]" data-cid="n54">
              <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n55">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n56">
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n57">
                    ID
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n58">
                    요구사항
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n59">
                    티켓
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n60">
                    우선순위
                  </th>
                </tr>
              </thead>
              <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n61">
                {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} styles={Tile_styles[i]} />)}
                {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} />)}
              </tbody>
            </table>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n125" data-component="heading" id="4-비기능-요구사항">
              4. 비기능 요구사항
            </h2>
            {" "}
            <table className="h-[388.7px] block min-w-full max-w-full my-[1.05rem] overflow-auto text-sm leading-[1.5625rem] [border-collapse:collapse] [border-spacing:2px] max-md:h-[38.2875rem]" data-cid="n126">
              <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n127">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n128">
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n129">
                    분류
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n130">
                    요구사항
                  </th>
                </tr>
              </thead>
              <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n131">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n132">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n133">
                    전달 보장
                  </td>
                  <td className="h-[3.8625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[6.6625rem]" data-cid="n134">
                    <strong className="inline [font-weight:650] [border-collapse:collapse] [border-spacing:2px]" data-cid="n135">
                      at-least-once
                    </strong>
                    {" + 멱등 dedupe로 중복 최소화. exactly-once는 분산 환경에서 비현실적임을 문서화하고 추구하지 않는다"}
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n136">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n137">
                    실시간성
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n138">
                    연성 실시간(soft real-time) — 수 분 지연 허용. 리마인드 배치는 시각 정확성보다 발송 보장 우선
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n139">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n140">
                    인프라
                  </td>
                  <td className="h-[3.8625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[8.0625rem]" data-cid="n141">
                    {"Kafka 브로커(KRaft 단일 노드)를 EC2 1대에 컨테이너로 추가 — 메모리 예산 검증 필수. "}
                    <strong className="inline [font-weight:650] [border-collapse:collapse] [border-spacing:2px]" data-cid="n142">
                      dev/prod 격리 유지
                    </strong>
                    (멘토 지시) — 토픽 분리 또는 브로커 분리는 스펙에서 확정
                  </td>
                </tr>
                {Tile3_data.map((d, i) => <Tile3 key={i} d={d} cids={Tile3_cids[i]} />)}
              </tbody>
            </table>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n152" data-component="heading" id="5-시퀀스-다이어그램">
              5. 시퀀스 다이어그램
            </h2>
            {" "}
            <figure className="border border-solid border-surface block my-[1.6rem] p-4 rounded-xl overflow-auto text-center bg-surface-8" data-cid="n153">
              <img className="w-169 h-96.5 inline-block max-w-full overflow-clip max-md:w-[18.8125rem] max-md:h-43 md:max-lg:w-[41.0625rem] md:max-lg:h-[23.4375rem]" data-cid="n154" data-component="image" alt="시퀀스 다이어그램" src="/assets/cloned/svg/f6a1a79b69cd.svg" />
              {" "}
              <figcaption className="block mt-3 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[1.32px] uppercase" data-cid="n155">
                시퀀스 다이어그램
              </figcaption>
              {" "}
            </figure>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n156" data-component="heading" id="6-클래스-다이어그램">
              6. 클래스 다이어그램
            </h2>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-42" data-cid="n157">
              {"신규 도메인이라 타입 다수 신설 예상 — 구체 형상(엔티티·인터페이스 분리)은 스펙 몫. 경계만 확정: 발송기는 "}
              <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n158">
                NotificationSender
              </code>
              {" 류 인터페이스 뒤에 두고 FCM은 구현체 하나 (채널 추가·제3자 교체 대비 — 책의 “제3자 서비스 추상화”)."}
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n159" data-component="heading" id="7-변경-파일-목록">
              7. 변경 파일 목록
            </h2>
            {" "}
            <table className="h-[450.5px] block min-w-full max-w-full my-[1.05rem] overflow-auto text-sm leading-[1.5625rem] [border-collapse:collapse] [border-spacing:2px] max-md:h-[875.9px]" data-cid="n160">
              <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n161">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n162">
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n163">
                    파일
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n164">
                    변경
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n165">
                    Owner
                  </th>
                </tr>
              </thead>
              <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n166">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n167">
                  <td className="h-[3.8625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[8.0625rem]" data-cid="n168">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n169">
                      src/main/java/com/msg/fillmap/notification/**
                    </code>
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n170">
                    신설 — controller(토큰·설정 API)/service/entity/repository/relay/consumer
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n171">
                    B
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n172">
                  <td className="h-[3.8625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[151.3px]" data-cid="n173">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n174">
                      src/main/resources/db/migration/V18__*.sql
                    </code>
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n175">
                    신설 — 발송 기록(outbox)·알림 설정 테이블 (V18 번호는 PR 직전 develop 재확인 — V16 선점 사건 재발 방지)
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n176">
                    B
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n177">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n178">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n179">
                      build.gradle
                    </code>
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n180">
                    spring-kafka · firebase-admin 의존성 추가
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n181">
                    B
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n182">
                  <td className="h-[3.8625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[6.6625rem]" data-cid="n183">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n184">
                      docker-compose*.yml
                    </code>
                    {" · 배포 설정"}
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n185">
                    Kafka(KRaft 단일 노드) 컨테이너 추가
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n186">
                    B(인프라 겸)
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n187">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n188">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n189">
                      src/main/java/com/msg/fillmap/badge/**
                    </code>
                    {" · "}
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n190">
                      streak/**
                    </code>
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n191">
                    수정 — 발급/리마인드 트리거 지점에 알림 요청 기록
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n192">
                    B
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n193">
                  <td className="h-[3.8625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[8.0625rem]" data-cid="n194">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n195">
                      src/main/java/com/msg/fillmap/auth/**
                    </code>
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n196">
                    수정 — logout에 fcmToken 선택 필드(푸시 토큰 동시 정리, MSG-178 Codex 1R P1 반영)
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n197">
                    B
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n198">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n199">
                    hotzone 접점
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n200">
                    기존 조회 인터페이스 소비 우선. 신설 계약 필요 시 스펙에서 Owner A와 협의
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n201">
                    A/B 경계
                  </td>
                </tr>
              </tbody>
            </table>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n202" data-component="heading" id="8-확정-사항-2026-08-03-성민-결정">
              8. 확정 사항 (2026-08-03 성민 결정)
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n203">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} styles={ListRow2_styles[i]} />)}
            </ul>
            {" "}
            <p className="h-14 block my-4 text-muted-foreground max-md:h-28" data-cid="n210">
              {"미해결 질문 없음. 단 "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n211">
                선행 조건
              </strong>
              : FCM 프로젝트 셋업(Firebase 콘솔 프로젝트 + 서비스 계정 키 발급)은 성민 수동 작업 — MSG-178 구현 착수 전 필요.
            </p>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n212">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n213">
          <strong className="inline text-muted-foreground font-bold" data-cid="n214">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
