import "./ditto.css";
import ListRow from "./components/list-row";
import NavLink from "./components/nav-link";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import Tile3 from "./components/tile3";
import Tile4 from "./components/tile4";
import Tile5 from "./components/tile5";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { kind: "link", href: "/", label: "개요" },
    { kind: "button", href: "/diagrams/0", ariacurrent: "page", label: "다이어그램" },
    { kind: "link", href: "/web-ia", label: "웹 IA" },
    { kind: "link", href: "/spec", label: "기능명세서" },
    { kind: "link", href: "/adr", label: "설계 · ADR" },
    { kind: "link", href: "/dataflow", label: "데이터플로우" },
    { kind: "link", href: "/research", label: "연구노트" },
    { kind: "link", href: "/roles", label: "역할분담" },
    { kind: "link", href: "/m1", label: "M1 계획" }
];
const NavLink_data = [
    { href: "/diagrams/0", label: "0", label2: "유스케이스" },
    { href: "/diagrams/1", label: "1", label2: "IA · 정보 구조" },
    { href: "/diagrams/2", label: "2", label2: "유저 저니" },
    { href: "/diagrams/3", label: "3", label2: "서비스 아키텍처" },
    { href: "/diagrams/4", ariacurrent: "page", label: "4", label2: "시스템 아키텍처" },
    { href: "/diagrams/5", label: "5", label2: "클라우드 아키텍처 · AWS" }
];
const Tile_data = [
    { id: "f0-env-ext", text: "외부 API" },
    { id: "f0-env-client", text: "클라이언트 환경" },
    { id: "f0-env-poke", text: "PokeClip 환경 (백엔드 · AWS)" },
    { id: "f0-grp-client", text: "Client" },
    { id: "f0-grp-api", text: "API 서비스" },
    { id: "f0-grp-collector", text: "수집기" },
    { id: "f0-grp-q", text: "Queue (SQS·Redis Streams)" },
    { id: "f0-grp-wrk", text: "잡 워커" },
    { id: "f0-grp-data", text: "Data Tier" }
];
const Tile2_data = [
    { id: "f0-cl-obs", text: "OBS 플러그인", text2: "(스트리머 · C++ 네이티브)" },
    { id: "f0-cl-dash", text: "웹 대시보드", text2: "(스트리머·편집자 · React)" },
    { id: "f0-cl-ops", text: "운영 콘솔", text2: "(운영자 · React SPA)" },
    { id: "f0-sv-auth", text: "Auth·Account Service", text2: "(Spring Boot · H1~H5)" },
    { id: "f0-sv-clip", text: "Clip Service", text2: "(Spring Boot · D2·E2·E3·E8·F4)" },
    { id: "f0-sv-media", text: "Media Origin", text2: "(Go · 미디어 인제스트 · B1~B7)" },
    { id: "f0-sv-chat", text: "Chat Collector·Analytics", text2: "(Node·TS · C1~C6)" }
];
const Tile3_data = [
    { id: "f0-q-evt", text: "방송이벤트 큐" },
    { id: "f0-q-render", text: "렌더 잡 큐" },
    { id: "f0-q-ai", text: "AI 잡 큐" },
    { id: "f0-q-upload", text: "업로드 잡 큐" }
];
const Tile4_data = [
    { id: "f0-sv-render", text: "Render·Upload Worker", text2: "(Spring+FFmpeg · F1~F5)" },
    { id: "f0-sv-ai", text: "AI Worker", text2: "(Python·Whisper · E4·E7)" },
    { id: "f0-st-rd", text: "Redis", text2: "(세션·라이브 상태·SSE 팬아웃)" },
    { id: "f0-st-pg", text: "PostgreSQL", text2: "(메타·상태·지표 · 소유: Auth·Clip·Chat)" },
    { id: "f0-st-s3", text: "S3", text2: "(세그먼트·VOD·클립·채팅 아카이브)" }
];
const Tile5_data = [
    { id: "f0-ex-google", text: "Google OAuth" },
    { id: "f0-ex-sm", text: "Secrets Manager" },
    { id: "f0-ex-chzzk", text: "CHZZK" },
    { id: "f0-ex-soop", text: "SOOP" },
    { id: "f0-ex-youtube", text: "YouTube Data API" },
    { id: "f0-ex-cw", text: "CloudWatch" }
];
const ListRow_cids: string[][] = [
    ["n10", "n11"],
    ["n12", "n13"],
    ["n14", "n15"],
    ["n16", "n17"],
    ["n18", "n19"],
    ["n20", "n21"],
    ["n22", "n23"],
    ["n24", "n25"],
    ["n26", "n27"]
];
const NavLink_cids: string[][] = [
    ["n36", "n37"],
    ["n38", "n39"],
    ["n40", "n41"],
    ["n42", "n43"],
    ["n44", "n45"],
    ["n46", "n47"]
];
const Tile_cids: string[][] = [
    ["n71", "n72"],
    ["n73", "n74"],
    ["n75", "n76"],
    ["n77", "n78"],
    ["n79", "n80"],
    ["n81", "n82"],
    ["n83", "n84"],
    ["n85", "n86"],
    ["n87", "n88"]
];
const Tile2_cids: string[][] = [
    ["n89", "n90", "n91"],
    ["n92", "n93", "n94"],
    ["n95", "n96", "n97"],
    ["n98", "n99", "n100"],
    ["n101", "n102", "n103"],
    ["n104", "n105", "n106"],
    ["n107", "n108", "n109"]
];
const Tile3_cids: string[][] = [
    ["n110", "n111"],
    ["n112", "n113"],
    ["n114", "n115"],
    ["n116", "n117"]
];
const Tile4_cids: string[][] = [
    ["n118", "n119", "n120"],
    ["n121", "n122", "n123"],
    ["n124", "n125", "n126"],
    ["n127", "n128", "n129"],
    ["n130", "n131", "n132"]
];
const Tile5_cids: string[][] = [
    ["n133", "n134"],
    ["n135", "n136"],
    ["n137", "n138"],
    ["n139", "n140"],
    ["n141", "n142"],
    ["n143", "n144"]
];
const ListRow_styles = [
    { className: "text-muted-foreground" },
    { className: "text-accent font-bold bg-surface-4" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const NavLink_styles = [
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-foreground text-background font-semibold bg-foreground", className2: "bg-surface-7" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" }
];
const Tile_styles = [
    { className: "w-427.5 h-39.5 border-2 border-dotted border-color-025 top-42.5 left-155 rounded-2xl", className2: "w-[70.3px] h-4.5 -top-[0.6875rem] left-4 px-2 text-color-023 text-sm font-bold leading-[0.9375rem]" },
    { className: "w-88 h-309.5 border-2 border-dotted border-color-025 top-98 left-10 rounded-2xl", className2: "w-[7.3625rem] h-4.5 -top-[0.6875rem] left-4 px-2 text-color-023 text-sm font-bold leading-[0.9375rem]" },
    { className: "w-557 h-309.5 border-2 border-dotted border-color-025 top-98 left-108 rounded-2xl", className2: "w-[202.3px] h-4.5 -top-[0.6875rem] left-4 px-2 text-color-023 text-sm font-bold leading-[0.9375rem]" },
    { className: "w-72 h-225 border border-dashed border-color-013 top-112.5 left-18 rounded-xl", className2: "w-11 h-3 -top-[0.5625rem] left-3.5 px-1.5 text-color-013 text-xs font-semibold leading-3" },
    { className: "w-86 h-90 border border-dashed border-color-013 top-107.5 left-119 rounded-xl", className2: "w-[4.4rem] h-[0.9375rem] -top-[0.5625rem] left-3.5 px-1.5 text-color-013 text-xs font-semibold leading-3" },
    { className: "w-86 h-47.5 border border-dashed border-color-013 top-277.5 left-119 rounded-xl", className2: "w-12 h-[0.9375rem] -top-[0.5625rem] left-3.5 px-1.5 text-color-013 text-xs font-semibold leading-3" },
    { className: "w-75 h-212.5 border border-dashed border-color-013 top-117.5 left-237.5 rounded-xl", className2: "w-[10.375rem] h-3 -top-[0.5625rem] left-3.5 px-1.5 text-color-013 text-xs font-semibold leading-3" },
    { className: "w-80 h-130 border border-dashed border-color-013 top-150 left-[86.5625rem] rounded-xl", className2: "w-[3.2rem] h-[0.9375rem] -top-[0.5625rem] left-3.5 px-1.5 text-color-013 text-xs font-semibold leading-3" },
    { className: "w-110 h-220 border border-dashed border-color-013 top-112.5 left-505 rounded-xl", className2: "w-[3.8125rem] h-3 -top-[0.5625rem] left-3.5 px-1.5 text-color-013 text-xs font-semibold leading-3" }
];
const Tile2_styles = [
    { className: "w-60 h-27 top-125 left-24 bg-surface" },
    { className: "w-60 h-27 top-217.5 left-24 bg-surface" },
    { className: "w-60 h-25 top-307.5 left-24 bg-surface" },
    { className: "w-71 h-25 top-117.5 left-126.5 bg-surface" },
    { className: "w-71 h-25 top-160 left-126.5 bg-surface" },
    { className: "w-71 h-27 top-225 left-126.5 bg-clr-26" },
    { className: "w-71 h-27 top-287.5 left-126.5 bg-surface" }
];
const Tile3_styles = [
    { className: "top-130" },
    { className: "top-180" },
    { className: "top-230" },
    { className: "top-280" }
];
const Tile4_styles = [
    { className: "w-62.5 h-27 top-165 left-[88.4375rem]" },
    { className: "w-62.5 h-27 top-235 left-[88.4375rem]" },
    { className: "w-90 h-25 top-127.5 left-515" },
    { className: "w-90 h-31 top-195 left-515" },
    { className: "w-90 h-31 top-270 left-515" }
];
const Tile5_styles = [
    { className: "w-[12.8125rem] left-165" },
    { className: "w-[14.0625rem] left-[57.1875rem]" },
    { className: "w-[12.8125rem] left-300" },
    { className: "w-[11.5625rem] left-367.5" },
    { className: "w-[15.9375rem] left-430" },
    { className: "w-52.5 left-[127.8125rem]" }
];

export default function Page() {
  return (
    <>
      <div className="h-full block" data-cid="n1" id="root">
        <a className="w-30 h-[2.7rem] block absolute -top-12 left-4 z-100 py-2 px-4 rounded-[10px] text-background bg-foreground cursor-pointer max-md:w-28.5 max-md:h-[41.3px] md:max-lg:h-[42.5px]" data-cid="n2" data-component="link" href="#main">
          본문 바로가기
        </a>
        <header className="h-[58.3px] border-b border-solid border-b-border block sticky top-0 z-40 bg-background [backdrop-filter:blur(10px)] max-md:h-[6.175rem]" data-cid="n3">
          <div className="h-full flex max-w-295 mx-auto py-[0.7rem] px-10 items-center gap-[2.4rem] max-md:px-[1.0875rem] max-md:flex-wrap max-md:gap-y-[0.2rem] max-md:gap-x-4 md:max-lg:px-[1.7rem] md:max-lg:gap-[1.4375rem]" data-cid="n4">
            <a className="h-[28.5px] flex items-baseline gap-2 text-[1.0625rem] font-extrabold leading-[1.8125rem] tracking-[-0.35px] whitespace-nowrap text-nowrap cursor-pointer" data-cid="n5" data-component="link" href="/">
              <span className="h-[9.5px] block rounded-[50%] self-center bg-color-017 shadow-[var(--clr-3)_0px_0px_0px_3.46498px] [animation-name:rec-pulse] [animation-duration:2.2s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] max-md:shadow-[var(--clr-4)_0px_0px_0px_4.20904px] md:max-lg:shadow-[var(--clr-7)_0px_0px_0px_5.9759px] 2xl:shadow-[var(--clr-25)_0px_0px_0px_2.06754px]" data-cid="n6" aria-hidden="true" />
              PokeClip
              <span className="block text-color-005 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1rem] tracking-[1.79px] uppercase" data-cid="n7">
                Architecture
              </span>
            </a>
            <nav className="block min-w-0 max-md:order-[3]" data-cid="n8" data-component="nav" aria-label="주요 메뉴">
              <ul className="flex gap-[0.7rem] overflow-auto [list-style-type:none] list-outside max-md:-mx-2 max-md:pt-[0.15rem] max-md:pb-[0.4rem] max-md:px-2 max-md:gap-1 md:max-lg:gap-[7.7px]" data-cid="n9">
                {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
              </ul>
            </nav>
          </div>
        </header>
        <main className="block" data-cid="n28" id="main">
          <div className="block max-w-295 mx-auto pt-[3.4rem] pb-[5.6rem] px-10 max-md:pt-8 max-md:pb-14 max-md:px-[1.0875rem] md:max-lg:pt-[2.6rem] md:max-lg:pb-[69.1px] md:max-lg:px-[1.7rem] 2xl:pt-16 2xl:pb-26" data-cid="n29">
            <header className="w-full max-w-200 block mb-[2.8rem] max-md:mb-[1.8rem] md:max-lg:mb-[2.1625rem] 2xl:mb-12" data-cid="n30">
              <p className="block mb-[0.9rem] text-accent [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.3125rem] tracking-[1.75px] uppercase" data-cid="n31">
                Diagrams 0–5
              </p>
              <h1 className="block text-[2.625rem] font-extrabold leading-[3.125rem] tracking-[-0.84px] text-balance max-md:text-[1.75rem] max-md:leading-[2.0625rem] max-md:tracking-[-0.56px] md:max-lg:text-[2.125rem] md:max-lg:leading-10 md:max-lg:tracking-[-0.68px] 2xl:text-[2.6875rem] 2xl:leading-[3.1875rem] 2xl:tracking-[-0.86px]" data-cid="n32" data-component="heading">
                아키텍처 다이어그램
              </h1>
              <p className="block mt-[0.9rem] text-muted-foreground text-[1.0625rem] leading-[1.75rem] max-lg:text-base max-md:leading-[1.625rem] md:max-lg:leading-[1.6875rem]" data-cid="n33">
                self-contained HTML이 원본이다 — 다이어그램 보기는 화면 폭에 맞춰 자동 축소, 문서 보기는 같은 내용을 반응형 텍스트로 보여준다.
              </p>
            </header>
            <div className="flex mb-[1.4rem] flex-wrap justify-between items-center gap-4" data-cid="n34">
              <nav className="flex flex-wrap gap-2" data-cid="n35" data-component="nav" aria-label="다이어그램 선택">
                {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
              </nav>
              <div className="border border-solid border-color-009 flex p-[0.1875rem] rounded-[999px] bg-surface" data-cid="n48" aria-label="보기 방식" role="group">
                <button className="block py-[5.1px] px-[0.95rem] rounded-[999px] text-background text-sm font-semibold leading-[1.375rem] text-center bg-foreground cursor-pointer" data-cid="n49" data-component="button" aria-pressed="true" type="button">
                  다이어그램
                </button>
                <button className="block py-[5.1px] px-[0.95rem] rounded-[999px] text-muted-foreground text-sm leading-[1.375rem] text-center cursor-pointer" data-cid="n50" data-component="button" aria-pressed="false" type="button">
                  문서 보기
                </button>
              </div>
            </div>
            <section className="block" data-cid="n51" aria-label="시스템 아키텍처 다이어그램 뷰어">
              <div className="flex mb-[0.7rem] flex-wrap justify-between items-baseline gap-4" data-cid="n52">
                <p className="h-[1.825rem] flex items-baseline gap-[0.6rem] font-bold max-md:h-[28.3px] md:max-lg:h-[29.5px]" data-cid="n53">
                  <span className="block text-color-017 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[1.625rem] leading-[1.625rem]" data-cid="n54" aria-hidden="true">
                    4
                  </span>
                  시스템 아키텍처
                  <span className="block text-color-005 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-xs font-medium leading-[1.1875rem] tracking-[1.38px] uppercase" data-cid="n55">
                    System Architecture
                  </span>
                </p>
                <div className="flex gap-[0.9rem] text-[0.8125rem] leading-[1.375rem]" data-cid="n56">
                  <div className="border border-solid border-color-009 flex rounded-[999px] items-stretch overflow-hidden bg-surface" data-cid="n57" aria-label="확대/축소" role="group">
                    <button className="block py-0.5 px-[0.6rem] text-muted-foreground text-sm leading-[1.25rem] text-center cursor-pointer" data-cid="n58" data-component="button" aria-label="축소" title="축소" type="button">
                      −
                    </button>
                    <button className="w-[3.4rem] border-r border-solid border-r-border border-l border-l-border block min-w-[3.4rem] py-0.5 px-[0.6rem] text-muted-foreground [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-xs leading-[1rem] text-center cursor-pointer" data-cid="n59" data-component="button" title="화면 폭에 맞춤" type="button">
                      100%
                    </button>
                    <button className="block py-0.5 px-[0.6rem] text-muted-foreground text-sm leading-[1.25rem] text-center cursor-pointer" data-cid="n60" data-component="button" aria-label="확대" title="확대" type="button">
                      ＋
                    </button>
                  </div>
                  <button className="border-b border-solid border-b-color-009 block pb-px text-muted-foreground text-center cursor-pointer" data-cid="n61" data-component="button" type="button">
                    전체화면
                  </button>
                  <a className="border-b border-solid border-b-color-009 block pb-px text-muted-foreground cursor-pointer" data-cid="n62" data-component="link" href="https://poke-clip-architecture.vercel.app/diagrams/4_Pokeclip_SysA.html" rel="noreferrer" target="_blank">
                    원본 새 탭 ↗
                  </a>
                </div>
              </div>
              <div className="h-[43.3125rem] border border-solid border-border block rounded-[10px] overflow-hidden bg-surface max-md:h-[13.4375rem] md:max-lg:h-112.5" data-cid="n63">
                <div className="h-full block relative" data-cid="n64">
                  <div className="w-675 h-425 block absolute overflow-hidden transform-[matrix(0.406667,0,0,0.406667,0,0)] origin-[0px_0px] pointer-events-none max-md:transform-[matrix(0.125278,0,0,0.125278,0,0)] md:max-lg:transform-[matrix(0.263565,0,0,0.263565,0,0)]" data-cid="n65" title="시스템 아키텍처 다이어그램">
                    <div className="w-675 h-425 block relative text-color-008 [font-family:Pretendard,_'Noto_Sans_KR',_'Noto_Sans_CJK_KR',_'Apple_SD_Gothic_Neo',_sans-serif] text-base leading-4.5 bg-surface" data-cid="n66">
                      <div className="w-[23rem] h-16.5 flex absolute top-6 left-8.5 pr-6.5 pl-5.5 items-center bg-color-004" data-cid="n67">
                        <h1 className="block text-surface text-[2.125rem] font-extrabold leading-[2.4375rem] tracking-[-0.5px] whitespace-nowrap" data-cid="n68" data-component="heading">
                          System Architecture
                        </h1>
                      </div>
                      {" "}
                      <div className="w-113 h-2 block absolute top-24.5 left-8.5 bg-color-004" data-cid="n69" />
                      {" "}
                      <div className="w-[46.425rem] h-[1.1875rem] block absolute top-29.5 left-9 text-[0.9375rem] leading-4" data-cid="n70">
                        클라이언트 3 · 백엔드 서비스 6 · 데이터 3 — 배포 관점의 컨테이너·큐·외부 API 배치 (SA와 같은 시스템, 다른 줌)
                      </div>
                      {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} styles={Tile_styles[i]} />)}
                      {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} styles={Tile2_styles[i]} />)}
                      {Tile3_data.map((d, i) => <Tile3 key={i} d={d} cids={Tile3_cids[i]} styles={Tile3_styles[i]} />)}
                      {Tile4_data.map((d, i) => <Tile4 key={i} d={d} cids={Tile4_cids[i]} styles={Tile4_styles[i]} />)}
                      {Tile5_data.map((d, i) => <Tile5 key={i} d={d} cids={Tile5_cids[i]} styles={Tile5_styles[i]} />)}
                      {" "}
                      <svg className="w-675 h-425 block absolute overflow-hidden pointer-events-none" data-cid="n145" data-component="image" id="f0-wires" fill="currentColor">
                        <defs>
                          <marker id="ar" markerWidth="11" markerHeight="11" refX="8.4" refY="4.5" orient="auto" markerUnits="userSpaceOnUse">
                            <path d="M1,1 L8,4.5 L1,8" fill="none" stroke="#1f2937" strokeWidth="1.3" />
                          </marker>
                        </defs>
                        <path d="M 336 596 L 421 596 L 421 942 L 506 942" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 336 520 L 443 520 L 443 508 L 506 508" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 336 596 L 399 596 L 399 670 L 506 670" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 336 882 L 465 882 L 465 532 L 506 532" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 336 882 L 377 882 L 377 690 L 506 690" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 336 954 L 487 954 L 487 966 L 506 966" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 336 966 L 355 966 L 355 1204 L 506 1204" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 336 1242 L 421 1242 L 421 710 L 506 710" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 520 L 814 520 L 814 627 L 2036 627 L 2036 818 L 2060 818" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 728 L 830 728 L 830 842 L 2060 842" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 652 L 1381 652 L 1381 548 L 2060 548" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 954 L 814 954 L 814 1064 L 2036 1064 L 2036 1118 L 2060 1118" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 954 L 814 954 L 814 623 L 2036 623 L 2036 572 L 2060 572" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 1162 L 808 1162 L 808 866 L 2060 866" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 1204 L 814 1204 L 814 1229 L 2036 1229 L 2036 1142 L 2060 1142" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 1665 756 L 1862.5 756 L 1862.5 1166 L 2060 1166" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 912 L 885 912 L 885 566 L 980 566" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 980 600 L 907 600 L 907 1204 L 790 1204" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 980 600 L 863 600 L 863 670 L 790 670" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 728 L 929 728 L 929 766 L 980 766" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 1220 732 L 1317.5 732 L 1317.5 702 L 1415 702" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 728 L 940 728 L 940 966 L 980 966" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 1220 994 L 1295.5 994 L 1295.5 994 L 1415 994" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 728 L 951 728 L 951 1166 L 980 1166" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 1220 1132 L 1273.5 1132 L 1273.5 726 L 1415 726" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 1415 690 L 1102.5 690 L 1102.5 690 L 790 690" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 1415 994 L 1391 994 L 1391 852 L 814 852 L 814 710 L 790 710" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 762.5 470 L 762.5 386.5 L 762.5 386.5 L 762.5 303" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 778 470 L 778 404.5 L 1027.5 404.5 L 1027.5 303" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 1653 660 L 1653 481.5 L 1847.5 481.5 L 1847.5 303" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 1653 660 L 1653 499.5 L 2150 499.5 L 2150 303" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 1204 L 880 1204 L 880 355 L 1302.5 355 L 1302.5 303" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                        <path d="M 790 1204 L 905 1204 L 905 372 L 1562.5 372 L 1562.5 303" fill="none" stroke="#1f2937" strokeWidth="1.3" markerEnd="url(#ar)" />
                      </svg>
                      {" "}
                    </div>
                  </div>
                </div>
              </div>
              <p className="block mt-[0.7rem] text-color-005 text-[0.8125rem] leading-[1.375rem]" data-cid="n146">
                박스를 클릭하면 화살표로 연결된 요소들이 떠오르며 강조됩니다 — 빈 곳이나 같은 박스를 다시 클릭하면 해제.
              </p>
            </section>
          </div>
        </main>
        <footer className="border-t border-solid border-t-border block bg-surface" data-cid="n147">
          <div className="block max-w-295 mx-auto pt-[2.2rem] pb-12 px-10 text-muted-foreground text-[0.9375rem] leading-[1.5rem] max-md:px-[1.0875rem] md:max-lg:px-[1.7rem]" data-cid="n148">
            <p className="h-[24.3px] block max-md:h-[3.0375rem]" data-cid="n149">
              <strong className="inline font-bold" data-cid="n150">
                PokeClip
              </strong>
              {" — 스트리밍 하이라이트·클립 자동화 서비스의 아키텍처 산출물."}
            </p>
          </div>
        </footer>
      </div>
      {" "}
    </>
  );
}
