import "./ditto.css";
import ListRow from "./components/list-row";
import Tile from "./components/tile";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import Tile2 from "./components/tile2";
import ListRow4 from "./components/list-row4";
import ListRow5 from "./components/list-row5";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { kind: "link", href: "/", label: "개요" },
    { kind: "link", href: "/diagrams/0", label: "다이어그램" },
    { kind: "link", href: "/web-ia", label: "웹 IA" },
    { kind: "link", href: "/spec", label: "기능명세서" },
    { kind: "link", href: "/adr", label: "설계 · ADR" },
    { kind: "link", href: "/dataflow", label: "데이터플로우" },
    { kind: "button", href: "/research", ariacurrent: "page", label: "연구노트" },
    { kind: "link", href: "/roles", label: "역할분담" },
    { kind: "link", href: "/m1", label: "M1 계획" }
];
const Tile_data = [
    { description: "실험 조건", description2: ": 채팅을 5초 윈도우로 집계(수집기는 1/3/5/10초 윈도우 지원)." },
    { description: "결과", description2: ": 대규모 방송에서 채팅의 방송 전체 평균은 방송 내내 안정적(비등비등). 따라서 \"평균 대비 2~3배\" 배율 임계로 잡은 하이라이트 구간은 방송이 진행되어도 거의 고정된다." },
    { description: "왜 그런가 (스파이크 희소성)", description2: ": 스파이크는 시간적으로 희소하다. 6시간 방송에서 30초짜리 10배 스파이크는 전체 샘플의 ~0.1%라 전체 평균을 1%도 못 움직인다. → \"지금 4배인 구간이, 나중에 더 큰 스파이크가 나오면 2배로 강등되지 않을까\"는 기우." },
    { description: "평균 vs 중앙값 결론 (스케일에 따라 답이 다름)", description2: ":" }
];
const ListRow2_data = [
    { text: "전체 평균 = (60×180 + 300×180) ÷ 360 = ", text2: "분당 180개" },
    { text: "전반의 진짜 하이라이트(분당 240 = 그 시점 기준 4배) → 180 기준 1.3배 → ", text2: "과소 판정(못 잡음)" },
    { text: "후반의 평범한 출렁임(분당 380) → 180 기준 2.1배 → ", text2: "과대 판정(가짜 카드)" }
];
const ListRow3_data = [
    { text: "창 길이 W = 튜닝 파라미터", text2: ": 짧으면 적응 빠름·노이즈 민감, 길면 안정·적응 느림." },
    { text: "전환 구간", text2: ": 레이드 직후 W분 동안 유입 자체가 스파이크로 잡힘 — 단, \"레이드 순간\"도 클립 가치가 있어 오탐이 아니라 제품 판단의 영역(국면 전환 태깅으로 분리 가능, §5)." },
    { text: "스파이크의 자기 오염", text2: ": 스파이크가 롤링 창에 들어가면 직후 베이스라인이 부풀어 연속 하이라이트를 놓칠 수 있음 → 롤링 계산에서 이상치 제외(트림 평균) 또는 중앙값 사용(§2 결론과 연결)." }
];
const Tile2_data = [
    { text: "장기 이평선", text2: "방송 전체/누적 평균", text3: "이 방송의 체급·기본 반응성 (실측상 안정)" },
    { text: "단기 이평선", text2: "롤링 10~20분", text3: "\"지금의 평상시\"" },
    { text: "캔들(현재가)", text2: "5초 윈도우 채팅량", text3: "순간값" },
    { text: "거래량 급증 국면 전환", text2: "단기선이 장기선을 크게 상회", text3: "레이드·사건으로 판이 커진 상태" }
];
const ListRow4_data = [
    { text: "배율 임계 K의 채널 유형별 값 — 대형(반응 위주)과 소통형(3~5%)에서 동일 K가 유효한가? 소통형은 베이스라인 오염 보정(소통 채팅 필터 피처: 멘션·질문형·스트리머 응답 인접성)이 선행되어야 하는가?" },
    { text: "롤링 창 길이 W — 10분/15분/20분 중 어디가 적정인가? 게임 장르(순간 반응형 vs 스토리형)별로 달라야 하는가?" },
    { text: "롤링 창 내 통계량 — 트림 평균 vs 중앙값, 트림 비율은?" },
    { text: "국면 전환(단기>장기) 자체를 카드로 발행할 것인가?" },
    { text: "고유 채터 수 지표의 실효성 — 메시지 수 대비 어느 정도 개선되는가? (데이터 수집 후 A/B)" },
    { text: "소형 채널: 채팅 외 신호(핫키 빈도, 시청자 수 변화, 오디오 이벤트 등) 결합의 가능성 — 장기 연구 과제." }
];
const ListRow5_data = [
    { text: "베이스라인", text2: ": 배율 판정의 분모가 되는 \"평상시\" 채팅 수준." },
    { text: "윈도우", text2: ": 채팅량을 집계하는 시간 단위(1/3/5/10초)." },
    { text: "워밍업", text2: ": 방송 초반 베이스라인 학습 기간(카드 발행 보류)." },
    { text: "드리프트", text2: ": 방송 중 시청자 규모 변화로 평상시 수준 자체가 이동하는 현상." },
    { text: "트림 평균", text2: ": 상·하위 이상치를 제외하고 낸 평균." }
];
const ListRow_cids: string[][] = [
    ["n10", "n11"],
    ["n12", "n13"],
    ["n14", "n15"],
    ["n16", "n17"],
    ["n18", "n19"],
    ["n20", "n21"],
    ["n22", "n23"],
    ["n24", "n25"],
    ["n26", "n27"]
];
const Tile_cids: string[][] = [
    ["n76", "n77"],
    ["n78", "n79"],
    ["n80", "n81"],
    ["n82", "n83"]
];
const ListRow2_cids: string[][] = [
    ["n97", "n98"],
    ["n99", "n100"],
    ["n101", "n102"]
];
const ListRow3_cids: string[][] = [
    ["n114", "n115"],
    ["n116", "n117"],
    ["n118", "n119"]
];
const Tile2_cids: string[][] = [
    ["n134", "n135", "n136", "n137"],
    ["n138", "n139", "n140", "n141"],
    ["n142", "n143", "n144", "n145"],
    ["n146", "n147", "n148", "n149"]
];
const ListRow4_cids: string[][] = [
    ["n169"],
    ["n170"],
    ["n171"],
    ["n172"],
    ["n173"],
    ["n174"]
];
const ListRow5_cids: string[][] = [
    ["n178", "n179"],
    ["n180", "n181"],
    ["n182", "n183"],
    ["n184", "n185"],
    ["n186", "n187"]
];
const ListRow_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-accent font-bold bg-surface-4" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const Tile_styles = [
    { className: "h-[1.7rem] max-md:h-[50.5px] md:max-lg:h-[26.5px]" },
    { className: "h-[3.4rem] max-md:h-[4.7375rem] md:max-lg:h-[3.3125rem]" },
    { className: "h-[3.4rem] max-md:h-[126.3px] md:max-lg:h-[4.975rem]" },
    { className: "h-[1.7rem] max-md:h-[25.3px] md:max-lg:h-[26.5px]" }
];
const ListRow3_styles = [
    { className: "h-[1.7rem] max-md:h-[50.5px] md:max-lg:h-[26.5px]" },
    { className: "h-[3.4rem] max-md:h-[6.3125rem] md:max-lg:h-[3.3125rem]" },
    { className: "h-[3.4rem] max-md:h-[6.3125rem] md:max-lg:h-[3.3125rem]" }
];
const Tile2_styles = [
    { className: "border-b border-solid border-b-border", className2: "border-b border-solid border-b-border", className3: "border-b border-solid border-b-border" },
    { className: "border-b border-solid border-b-border", className2: "border-b border-solid border-b-border", className3: "border-b border-solid border-b-border" },
    { className: "border-b border-solid border-b-border", className2: "border-b border-solid border-b-border", className3: "border-b border-solid border-b-border" },
    {  }
];
const ListRow5_styles = [
    { className: "max-md:h-[50.5px]" },
    { className: "max-md:h-[25.3px]" },
    { className: "max-md:h-[50.5px]" },
    { className: "max-md:h-[50.5px]" },
    { className: "max-md:h-[25.3px]" }
];

export default function Page() {
  return (
    <>
      <div className="h-full block" data-cid="n1" id="root">
        <a className="w-30 h-[2.7rem] block absolute -top-12 left-4 z-100 py-2 px-4 rounded-[10px] text-background bg-foreground cursor-pointer max-md:w-28.5 max-md:h-[41.3px] md:max-lg:h-[42.5px]" data-cid="n2" data-component="link" href="#main">
          본문 바로가기
        </a>
        <header className="h-[58.3px] border-b border-solid border-b-border block sticky top-0 z-40 bg-background [backdrop-filter:blur(10px)] max-md:h-[6.175rem]" data-cid="n3">
          <div className="h-full flex max-w-295 mx-auto py-[0.7rem] px-10 items-center gap-[2.4rem] max-md:px-[1.0875rem] max-md:flex-wrap max-md:gap-y-[0.2rem] max-md:gap-x-4 md:max-lg:px-[1.7rem] md:max-lg:gap-[1.4375rem]" data-cid="n4">
            <a className="h-[28.5px] flex items-baseline gap-2 text-[1.0625rem] font-extrabold leading-[1.8125rem] tracking-[-0.35px] whitespace-nowrap text-nowrap cursor-pointer" data-cid="n5" data-component="link" href="/">
              <span className="h-[9.5px] block rounded-[50%] self-center bg-color-017 shadow-[var(--clr-3)_0px_0px_0px_3.31617px] [animation-name:rec-pulse] [animation-duration:2.2s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] max-md:shadow-[var(--clr-12)_0px_0px_0px_1.03553px] md:max-lg:shadow-[var(--clr-13)_0px_0px_0px_2.23062px] 2xl:shadow-[var(--clr-8)_0px_0px_0px_5.53043px]" data-cid="n6" aria-hidden="true" />
              PokeClip
              <span className="block text-color-005 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1rem] tracking-[1.79px] uppercase" data-cid="n7">
                Architecture
              </span>
            </a>
            <nav className="block min-w-0 max-md:order-[3]" data-cid="n8" data-component="nav" aria-label="주요 메뉴">
              <ul className="flex gap-[0.7rem] overflow-auto [list-style-type:none] list-outside max-md:-mx-2 max-md:pt-[0.15rem] max-md:pb-[0.4rem] max-md:px-2 max-md:gap-1 md:max-lg:gap-[7.7px]" data-cid="n9">
                {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
              </ul>
            </nav>
          </div>
        </header>
        <main className="block" data-cid="n28" id="main">
          <div className="block max-w-295 mx-auto pt-[3.4rem] pb-[5.6rem] px-10 max-md:pt-8 max-md:pb-14 max-md:px-[1.0875rem] md:max-lg:pt-[2.6rem] md:max-lg:pb-[69.1px] md:max-lg:px-[1.7rem] 2xl:pt-16 2xl:pb-26" data-cid="n29">
            <header className="w-full max-w-200 block mb-[2.8rem] max-md:mb-[1.8rem] md:max-lg:mb-[2.1625rem] 2xl:mb-12" data-cid="n30">
              <p className="block mb-[0.9rem] text-accent [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.3125rem] tracking-[1.75px] uppercase" data-cid="n31">
                Doc 8 · Research Note
              </p>
              <h1 className="block text-[2.625rem] font-extrabold leading-[3.125rem] tracking-[-0.84px] text-balance max-md:text-[1.75rem] max-md:leading-[2.0625rem] max-md:tracking-[-0.56px] md:max-lg:text-[2.125rem] md:max-lg:leading-10 md:max-lg:tracking-[-0.68px] 2xl:text-[2.6875rem] 2xl:leading-[3.1875rem] 2xl:tracking-[-0.86px]" data-cid="n32" data-component="heading">
                하이라이트 탐지 연구 노트
              </h1>
              <p className="block mt-[0.9rem] text-muted-foreground text-[1.0625rem] leading-[1.75rem] max-lg:text-base max-md:leading-[1.625rem] md:max-lg:leading-[1.6875rem]" data-cid="n33">
                채팅 반응 기반 하이라이트 탐지 방법론 — 팀 실측 기록.
              </p>
            </header>
            <div className="w-full max-w-200 block" data-cid="n34">
              <p className="h-[3.4rem] block text-muted-foreground max-md:h-[6.3125rem] md:max-lg:h-[3.3125rem]" data-cid="n35">
                {"채팅 기반 하이라이트 탐지의 방법론 정리. 팀 실측 결과 + 보완 가설을 통합했으며, "}
                <strong className="inline text-foreground font-bold" data-cid="n36">
                  차트 분석 멘토 미팅의 논의 자료
                </strong>
                {"를 겸한다. 확정 정책은 "}
                <code className="inline py-[1.7px] px-[5.7px] rounded-[5px] [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-sm leading-[1.4375rem] bg-surface-2 max-md:py-[0.1rem] max-md:px-[5.3px] max-md:text-[0.8125rem] max-md:leading-[1.375rem] md:max-lg:px-[5.5px]" data-cid="n37">
                  6_Pokeclip_설계결정.md
                </code>
                {" 11번에 요약되어 있고, 이 문서는 그 상세판이다."}
              </p>
              {" "}
              <hr className="w-200 h-px border-t border-solid border-t-border block my-[2.475rem] overflow-hidden text-color-020 max-md:w-85 max-md:my-[36.7px] md:max-lg:w-178.5 md:max-lg:my-[2.4125rem]" data-cid="n38" />
              {" "}
              <h2 className="border-t border-solid border-t-border block mt-[62.1px] pt-[33.5px] text-2xl font-bold leading-[1.9375rem] tracking-[-0.36px] max-md:mt-[57.7px] max-md:pt-[1.9375rem] max-md:text-[1.375rem] max-md:leading-[1.8125rem] max-md:tracking-[-0.33px] md:max-lg:mt-[60.7px] md:max-lg:pt-[32.7px] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.875rem] md:max-lg:tracking-[-0.35px]" data-cid="n39" data-component="heading">
                1. 채팅 신호 모델
              </h2>
              {" "}
              <p className="block mt-[16.5px] text-muted-foreground max-md:mt-[15.3px] md:max-lg:mt-4" data-cid="n40">
                채팅은 두 종류로 나뉜다.
              </p>
              {" "}
              <div className="h-[7.5875rem] border border-solid border-border block mt-[16.5px] rounded-[10px] overflow-auto bg-surface max-md:h-[13.375rem] max-md:mt-[15.3px] md:max-lg:h-[118.7px] md:max-lg:mt-4" data-cid="n41">
                <table className="w-full h-full table text-[0.9375rem] leading-[1.375rem] [border-collapse:collapse] [border-spacing:2px] max-lg:text-sm max-md:leading-[1.25rem] md:max-lg:leading-[1.3125rem]" data-cid="n42">
                  <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n43">
                    <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n44">
                      <th className="border-b border-solid border-b-border table-cell py-[8.7px] px-[0.8125rem] align-top font-bold text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px] max-md:py-2 max-md:px-3 md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n45">
                        구분
                      </th>
                      <th className="border-b border-solid border-b-border table-cell py-[8.7px] px-[0.8125rem] align-top font-bold text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px] max-md:py-2 max-md:px-3 md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n46">
                        동기
                      </th>
                      <th className="border-b border-solid border-b-border table-cell py-[8.7px] px-[0.8125rem] align-top font-bold text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px] max-md:py-2 max-md:px-3 md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n47">
                        예시
                      </th>
                      <th className="border-b border-solid border-b-border table-cell py-[8.7px] px-[0.8125rem] align-top font-bold text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px] max-md:py-2 max-md:px-3 md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n48">
                        탐지 관점
                      </th>
                    </tr>
                  </thead>
                  <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n49">
                    <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n50">
                      <td className="w-[5.8125rem] border-b border-solid border-b-border table-cell min-w-10 py-2 px-3 align-top [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.8125rem] leading-5 whitespace-nowrap text-nowrap [border-collapse:collapse] [border-spacing:2px] max-md:w-[4.875rem] max-md:min-w-[37.1px] max-md:py-[0.4625rem] max-md:px-[0.7rem] max-md:text-xs max-md:leading-[1.1875rem] md:max-lg:w-[5.4rem] md:max-lg:min-w-[2.4375rem] md:max-lg:px-[11.7px] md:max-lg:leading-[1.25rem]" data-cid="n51">
                        <strong className="inline font-bold [border-collapse:collapse] [border-spacing:2px]" data-cid="n52">
                          반응 채팅
                        </strong>
                      </td>
                      <td className="w-[12.8125rem] border-b border-solid border-b-border table-cell min-w-13.5 py-[8.7px] px-[0.8125rem] align-top text-muted-foreground [border-collapse:collapse] [border-spacing:2px] max-md:w-[76.5px] max-md:py-2 max-md:px-3 md:max-lg:w-[11.425rem] md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n53">
                        화면 사건에 대한 반사 반응
                      </td>
                      <td className="w-[298.1px] border-b border-solid border-b-border table-cell min-w-13.5 py-[8.7px] px-[0.8125rem] align-top text-muted-foreground [border-collapse:collapse] [border-spacing:2px] max-md:w-[5.6625rem] max-md:py-2 max-md:px-3 md:max-lg:w-[16.3625rem] md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n54">
                        "ㅋㅋㅋㅋ", "와", "클립각", 이모티콘 도배
                      </td>
                      <td className="w-[12.6125rem] border-b border-solid border-b-border table-cell min-w-13.5 py-[8.7px] px-[0.8125rem] align-top text-muted-foreground [border-collapse:collapse] [border-spacing:2px] max-md:w-[5.825rem] max-md:py-2 max-md:px-3 md:max-lg:w-[180.7px] md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n55">
                        <strong className="inline text-foreground font-bold [border-collapse:collapse] [border-spacing:2px]" data-cid="n56">
                          신호
                        </strong>
                        {" — 하이라이트의 원천"}
                      </td>
                    </tr>
                    <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n57">
                      <td className="w-[5.8125rem] table-cell min-w-10 py-2 px-3 align-top [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.8125rem] leading-5 whitespace-nowrap text-nowrap [border-collapse:collapse] [border-spacing:2px] max-md:w-[4.875rem] max-md:min-w-[37.1px] max-md:py-[0.4625rem] max-md:px-[0.7rem] max-md:text-xs max-md:leading-[1.1875rem] md:max-lg:w-[5.4rem] md:max-lg:min-w-[2.4375rem] md:max-lg:px-[11.7px] md:max-lg:leading-[1.25rem]" data-cid="n58">
                        <strong className="inline font-bold [border-collapse:collapse] [border-spacing:2px]" data-cid="n59">
                          소통 채팅
                        </strong>
                      </td>
                      <td className="w-[12.8125rem] table-cell min-w-13.5 py-[8.7px] px-[0.8125rem] align-top text-muted-foreground [border-collapse:collapse] [border-spacing:2px] max-md:w-[76.5px] max-md:py-2 max-md:px-3 md:max-lg:w-[11.425rem] md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n60">
                        스트리머와의 대화 목적
                      </td>
                      <td className="w-[298.1px] table-cell min-w-13.5 py-[8.7px] px-[0.8125rem] align-top text-muted-foreground [border-collapse:collapse] [border-spacing:2px] max-md:w-[5.6625rem] max-md:py-2 max-md:px-3 md:max-lg:w-[16.3625rem] md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n61">
                        질문, 인사, 관심 끌기
                      </td>
                      <td className="w-[12.6125rem] table-cell min-w-13.5 py-[8.7px] px-[0.8125rem] align-top text-muted-foreground [border-collapse:collapse] [border-spacing:2px] max-md:w-[5.825rem] max-md:py-2 max-md:px-3 md:max-lg:w-[180.7px] md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n62">
                        <strong className="inline text-foreground font-bold [border-collapse:collapse] [border-spacing:2px]" data-cid="n63">
                          잡음
                        </strong>
                        {" — 베이스라인을 오염"}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              {" "}
              <h3 className="block mt-[2.3125rem] text-[1.1875rem] font-bold leading-[1.9375rem] max-md:mt-[34.3px] max-md:text-[1.0625rem] max-md:leading-[1.75rem] md:max-lg:mt-9 md:max-lg:text-lg md:max-lg:leading-[1.875rem]" data-cid="n64" data-component="heading">
                채널 유형별 실측 (팀 연구)
              </h3>
              {" "}
              <ul className="block mt-[16.5px] pl-[1.4375rem] [list-style-type:disc] list-outside max-md:mt-[15.3px] max-md:pl-[1.3375rem] md:max-lg:mt-4 md:max-lg:pl-[22.5px]" data-cid="n65">
                <li className="h-[3.4rem] list-item mt-1.5 text-muted-foreground max-md:h-[6.3125rem] max-md:mt-[0.3375rem] md:max-lg:h-[3.3125rem] md:max-lg:mt-[0.35rem]" data-cid="n66">
                  <strong className="inline text-foreground font-bold" data-cid="n67">
                    대형 채널
                  </strong>
                  : 시청자 채팅 참여율 1~2%. 그럼에도 하이라이트가 깨끗하게 잡힌다. 해석: 스트리머가 채팅을 읽어줄 수 없는 규모라 소통 채팅의 동기가 약함 → 채팅이 반응 위주 → 신호 대 잡음(S/N)이 좋음.
                </li>
                <li className="h-[5.1rem] list-item mt-1.5 text-muted-foreground max-md:h-[126.3px] max-md:mt-[0.3375rem] md:max-lg:h-[4.975rem] md:max-lg:mt-[0.35rem]" data-cid="n68">
                  <strong className="inline text-foreground font-bold" data-cid="n69">
                    소통 중심 채널
                  </strong>
                  {" (참여율 3~5%, 예: 여성 스트리머): 하이라이트가 아니어도 참여율이 상시 높음(스트리머의 관심을 끌기 위한 채팅). 베이스라인이 소통 채팅으로 오염 — 거래량은 많은데 방향성이 없는 횡보장과 유사. "}
                  <strong className="inline text-foreground font-bold" data-cid="n70">
                    차트 분석 기법이 실제로 필요한 구간.
                  </strong>
                </li>
                <li className="h-[5.1rem] list-item mt-1.5 text-muted-foreground max-md:h-[9.475rem] max-md:mt-[0.3375rem] md:max-lg:h-[4.975rem] md:max-lg:mt-[0.35rem]" data-cid="n71">
                  <strong className="inline text-foreground font-bold" data-cid="n72">
                    소형 채널
                  </strong>
                  {": 채팅이 거의 전부 소통 채팅(시청자는 \"내 채팅을 읽어주는 것\"이 좋아서 침) + 절대량 부족. 펜타킬 등에서 평소보다 늘긴 하지만 채팅 단독으로 신뢰성 있게 잡는 것은 "}
                  <strong className="inline text-foreground font-bold" data-cid="n73">
                    현재로선 불가 판단
                  </strong>
                  . 데이터 축적 후 재검토하는 미확정 연구 과제 — 설계 전제로 삼지 않는다. 소형 유저는 핫키 모드(수동)로 커버.
                </li>
              </ul>
              {" "}
              <hr className="w-200 h-px border-t border-solid border-t-border block my-[2.475rem] overflow-hidden text-color-020 max-md:w-85 max-md:my-[36.7px] md:max-lg:w-178.5 md:max-lg:my-[2.4125rem]" data-cid="n74" />
              {" "}
              <h2 className="border-t border-solid border-t-border block mt-[62.1px] pt-[33.5px] text-2xl font-bold leading-[1.9375rem] tracking-[-0.36px] max-md:mt-[57.7px] max-md:pt-[1.9375rem] max-md:text-[1.375rem] max-md:leading-[1.8125rem] max-md:tracking-[-0.33px] md:max-lg:mt-[60.7px] md:max-lg:pt-[32.7px] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.875rem] md:max-lg:tracking-[-0.35px]" data-cid="n75" data-component="heading">
                2. 베이스라인 실측 — 전체 평균의 안정성
              </h2>
              {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} styles={Tile_styles[i]} />)}
              {" "}
              <ul className="block mt-[16.5px] pl-[1.4375rem] [list-style-type:disc] list-outside max-md:mt-[15.3px] max-md:pl-[1.3375rem] md:max-lg:mt-4 md:max-lg:pl-[22.5px]" data-cid="n84">
                <li className="h-[1.7rem] list-item mt-1.5 text-muted-foreground max-md:h-[50.5px] max-md:mt-[0.3375rem] md:max-lg:h-[26.5px] md:max-lg:mt-[0.35rem]" data-cid="n85">
                  <strong className="inline text-foreground font-bold" data-cid="n86">
                    긴 창(방송 전체·누적)
                  </strong>
                  {": 스파이크가 희소해 평균이 강건 → 더 단순한 "}
                  <strong className="inline text-foreground font-bold" data-cid="n87">
                    평균
                  </strong>
                  {" 채택."}
                </li>
                <li className="h-[1.7rem] list-item mt-1.5 text-muted-foreground max-md:h-[4.7375rem] max-md:mt-[0.3375rem] md:max-lg:h-[3.3125rem] md:max-lg:mt-[0.35rem]" data-cid="n88">
                  <strong className="inline text-foreground font-bold" data-cid="n89">
                    짧은 창(롤링 10~20분)
                  </strong>
                  {": 창 내 스파이크 비중이 커져 평균이 부풀 수 있음 → "}
                  <strong className="inline text-foreground font-bold" data-cid="n90">
                    중앙값 또는 트림 평균
                  </strong>
                  (이상치 제외)이 강건.
                </li>
              </ul>
              {" "}
              <hr className="w-200 h-px border-t border-solid border-t-border block my-[2.475rem] overflow-hidden text-color-020 max-md:w-85 max-md:my-[36.7px] md:max-lg:w-178.5 md:max-lg:my-[2.4125rem]" data-cid="n91" />
              {" "}
              <h2 className="border-t border-solid border-t-border block mt-[62.1px] pt-[33.5px] text-2xl font-bold leading-[1.9375rem] tracking-[-0.36px] max-md:mt-[57.7px] max-md:pt-[1.9375rem] max-md:text-[1.375rem] max-md:leading-[1.8125rem] max-md:tracking-[-0.33px] md:max-lg:mt-[60.7px] md:max-lg:pt-[32.7px] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.875rem] md:max-lg:tracking-[-0.35px]" data-cid="n92" data-component="heading">
                3. 문제 케이스 — 베이스라인 드리프트
              </h2>
              {" "}
              <p className="block mt-[16.5px] text-muted-foreground max-md:mt-[15.3px] md:max-lg:mt-4" data-cid="n93">
                전체 평균의 전제는 "시청자 규모가 방송 내내 안정적"이다. 레이드 유입·사건으로 규모가 급변하면 전제가 깨진다.
              </p>
              {" "}
              <p className="h-[1.7rem] block mt-[16.5px] text-muted-foreground max-md:h-[50.5px] max-md:mt-[15.3px] md:max-lg:h-[26.5px] md:max-lg:mt-4" data-cid="n94">
                <strong className="inline text-foreground font-bold" data-cid="n95">
                  숫자 예시
                </strong>
                : 6시간 방송. 전반 3시간은 시청자 1,000명·분당 60개, 3시간째 레이드로 5,000명·분당 300개.
              </p>
              {" "}
              <ul className="block mt-[16.5px] pl-[1.4375rem] [list-style-type:disc] list-outside max-md:mt-[15.3px] max-md:pl-[1.3375rem] md:max-lg:mt-4 md:max-lg:pl-[22.5px]" data-cid="n96">
                {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
              </ul>
              {" "}
              <p className="h-[3.4rem] block mt-[16.5px] text-muted-foreground max-md:h-[6.3125rem] max-md:mt-[15.3px] md:max-lg:h-[3.3125rem] md:max-lg:mt-4" data-cid="n103">
                <strong className="inline text-foreground font-bold" data-cid="n104">
                  원리
                </strong>
                : 배율 임계는 비교 기준이 "그 시점의 평상시"일 때만 유효하다. 규모가 급변하면 방송 안에 평상시가 두 개 생기고, 전체 평균은 그 사이의 어중간한 값이라 양쪽 다 틀린다.
              </p>
              {" "}
              <hr className="w-200 h-px border-t border-solid border-t-border block my-[2.475rem] overflow-hidden text-color-020 max-md:w-85 max-md:my-[36.7px] md:max-lg:w-178.5 md:max-lg:my-[2.4125rem]" data-cid="n105" />
              {" "}
              <h2 className="border-t border-solid border-t-border block mt-[62.1px] pt-[33.5px] text-2xl font-bold leading-[1.9375rem] tracking-[-0.36px] max-md:mt-[57.7px] max-md:pt-[1.9375rem] max-md:text-[1.375rem] max-md:leading-[1.8125rem] max-md:tracking-[-0.33px] md:max-lg:mt-[60.7px] md:max-lg:pt-[32.7px] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.875rem] md:max-lg:tracking-[-0.35px]" data-cid="n106" data-component="heading">
                4. 해법 — 롤링 베이스라인
              </h2>
              {" "}
              <p className="h-[1.7rem] block mt-[16.5px] text-muted-foreground max-md:h-[50.5px] max-md:mt-[15.3px] md:max-lg:h-[26.5px] md:max-lg:mt-4" data-cid="n107">
                <strong className="inline text-foreground font-bold" data-cid="n108">
                  정의
                </strong>
                : "최근 W분(10~20분)의 채팅 수준"을 매 순간 다시 계산하는 이동 기준선. "지금의 평상시"를 자동 추적한다.
              </p>
              {" "}
              <p className="h-[3.4rem] block mt-[16.5px] text-muted-foreground max-md:h-[6.3125rem] max-md:mt-[15.3px] md:max-lg:h-[3.3125rem] md:max-lg:mt-4" data-cid="n109">
                <strong className="inline text-foreground font-bold" data-cid="n110">
                  예시 재판정
                </strong>
                : 전반엔 롤링 ≈ 60 → 240 스파이크가 4배로 정확히 검출. 레이드 후엔 롤링이 W분에 걸쳐 60→300으로 추적 → 평상시 300은 1배(조용), 진짜 하이라이트 900만 3배로 검출.
              </p>
              {" "}
              <p className="block mt-[16.5px] text-muted-foreground max-md:mt-[15.3px] md:max-lg:mt-4" data-cid="n111">
                <strong className="inline text-foreground font-bold" data-cid="n112">
                  트레이드오프
                </strong>
              </p>
              {" "}
              <ol className="block mt-[16.5px] pl-[1.4375rem] [list-style-type:decimal] list-outside max-md:mt-[15.3px] max-md:pl-[1.3375rem] md:max-lg:mt-4 md:max-lg:pl-[22.5px]" data-cid="n113">
                {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
              </ol>
              {" "}
              <p className="h-[3.4rem] block mt-[16.5px] text-muted-foreground max-md:h-[126.3px] max-md:mt-[15.3px] md:max-lg:h-[4.975rem] md:max-lg:mt-4" data-cid="n120">
                <strong className="inline text-foreground font-bold" data-cid="n121">
                  핵심 안심 포인트
                </strong>
                {": 규모가 안정적인 방송에서는 롤링 ≈ 전체 평균이라 기존 실측 결과가 그대로 재현된다. 롤링은 전체 평균을 버리는 선택이 아니라, "}
                <strong className="inline text-foreground font-bold" data-cid="n122">
                  잘 되던 케이스는 그대로 두고 깨지는 케이스만 자동으로 고치는 일반화
                </strong>
                {" — 잃는 것이 없는 업그레이드."}
              </p>
              {" "}
              <hr className="w-200 h-px border-t border-solid border-t-border block my-[2.475rem] overflow-hidden text-color-020 max-md:w-85 max-md:my-[36.7px] md:max-lg:w-178.5 md:max-lg:my-[2.4125rem]" data-cid="n123" />
              {" "}
              <h2 className="border-t border-solid border-t-border block mt-[62.1px] pt-[33.5px] text-2xl font-bold leading-[1.9375rem] tracking-[-0.36px] max-md:mt-[57.7px] max-md:pt-[1.9375rem] max-md:text-[1.375rem] max-md:leading-[1.8125rem] max-md:tracking-[-0.33px] md:max-lg:mt-[60.7px] md:max-lg:pt-[32.7px] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.875rem] md:max-lg:tracking-[-0.35px]" data-cid="n124" data-component="heading">
                5. 장단기 이평선 병용 프레임 (멘토 논의용)
              </h2>
              {" "}
              <p className="block mt-[16.5px] text-muted-foreground max-md:mt-[15.3px] md:max-lg:mt-4" data-cid="n125">
                주식 차트 문법으로의 매핑:
              </p>
              {" "}
              <div className="h-[12.6rem] border border-solid border-border block mt-[16.5px] rounded-[10px] overflow-auto bg-surface max-md:h-[21.8375rem] max-md:mt-[15.3px] md:max-lg:h-[12.3125rem] md:max-lg:mt-4" data-cid="n126">
                <table className="w-full h-full table text-[0.9375rem] leading-[1.375rem] [border-collapse:collapse] [border-spacing:2px] max-lg:text-sm max-md:leading-[1.25rem] md:max-lg:leading-[1.3125rem]" data-cid="n127">
                  <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n128">
                    <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n129">
                      <th className="border-b border-solid border-b-border table-cell py-[8.7px] px-[0.8125rem] align-top font-bold text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px] max-md:py-2 max-md:px-3 md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n130">
                        주식
                      </th>
                      <th className="border-b border-solid border-b-border table-cell py-[8.7px] px-[0.8125rem] align-top font-bold text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px] max-md:py-2 max-md:px-3 md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n131">
                        Pokeclip
                      </th>
                      <th className="border-b border-solid border-b-border table-cell py-[8.7px] px-[0.8125rem] align-top font-bold text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px] max-md:py-2 max-md:px-3 md:max-lg:py-[8.5px] md:max-lg:px-[12.7px]" data-cid="n132">
                        역할
                      </th>
                    </tr>
                  </thead>
                  <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n133">
                    {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} styles={Tile2_styles[i]} />)}
                  </tbody>
                </table>
              </div>
              {" "}
              <p className="block mt-[16.5px] text-muted-foreground max-md:mt-[15.3px] md:max-lg:mt-4" data-cid="n150">
                <strong className="inline text-foreground font-bold" data-cid="n151">
                  판정 규칙(안)
                </strong>
                :
              </p>
              {" "}
              <pre className="h-[6.2rem] block mt-3.5 py-[0.975rem] px-[1.15rem] rounded-[10px] overflow-auto text-surface-2 [font-family:monospace] text-sm leading-[1.4375rem] whitespace-pre text-nowrap bg-clr-10 max-md:h-[92.1px] max-md:mt-[0.825rem] max-md:py-[14.5px] max-md:px-[17.1px] max-md:text-[0.8125rem] max-md:leading-[1.3125rem] md:max-lg:h-[96.9px] md:max-lg:py-[0.95rem] md:max-lg:px-[1.125rem] md:max-lg:leading-[1.375rem]" data-cid="n152">
                <code className="inline rounded-[5px] [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace]" data-cid="n153">
                  {"하이라이트 후보 = (순간값 ≥ K × 단기 베이스라인)   … 지금 기준으로 이례적\n              AND (순간값 ≥ 절대 최소치 M)          … 소형·노이즈 컷\n국면 전환 태그 = (단기선 ≥ L × 장기선)              … 별도 카드 가치 검토\n"}
                </code>
              </pre>
              {" "}
              <hr className="w-200 h-px border-t border-solid border-t-border block my-[2.475rem] overflow-hidden text-color-020 max-md:w-85 max-md:my-[36.7px] md:max-lg:w-178.5 md:max-lg:my-[2.4125rem]" data-cid="n154" />
              {" "}
              <h2 className="border-t border-solid border-t-border block mt-[62.1px] pt-[33.5px] text-2xl font-bold leading-[1.9375rem] tracking-[-0.36px] max-md:mt-[57.7px] max-md:pt-[1.9375rem] max-md:text-[1.375rem] max-md:leading-[1.8125rem] max-md:tracking-[-0.33px] md:max-lg:mt-[60.7px] md:max-lg:pt-[32.7px] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.875rem] md:max-lg:tracking-[-0.35px]" data-cid="n155" data-component="heading">
                6. 보조 장치
              </h2>
              {" "}
              <ul className="block mt-[16.5px] pl-[1.4375rem] [list-style-type:disc] list-outside max-md:mt-[15.3px] max-md:pl-[1.3375rem] md:max-lg:mt-4 md:max-lg:pl-[22.5px]" data-cid="n156">
                <li className="h-[3.4rem] list-item mt-1.5 text-muted-foreground max-md:h-[6.3125rem] max-md:mt-[0.3375rem] md:max-lg:h-[3.3125rem] md:max-lg:mt-[0.35rem]" data-cid="n157">
                  <strong className="inline text-foreground font-bold" data-cid="n158">
                    워밍업 구간 (확정 정책)
                  </strong>
                  : 방송 초반 N분은 베이스라인 학습만 하고 카드 발행 보류. 누적 평균이 안정 값에 수렴한 뒤 판정 시작 — 하이라이트 표시는 워밍업 이후부터.
                </li>
                <li className="h-[3.4rem] list-item mt-1.5 text-muted-foreground max-md:h-[126.3px] max-md:mt-[0.3375rem] md:max-lg:h-[4.975rem] md:max-lg:mt-[0.35rem]" data-cid="n159">
                  <strong className="inline text-foreground font-bold" data-cid="n160">
                    고유 채터 수 가설
                  </strong>
                  {": 메시지 수보다 "}
                  <strong className="inline text-foreground font-bold" data-cid="n161">
                    고유 채터 수의 급증
                  </strong>
                  이 더 깨끗한 신호 후보. 1인 도배는 메시지 수만 올리고, 진짜 하이라이트는 눈팅층이 동시에 입을 여는 순간. 주식 비유: 거래량이 아닌 "참여 계좌 수" — 세력 도배와 군중 반응의 구분.
                </li>
                <li className="h-[3.4rem] list-item mt-1.5 text-muted-foreground max-md:h-[6.3125rem] max-md:mt-[0.3375rem] md:max-lg:h-[3.3125rem] md:max-lg:mt-[0.35rem]" data-cid="n162">
                  <strong className="inline text-foreground font-bold" data-cid="n163">
                    멀티윈도우 합의
                  </strong>
                  : 1/3/5/10초 윈도우가 이미 구현되어 있으므로, 복수 윈도우에서 동시 검출된 스파이크만 카드로 승격하는 앙상블로 오탐 저감(추가 구현 비용 최소).
                </li>
                <li className="h-[3.4rem] list-item mt-1.5 text-muted-foreground max-md:h-[6.3125rem] max-md:mt-[0.3375rem] md:max-lg:h-[3.3125rem] md:max-lg:mt-[0.35rem]" data-cid="n164">
                  <strong className="inline text-foreground font-bold" data-cid="n165">
                    시차 보정 전제
                  </strong>
                  : 멀티 플랫폼(치지직·SOOP) 채팅은 플랫폼별 방송 지연이 달라, 오프셋 보정으로 인제스트 타임라인에 정렬한 뒤 합산해야 스파이크가 뭉개지지 않는다.
                </li>
              </ul>
              {" "}
              <hr className="w-200 h-px border-t border-solid border-t-border block my-[2.475rem] overflow-hidden text-color-020 max-md:w-85 max-md:my-[36.7px] md:max-lg:w-178.5 md:max-lg:my-[2.4125rem]" data-cid="n166" />
              {" "}
              <h2 className="border-t border-solid border-t-border block mt-[62.1px] pt-[33.5px] text-2xl font-bold leading-[1.9375rem] tracking-[-0.36px] max-md:mt-[57.7px] max-md:pt-[1.9375rem] max-md:text-[1.375rem] max-md:leading-[1.8125rem] max-md:tracking-[-0.33px] md:max-lg:mt-[60.7px] md:max-lg:pt-[32.7px] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.875rem] md:max-lg:tracking-[-0.35px]" data-cid="n167" data-component="heading">
                7. 미결 질문 (멘토 미팅 안건)
              </h2>
              {" "}
              <ol className="block mt-[16.5px] pl-[1.4375rem] [list-style-type:decimal] list-outside max-md:mt-[15.3px] max-md:pl-[1.3375rem] md:max-lg:mt-4 md:max-lg:pl-[22.5px]" data-cid="n168">
                {ListRow4_data.map((d, i) => <ListRow4 key={i} d={d} cids={ListRow4_cids[i]} />)}
              </ol>
              {" "}
              <hr className="w-200 h-px border-t border-solid border-t-border block my-[2.475rem] overflow-hidden text-color-020 max-md:w-85 max-md:my-[36.7px] md:max-lg:w-178.5 md:max-lg:my-[2.4125rem]" data-cid="n175" />
              {" "}
              <h2 className="border-t border-solid border-t-border block mt-[62.1px] pt-[33.5px] text-2xl font-bold leading-[1.9375rem] tracking-[-0.36px] max-md:mt-[57.7px] max-md:pt-[1.9375rem] max-md:text-[1.375rem] max-md:leading-[1.8125rem] max-md:tracking-[-0.33px] md:max-lg:mt-[60.7px] md:max-lg:pt-[32.7px] md:max-lg:text-[1.4375rem] md:max-lg:leading-[1.875rem] md:max-lg:tracking-[-0.35px]" data-cid="n176" data-component="heading">
                부록 — 용어
              </h2>
              {" "}
              <ul className="block mt-[16.5px] pl-[1.4375rem] [list-style-type:disc] list-outside max-md:mt-[15.3px] max-md:pl-[1.3375rem] md:max-lg:mt-4 md:max-lg:pl-[22.5px]" data-cid="n177">
                {ListRow5_data.map((d, i) => <ListRow5 key={i} d={d} cids={ListRow5_cids[i]} styles={ListRow5_styles[i]} />)}
              </ul>
            </div>
          </div>
        </main>
        <footer className="border-t border-solid border-t-border block bg-surface" data-cid="n188">
          <div className="block max-w-295 mx-auto pt-[2.2rem] pb-12 px-10 text-muted-foreground text-[0.9375rem] leading-[1.5rem] max-md:px-[1.0875rem] md:max-lg:px-[1.7rem]" data-cid="n189">
            <p className="h-[24.3px] block max-md:h-[3.0375rem]" data-cid="n190">
              <strong className="inline font-bold" data-cid="n191">
                PokeClip
              </strong>
              {" — 스트리밍 하이라이트·클립 자동화 서비스의 아키텍처 산출물."}
            </p>
          </div>
        </footer>
      </div>
      {" "}
    </>
  );
}
