import "./ditto.css";
import NavLink from "./components/nav-link";
import TextLink from "./components/text-link";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", ariacurrent: "page", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const TextLink_data = [
    { label: "01", label2: "MSG-178 알림 시스템 — FCM 푸시 파이프라인 (공유 PRD)", label3: "검토됨" },
    { label: "02", label2: "MSG-185 친구 코드·친구 관계 API (요청/수락/거절/삭제)", label3: "검토됨" },
    { label: "03", label2: "MSG-186 친구 목록 · 친구 프로필(도감 요약) 조회", label3: "검토됨" },
    { label: "04", label2: "MSG-187 친구 도감 뷰포트 레이어 (친구 격자 지도 보기)", label3: "검토됨" },
    { label: "05", label2: "MSG-192 영상 신고 접수와 블라인드 처리 (MSG-192, MSG-193 공유 PRD)", label3: "검토됨" },
    { label: "06", label2: "MSG-195 관리자 신고 처리 API (MSG-195)", label3: "검토됨" },
    { label: "07", label2: "MSG-203 프로필 조회·닉네임 수정 API", label3: "검토됨" },
    { label: "08", label2: "MSG-204 업로드 시 공개범위 지정 (PUBLIC/PRIVATE, 기본 공개)", label3: "검토됨" },
    { label: "09", label2: "MSG-205 계정 삭제 API (즉시 물리 삭제 + 연쇄 정리)", label3: "검토됨" },
    { label: "10", label2: "MSG-219 미션·이벤트 — 축제·코스 미션 적재와 스탬프 발급", label3: "검토됨" },
    { label: "11", label2: "MSG-233 핫구역 — 사용자 업로드 신호로 \"지금 뜨는 곳\" 감지", label3: "검토됨" },
    { label: "12", label2: "MSG-235 팝업 스토어 미션 적재 — 팝가 수집본 시드와 주기 갱신", label3: "검토됨" },
    { label: "13", label2: "MSG-239 뱃지 시스템 MVP — 마스터 시딩·획득 엔진", label3: "검토됨" },
    { label: "14", label2: "MSG-258 인기 검색어 순위 (사람들이 많이 찾는 장소 검색어 TOP 10)", label3: "검토됨" },
    { label: "15", label2: "MSG-259 격자 표시명 zone 롤아웃 — 상권 데이터 주입 · 명명 규칙 드리프트 방어", label3: "초안" },
    { label: "16", label2: "MSG-278 미션 스탬프 판정의 촬영 시각 위조 방어", label3: "검토됨" },
    { label: "17", label2: "MSG-285 영상 공개범위 FRIENDS(친구만 보기) 확장", label3: "검토됨" },
    { label: "18", label2: "MSG-286 AI 프리체크 탈락 영상 즉시 실패 처리 (BE 소비)", label3: "검토됨" },
    { label: "19", label2: "MSG-310 카카오 가입 이메일 미수집", label3: "검토됨" },
    { label: "20", label2: "MSG-313 알림 다양화 (영상 준비 완료 · 뱃지 임박 · 주간 요약, 공유 PRD)", label3: "검토됨" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const TextLink_cids: string[][] = [
    ["n23", "n24", "n25", "n26", "n27", "n28"],
    ["n29", "n30", "n31", "n32", "n33", "n34"],
    ["n35", "n36", "n37", "n38", "n39", "n40"],
    ["n41", "n42", "n43", "n44", "n45", "n46"],
    ["n47", "n48", "n49", "n50", "n51", "n52"],
    ["n53", "n54", "n55", "n56", "n57", "n58"],
    ["n59", "n60", "n61", "n62", "n63", "n64"],
    ["n65", "n66", "n67", "n68", "n69", "n70"],
    ["n71", "n72", "n73", "n74", "n75", "n76"],
    ["n77", "n78", "n79", "n80", "n81", "n82"],
    ["n83", "n84", "n85", "n86", "n87", "n88"],
    ["n89", "n90", "n91", "n92", "n93", "n94"],
    ["n95", "n96", "n97", "n98", "n99", "n100"],
    ["n101", "n102", "n103", "n104", "n105", "n106"],
    ["n107", "n108", "n109", "n110", "n111", "n112"],
    ["n113", "n114", "n115", "n116", "n117", "n118"],
    ["n119", "n120", "n121", "n122", "n123", "n124"],
    ["n125", "n126", "n127", "n128", "n129", "n130"],
    ["n131", "n132", "n133", "n134", "n135", "n136"],
    ["n137", "n138", "n139", "n140", "n141", "n142"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const TextLink_styles = [
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[31.5px_27.25px]", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "max-md:h-21 md:max-lg:h-14", className3: "border-dashed border-surface" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[31.5px_27.25px]", className3: "border-solid border-clr-1 text-primary bg-surface-6" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14", className3: "border-solid border-clr-1 text-primary bg-surface-6" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <p className="h-[1.3125rem] flex mb-3.5 items-center gap-2.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.92px] uppercase before:content-[''] before:block before:w-[0.4375rem] before:h-[0.4375rem] before:bg-primary before:rounded-tl-[50%]" data-cid="n19">
              PRODUCT REQUIREMENTS
            </p>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              제품 요구사항
            </h1>
            {" "}
            <p className="w-full max-w-[37.175rem] block mt-3.5 text-muted-foreground" data-cid="n21">
              무엇을 왜 만드는지를 먼저 정하고 들어갑니다. 구현 스펙보다 앞서는 게이트라, 요구사항을 즉석에서 만드는 일을 막습니다.
            </p>
            {" "}
          </div>
          {" "}
          <div className="border-t border-solid border-t-surface block mb-24 max-md:mb-14 md:max-lg:mb-[69.1px]" data-cid="n22">
            {TextLink_data.map((d, i) => <TextLink key={i} d={d} cids={TextLink_cids[i]} styles={TextLink_styles[i]} />)}
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n143">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n144">
          <strong className="inline text-muted-foreground font-bold" data-cid="n145">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
