import "./ditto.css";
import NavLink from "./components/nav-link";
import TextLink from "./components/text-link";
import TextLink2 from "./components/text-link2";
import TextLink3 from "./components/text-link3";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", ariacurrent: "page", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const TextLink_data = [
    { label: "01", label2: "용어 정의 (도메인 사전)" },
    { label: "02", label2: "공통 응답 · 예외 처리 규약" },
    { label: "03", label2: "서비스 아키텍처 (SysA v2 정본)" },
    { label: "04", label2: "100×100m 격자 시스템" },
    { label: "05", label2: "화면 구조 IA · 구현 갭" }
];
const TextLink2_data = [
    { label: "06", label2: "FillMap DB Schema v5 — MVP 개인 도감", label3: "DB · 스키마 · schema · v5 · ERD · users", label4: "2026-07-21" },
    { label: "07", label2: "FillMap 지도·격자 DB 설계 상세 — MVP", label3: "지도 · 격자 · DB 설계 · grids · user_grids · 뷰포트", label4: "2026-07-21" },
    { label: "08", label2: "FillMap DB 자료형·ENUM·GeoJSON 처리 기준", label3: "자료형 · 타입 · ENUM · CHECK · GEOGRAPHY · GEOMETRY", label4: "2026-07-21" },
    { label: "09", label2: "FillMap API 스펙 통합 (전체 한눈에)", label3: "API 스펙 · API 명세 · 통합 · 전체 · 한눈에 · one page", label4: "2026-07-31" },
    { label: "10", label2: "FillMap API 명세 v1 (구현 기준)", label3: "API 명세 · API spec · v1 · 구현 기준 · ApiResponseDto · 응답 래퍼", label4: "2026-07-21" },
    { label: "11", label2: "Grid API (v1 구현 기준)", label3: "Grid · 격자 · API · 도감 · 뷰포트 · viewport", label4: "2026-07-21" },
    { label: "12", label2: "Auth API (v1 구현 기준)", label3: "Auth · 인증 · 로그인 · login · 회원가입 · signup", label4: "2026-07-21" },
    { label: "13", label2: "Video API (v1 구현 기준)", label3: "Video · 영상 · API · 업로드 · upload · presigned URL", label4: "2026-07-21" },
    { label: "14", label2: "FE 격자 계약 — 프론트-백 합의 (격자 사전 생성 정정)", label3: "격자 계약 · grid contract · FE · 프론트 · 사전 생성 · 전역 고정 눈금", label4: "2026-07-30" },
    { label: "15", label2: "zone 표시명 FE 계약 — \"서면 A-14\"를 화면이 만드는 규칙", label3: "zone · 표시명 · display name · 서면 A-14 · FE 계약 · 프론트", label4: "2026-07-31" },
    { label: "16", label2: "PRD — FillMap MVP 화면별 기능·API 명세", label3: "PRD · 화면 · 피그마 · Figma · 와이어프레임 · 7개 화면", label4: "2026-07-25" },
    { label: "17", label2: "개인 도감 화면 — 확정 UX·API 설계 (수집률/탐험률)", label3: "개인 도감 · 도감 · collection · 도감 화면 · 수집률 · 탐험률", label4: "2026-07-30" }
];
const TextLink3_data = [
    { label: "18", label2: "핫구역 설계 (정의 · 산식 · 저장 구조)" },
    { label: "19", label2: "zone 표시명 체계 설계" },
    { label: "20", label2: "zone 롤아웃 (상권 데이터 검수 · 시딩)" },
    { label: "21", label2: "코딩 컨벤션" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const TextLink_cids: string[][] = [
    ["n23", "n24", "n25", "n26", "n27"],
    ["n28", "n29", "n30", "n31", "n32"],
    ["n33", "n34", "n35", "n36", "n37"],
    ["n38", "n39", "n40", "n41", "n42"],
    ["n43", "n44", "n45", "n46", "n47"]
];
const TextLink2_cids: string[][] = [
    ["n48", "n49", "n50", "n51", "n52", "n53", "n54", "n55"],
    ["n56", "n57", "n58", "n59", "n60", "n61", "n62", "n63"],
    ["n64", "n65", "n66", "n67", "n68", "n69", "n70", "n71"],
    ["n72", "n73", "n74", "n75", "n76", "n77", "n78", "n79"],
    ["n80", "n81", "n82", "n83", "n84", "n85", "n86", "n87"],
    ["n88", "n89", "n90", "n91", "n92", "n93", "n94", "n95"],
    ["n96", "n97", "n98", "n99", "n100", "n101", "n102", "n103"],
    ["n104", "n105", "n106", "n107", "n108", "n109", "n110", "n111"],
    ["n112", "n113", "n114", "n115", "n116", "n117", "n118", "n119"],
    ["n120", "n121", "n122", "n123", "n124", "n125", "n126", "n127"],
    ["n128", "n129", "n130", "n131", "n132", "n133", "n134", "n135"],
    ["n136", "n137", "n138", "n139", "n140", "n141", "n142", "n143"]
];
const TextLink3_cids: string[][] = [
    ["n144", "n145", "n146", "n147", "n148"],
    ["n149", "n150", "n151", "n152", "n153"],
    ["n154", "n155", "n156", "n157", "n158"],
    ["n159", "n160", "n161", "n162", "n163"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const TextLink2_styles = [
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[56px_27.25px]", className2: "h-7 max-md:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[56px_27.25px]", className2: "h-7 max-md:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[56px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-lg:h-14" },
    { className: "grid-rows-[56px] max-md:grid-rows-[84px_27.25px]", className2: "h-14 max-md:h-21" },
    { className: "grid-rows-[56px] max-md:grid-rows-[84px_27.25px]", className2: "h-14 max-md:h-21" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" }
];
const TextLink3_styles = [
    { className: "h-7" },
    { className: "h-7" },
    { className: "h-7" },
    {  }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <p className="h-[1.3125rem] flex mb-3.5 items-center gap-2.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.92px] uppercase before:content-[''] before:block before:w-[0.4375rem] before:h-[0.4375rem] before:bg-primary before:rounded-tl-[50%]" data-cid="n19">
              {"DESIGN & SPEC"}
            </p>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              설계와 명세
            </h1>
            {" "}
            <p className="w-full max-w-[37.175rem] block mt-3.5 text-muted-foreground" data-cid="n21">
              DB 스키마, 격자 시스템, API 계약. 코드가 정본인 항목은 저장소 문서를, 합의 이력이 정본인 항목은 팀 위키를 실었습니다.
            </p>
            {" "}
          </div>
          {" "}
          <div className="border-t border-solid border-t-surface block mb-24 max-md:mb-14 md:max-lg:mb-[69.1px]" data-cid="n22">
            {TextLink_data.map((d, i) => <TextLink key={i} d={d} cids={TextLink_cids[i]} />)}
            {TextLink2_data.map((d, i) => <TextLink2 key={i} d={d} cids={TextLink2_cids[i]} styles={TextLink2_styles[i]} />)}
            {TextLink3_data.map((d, i) => <TextLink3 key={i} d={d} cids={TextLink3_cids[i]} styles={TextLink3_styles[i]} />)}
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n164">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n165">
          <strong className="inline text-muted-foreground font-bold" data-cid="n166">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
