import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import ListRow3 from "./components/list-row3";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", ariacurrent: "page", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-08-03" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "Redis 센티널과 클러스터는 무엇이 다르고 언제 무엇을 쓰나?" },
    { text: "페일오버 실습을 어떤 순서로 하고 무엇을 실측해야 하나?" },
    { text: "FillMap의 Redis가 죽으면 각 기능은 어떻게 동작하나?" },
    { text: "대규모 알림 서비스는 어떤 요소로 구성되나? (배치·스로틀링·중복 방지·outbox)" },
    { text: "LGTM 스택과 ELK의 본질적 차이는? Thanos와 Mimir는 어떻게 다른가?" },
    { text: "FillMap에서 부하 테스트·slow query 추적 대상은 어디인가?" }
];
const Tile_data = [
    { text: "핫스코어 집계 (MSG-183)", text2: "전용 스레드에서 실패 삼킴 + warn. 업로드는 무조건 성공", text3: "“부가 신호는 유실 허용, 핵심 경로 비전파” — 페일오버 다운타임에도 업로드 API 무영향" },
    { text: "핫구역 조회 (MSG-184)", text2: "예외 전파 → 500. SLO 5xx<1% 관리 대상", text3: "조회는 실패가 보여야 하는 경로 — 다운타임 동안 500률로 관측" },
    { text: "refresh 토큰 (MSG-135)", text2: "Redis 죽으면 재발급 실패 → 재로그인 유도", text3: "세션 계층이 Redis 종속 — Sentinel이 필요한 실제 이유. “액세스 토큰은 stateless라 만료 전까지 이용은 지속”까지 붙이면 완성" }
];
const Tile2_data = [
    { text: "G", text2: "rafana", text3: "시각화", text4: "벤더 중립 단일 화면 — Prometheus·Loki·Tempo·ES 전부 데이터소스" },
    { text: "T", text2: "empo", text3: "트레이스", text4: "traceID 기반 저장·조회. 로그↔트레이스↔메트릭 점프(correlation)가 셀링 포인트" },
    { text: "M", text2: "imir", text3: "메트릭 장기 저장", text4: "Prometheus의 수평 확장·장기 보관판 (Cortex 계보)" }
];
const ListRow3_data = [
    { href: "https://medium.com/@krunalpatel1530/elk-vs-grafana-stack-a-practical-comparison-for-observability-5b6b90fc980a", label: "ELK vs. Grafana Stack: A Practical Comparison for Observability" },
    { href: "https://medium.com/@elammarisoufiane/one-stack-to-rule-them-all-arbitrating-your-observability-architecture-elk-vs-lgtm-one-choice-per-1af7410152fc", label: "Arbitrating Your Observability Architecture (ELK vs LGTM)" },
    { href: "https://oneuptime.com/blog/post/2026-02-06-lgtm-stack-opentelemetry/view", label: "How to Build a Complete LGTM Stack with OpenTelemetry" },
    { href: "https://oneuptime.com/blog/post/2026-03-31-redis-sentinel-docker-compose/view", label: "How to Set Up Redis Sentinel with Docker Compose" },
    { href: "https://intelligentbee.com/blog/emulating-redis-failover-docker/", label: "Emulate a Redis Failover with Docker" },
    { href: "https://github.com/AliyunContainerService/redis-cluster", label: "Redis cluster with Docker Compose" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n36"],
    ["n37"],
    ["n38"],
    ["n39"],
    ["n40"],
    ["n41"]
];
const Tile_cids: string[][] = [
    ["n105", "n106", "n107", "n108"],
    ["n109", "n110", "n111", "n112"],
    ["n113", "n114", "n115", "n116"]
];
const Tile2_cids: string[][] = [
    ["n181", "n182", "n183", "n184", "n185"],
    ["n186", "n187", "n188", "n189", "n190"],
    ["n191", "n192", "n193", "n194", "n195"]
];
const ListRow3_cids: string[][] = [
    ["n234", "n235"],
    ["n236", "n237"],
    ["n238", "n239"],
    ["n240", "n241"],
    ["n242", "n243"],
    ["n244", "n245"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];
const ListRow3_styles = [
    { className: "max-md:h-14" },
    { className: "max-md:h-14" },
    { className: "max-md:h-14" },
    { className: "max-md:h-14" },
    {  },
    {  }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/research">
              ← 연구 노트
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              백엔드 학습 로드맵 — Redis HA · 대규모 알림 · 관측성 (멘토링 08-01 후속)
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="h-[11.1rem] block mt-[14.5px] text-muted-foreground max-md:h-101.5" data-cid="n28">
                {"2026-08-01 멘토 멘토링 피드백을 트랙 3개로 분해한 개인 공부 계획. 원칙은 하나 — "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n29">
                  직접 실습 없이 이력서에 쓰지 않는다.
                </strong>
                {" 이력서 불릿 공식: 공부 → 실습 → 장애 주입 → 검증 → 우리 서비스 관점 서술. 트랙 1 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n30">
                  Redis HA
                </strong>
                {"(센티널 vs 클러스터, 마스터 kill → 페일오버 다운타임 실측 → WAS 관점 실험)가 최우선. FillMap의 Redis 사용처 3곳(핫스코어 MSG-183 / 핫구역 조회 MSG-184 / refresh 토큰 MSG-135)이 장애 시 대처가 서로 달라 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n31">
                  비즈니스 관점 서사가 이미 준비돼 있다
                </strong>
                {". 트랙 2 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n32">
                  대규모 알림
                </strong>
                {"(FillMap 미보유 도메인 — outbox·배치·스로틀링·멱등), 트랙 3 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n33">
                  관측성
                </strong>
                (부하테스트 사이클 + Prometheus/Grafana → slow query 추적 → LGTM·Thanos). 우선순위: 1 → 3-1 → 3-2 → 2.
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n34" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n35">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n42" data-component="heading" id="요약">
              요약
            </h2>
            {" "}
            <p className="h-14 block my-4 text-muted-foreground max-md:h-28" data-cid="n43">
              {"멘토 판정을 그대로 옮기면: "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n44">
                버림
              </strong>
              {" = 기술 스택 나열 불릿·의미 불명 항목. "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n45">
                살림 + 깊이
              </strong>
              {" = Redis. "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n46">
                신규 추천
              </strong>
              {" = 대규모 알림 서비스, 관측성. 이 판정을 트랙 3개 + 우선순위로 정리한 문서다."}
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n47" data-component="heading" id="발견">
              발견
            </h2>
            {" "}
            <h3 className="block mt-[2.025rem] mb-[0.5625rem] text-lg font-bold leading-[2rem] tracking-[-0.36px]" data-cid="n48" data-component="heading" id="트랙-1-redis-고가용성--센티널-vs-클러스터">
              트랙 1. Redis 고가용성 — 센티널 vs 클러스터
            </h3>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground" data-cid="n49">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n50">
                선행 개념 (실습 전에 답할 수 있어야 하는 것)
              </strong>
            </p>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n51">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n52">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n53">
                  복제
                </strong>
                {": 마스터→레플리카 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n54">
                  비동기
                </strong>
                {" 복제. 왜 비동기이고, 페일오버 때 무엇을 잃는가(마스터 승인 후 미복제분 유실 — 알고 쓰는 트레이드오프)."}
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-42" data-cid="n55">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n56">
                  Sentinel
                </strong>
                {": 별도 프로세스가 마스터 감시. SDOWN(주관적) vs ODOWN(객관적), "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n57">
                  quorum
                </strong>
                {"(센티널이 홀수 3대 이상인 이유), 리더 선출 → 레플리카 승격 → 클라이언트 통지. "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n58">
                  샤딩 없음
                </strong>
                {" — 데이터가 한 마스터에 다 들어갈 때의 HA."}
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-49" data-cid="n59">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n60">
                  Cluster
                </strong>
                {": "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n61">
                  16384 해시 슬롯
                </strong>
                {" 샤딩 + 마스터별 레플리카로 HA까지. gossip으로 노드끼리 감시(별도 센티널 없음), "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n62">
                  MOVED
                </code>
                /
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n63">
                  ASK
                </code>
                {" 리다이렉션, "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n64">
                  멀티키·Lua는 같은 슬롯이어야
                </strong>
                {" 함(hash tag "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n65">
                  {"{}"}
                </code>
                ). 회사 기본 스택인 이유는 스케일아웃 + HA를 한 구조로 해결하기 때문.
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n66">
                선택 기준 한 줄: 한 인스턴스에 들어가면 Sentinel, 샤딩이 필요하면 Cluster.
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-42" data-cid="n67">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n68">
                  클라이언트(Lettuce) 관점
                </strong>
                {": 페일오버 순간 연결 끊김 → 예외 → 토폴로지 갱신 → 새 마스터 재연결. Spring Data Redis의 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n69">
                  RedisStaticMasterReplicaConfiguration
                </code>
                {" vs "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n70">
                  RedisSentinelConfiguration
                </code>
                {" vs "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n71">
                  RedisClusterConfiguration
                </code>
                {" 차이."}
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n72">
                {"참고: 라이선스 분쟁으로 갈라진 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n73">
                  Valkey
                </strong>
                (오픈소스 포크) 존재 정도는 알아두기.
              </li>
            </ul>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground" data-cid="n74">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n75">
                실습 로드맵 (멘토 지정 흐름)
              </strong>
            </p>
            {" "}
            <ol className="block my-4 pl-[1.35rem] [list-style-type:decimal] list-outside" data-cid="n76">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n77">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n78">
                  Sentinel 구성
                </strong>
                {" — docker-compose로 마스터 1 + 레플리카 2 + 센티널 3, quorum 2. "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n79">
                  redis-cli -p 26379 sentinel master
                </code>
                로 상태 확인.
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-35 md:max-lg:h-21" data-cid="n80">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n81">
                  마스터 죽이기
                </strong>
                {" — "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n82">
                  docker stop
                </code>
                {" → 센티널 로그 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n83">
                  +sdown
                </code>
                {" → "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n84">
                  +odown
                </code>
                {" → "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n85">
                  +switch-master
                </code>
                {" 확인. "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n86">
                  down-after-milliseconds
                </code>
                ·
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n87">
                  failover-timeout
                </code>
                {"을 바꿔가며 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n88">
                  다운타임 실측
                </strong>
                (이 숫자가 이력서 불릿 재료).
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n89">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n90">
                  Cluster 구성
                </strong>
                {" — 마스터 3 + 레플리카 3, "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n91">
                  redis-cli --cluster create
                </code>
                {". "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n92">
                  CLUSTER KEYSLOT
                </code>
                으로 슬롯 분배 확인, 마스터 kill → 승격 관측.
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-35" data-cid="n93">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n94">
                  WAS 관점 실험(핵심)
                </strong>
                {" — Spring Boot(Lettuce)를 Sentinel에 붙이고 페일오버 도중 요청을 계속 쏘며(k6) "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n95">
                  어떤 예외가 몇 초간 나는지
                </strong>
                {" 실측 → 재시도/예외 삼킴/폴백을 케이스별로 코드화."}
              </li>
            </ol>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground max-md:h-14" data-cid="n96">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n97">
                FillMap 접점 — 비즈니스 관점 서술 재료 (이미 있는 것)
              </strong>
            </p>
            {" "}
            <table className="h-[270.5px] block min-w-full max-w-full my-[1.05rem] overflow-auto text-sm leading-[1.5625rem] [border-collapse:collapse] [border-spacing:2px] max-md:h-[763.1px]" data-cid="n98">
              <thead className="h-[2.4625rem] table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n99">
                <tr className="h-[2.4625rem] table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n100">
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n101">
                    사용처
                  </th>
                  <th className="h-[2.4625rem] border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n102">
                    장애 시 동작 (현재 설계)
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n103">
                    서술 포인트
                  </th>
                </tr>
              </thead>
              <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n104">
                {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} />)}
              </tbody>
            </table>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-49" data-cid="n117">
              {"실습 4단계를 FillMap dev 구성(EC2 docker-compose)에 축소 적용해 “페일오버 N초 동안 로그인 연장만 실패하고 업로드·조회는 이렇게 버틴다”를 숫자로 말할 수 있으면 멘토가 말한 “비즈니스 관점 포함 서술”이 완성된다. (핫구역 Redis ZSET 집계 맥락은 "}
              <a className="inline text-primary underline cursor-pointer" data-cid="n118" data-component="link" href="/adr/adr-viewport-polling-slo">
                ADR viewport polling SLO
              </a>
              {" §6)"}
            </p>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground" data-cid="n119">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n120">
                면접 예상 질문 (막히면 안 되는 것)
              </strong>
            </p>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n121">
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n122">
                센티널 quorum이 2인데 센티널이 2대면? (스플릿 브레인·과반 선출 불가)
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n123">
                {"페일오버 중 쓰기 유실이 왜 생기나? "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n124">
                  min-replicas-to-write
                </code>
                는 뭘 완화하나?
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n125">
                {"Cluster에서 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n126">
                  MGET a b c
                </code>
                가 실패하는 이유와 hash tag 해법
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n127">
                Lettuce는 페일오버를 어떻게 알아채나? (Sentinel pub/sub 구독 vs Cluster 토폴로지 갱신)
              </li>
            </ul>
            {" "}
            <h3 className="block mt-[2.025rem] mb-[0.5625rem] text-lg font-bold leading-[2rem] tracking-[-0.36px]" data-cid="n128" data-component="heading" id="트랙-2-대규모-알림-서비스">
              트랙 2. 대규모 알림 서비스
            </h3>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-42" data-cid="n129">
              {"FillMap에 알림 도메인이 "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n130">
                아직 없다
              </strong>
              {" — 이벤트 소스(뱃지 획득·미션 스탬프·스트릭 임박·핫구역 진입)는 이미 쌓여 있어 붙이기 좋은 신규 기능. "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n131">
                “핫구역 뜸 → 근처 사용자 대량 발송”
              </strong>
              {" 시나리오가 트래픽 쏠림 제어까지 한 세트로 맞는다."}
            </p>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n132">
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n133">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n134">
                  실시간 개별 vs 대량 발송
                </strong>
                : 개별은 이벤트 훅에서 바로, 대량은 저장 후 배치.
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-42" data-cid="n135">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n136">
                  예약 발송 배치
                </strong>
                {": PENDING→SENT 상태 테이블 + 주기 배치(회사 실무 방식). Spring Batch(Job·Step·chunk) 또는 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n137">
                  @Scheduled
                </code>
                {" + 상태 테이블부터. 다중 인스턴스 중복 실행 방지(ShedLock·DB 락 — "}
                <a className="inline text-primary underline cursor-pointer" data-cid="n138" data-component="link" href="/research/EB-B6-84-EC-82-B0-EB-9D-BD-EC-A0-81-EC-9A-A9-EC-A3-BC-EC-9D-98-EC-A0-90">
                  분산락 적용 주의점
                </a>
                과 연결).
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n139">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n140">
                  스로틀링/분산 발송
                </strong>
                {": 나눠 보내는 이유는 발송 부하가 아니라 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n141">
                  유입 트래픽 평탄화
                </strong>
                . 배치 N등분 시차 발송 또는 큐 + 소비 속도 제한.
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n142">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n143">
                  중복 방지
                </strong>
                {": 멱등 키(사용자×알림종류×기준시각), DB 유니크 제약이 최후 방어선 (FillMap "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n144">
                  insertIgnoreConflict
                </code>
                {" 패턴 재사용 가능)."}
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-35" data-cid="n145">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n146">
                  outbox 패턴
                </strong>
                : 비즈니스 트랜잭션과 발송 요청 저장을 한 트랜잭션으로, 발송은 별도 폴러가 — “커밋됐는데 유실”/“롤백됐는데 발송” 양쪽 차단. FillMap afterCommit 훅과 비교 설명하면 좋은 어필.
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n147">
                {"채널(FCM·웹푸시)보다 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n148">
                  파이프라인 설계
                </strong>
                가 어필 포인트. 이력 보존·파티셔닝, 재시도 정책(지수 백오프·DLQ)까지.
              </li>
            </ul>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-42" data-cid="n149">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n150">
                실습 아이디어(FillMap 티켓화 후보)
              </strong>
              : ① notifications 테이블 + 이벤트 훅 PENDING 적재(outbox) ② 배치 발송기(폴링·배치 크기 제한·동시 실행 락) ③ 핫구역 진입 알림 N분할 시차 발송 + k6로 몰림 vs 분산 유입 비교 ④ 유니크 제약 + 재시도 테스트.
            </p>
            {" "}
            <h3 className="block mt-[2.025rem] mb-[0.5625rem] text-lg font-bold leading-[2rem] tracking-[-0.36px]" data-cid="n151" data-component="heading" id="트랙-3-모니터링--관측성">
              트랙 3. 모니터링 · 관측성
            </h3>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground max-md:h-14" data-cid="n152">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n153">
                3-1. 기본 사이클이 뼈대
              </strong>
              {" — 부하 테스트 → 병목 확인 → 개선 → 재테스트. 도구는 수단."}
            </p>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n154">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n155">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n156">
                  부하 테스트
                </strong>
                {": k6 기본(시나리오·VU·p95/p99). FillMap 대상 후보 — "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n157">
                  GET /api/hotzones
                </code>
                {"(캐시 만료 순간 동시 재계산), "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n158">
                  GET /api/grids
                </code>
                {" viewport, 업로드 확정."}
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n159">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n160">
                  메트릭 파이프라인
                </strong>
                : Spring Actuator + Micrometer → Prometheus(pull·scrape) → Grafana. HTTP p95·에러율·커넥션 풀·JVM 힙 기본 패널.
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-49 md:max-lg:h-28" data-cid="n161">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n162">
                  slow query 추적
                </strong>
                {": 멘토 지적 “Grafana가 시각화만 하면 한계”. PostgreSQL "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n163">
                  pg_stat_statements
                </code>
                (누적 통계)·
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n164">
                  auto_explain
                </code>
                (느린 쿼리 실행계획 자동 로깅). FillMap 대상: viewport keyset 쿼리·region_stats recompute·미션 판정 native 쿼리. (PostgreSQL 실무 가이드 모음)
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n165">
                메트릭 vs 로그 vs 트레이스 — 세 신호의 역할 구분을 자기 말로.
              </li>
            </ul>
            {" "}
            <p className="block my-4 text-muted-foreground" data-cid="n166">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n167">
                3-2. LGTM 스택
              </strong>
            </p>
            {" "}
            <table className="h-[265.1px] block min-w-full max-w-full my-[1.05rem] overflow-auto text-sm leading-[1.5625rem] [border-collapse:collapse] [border-spacing:2px] max-md:h-[399.5px] md:max-lg:h-[287.5px]" data-cid="n168">
              <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n169">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n170">
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n171">
                    구성
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n172">
                    역할
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n173">
                    핵심 한 줄
                  </th>
                </tr>
              </thead>
              <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n174">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n175">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n176">
                    <strong className="inline [font-weight:650] [border-collapse:collapse] [border-spacing:2px]" data-cid="n177">
                      L
                    </strong>
                    oki
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n178">
                    로그
                  </td>
                  <td className="h-[3.8625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[6.6625rem]" data-cid="n179">
                    <strong className="inline [font-weight:650] [border-collapse:collapse] [border-spacing:2px]" data-cid="n180">
                      라벨만 인덱싱
                    </strong>
                    , 본문은 압축 청크로 오브젝트 스토리지에 — ELK 대비 저장 비용이 구조적으로 싼 이유
                  </td>
                </tr>
                {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} />)}
              </tbody>
            </table>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n196">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n197">
                {"수집 에이전트는 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n198">
                  Grafana Alloy
                </strong>
                (구 Agent, OTel 호환)가 현재 표준 — OpenTelemetry 계측 → Alloy가 밀어넣는 구성이 2026 기본형.
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-42" data-cid="n199">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n200">
                  LGTM vs ELK
                </strong>
                : 인덱싱 전략이 본질 — ES는 전 필드 역인덱스(검색 강력·비용 큼), Loki는 라벨만(grep식·비용 작음). 전문 검색이면 ELK, 대량 로그 경제성이면 Loki. 반론: LGTM은 상태ful 시스템 3~4개를 굴리는 운영 세금이 있다.
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n201">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n202">
                  Thanos
                </strong>
                {"(멘토 키워드 “타노스 아키텍처”): Prometheus 단일 인스턴스의 한계 3개 — ① 로컬 디스크라 장기 보관 불가 ② HA 없음(죽으면 구멍) ③ 여러 Prometheus 글로벌 뷰 없음 — 을 기존 Prometheus를 안 건드리고 옆에서 푼다. "}
                <ul className="block pl-[1.35rem] [list-style-type:circle] list-outside" data-cid="n203">
                  <li className="h-14 list-item my-[0.3rem] max-md:h-28" data-cid="n204">
                    {"구성: "}
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n205">
                      Sidecar
                    </strong>
                    {"(블록 S3 업로드 + 실시간 프록시) · "}
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n206">
                      Store Gateway
                    </strong>
                    {"(S3 과거 조회) · "}
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n207">
                      Querier
                    </strong>
                    {"(팬아웃 합산 = 글로벌 뷰) · "}
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n208">
                      Compactor
                    </strong>
                    (다운샘플링·압축).
                  </li>
                  <li className="h-14 list-item my-[0.3rem] max-md:h-21" data-cid="n209">
                    {"HA 방식: Prometheus 2대가 "}
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n210">
                      중복 수집
                    </strong>
                    {"하고 Querier가 조회 시 "}
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n211">
                      dedup
                    </strong>
                    {" — 한 대 죽어도 구멍이 안 난다."}
                  </li>
                  <li className="h-21 list-item my-[0.3rem] max-md:h-42" data-cid="n212">
                    <strong className="inline text-foreground [font-weight:650]" data-cid="n213">
                      vs Mimir
                    </strong>
                    : 같은 문제의식, 반대 접근 — Thanos는 기존 Prometheus 옆에 붙는 연합형, Mimir는 remote write 중앙 집중형(Cortex 계보). “이미 Prometheus가 여기저기면 Thanos, 처음부터 중앙화면 Mimir”.
                  </li>
                  <li className="list-item my-[0.3rem]" data-cid="n214">
                    실습은 로컬 docker-compose로 Prometheus 2대 + Sidecar + Querier → 한 대 kill 후 dedup으로 그래프에 구멍이 안 나는 것 확인 정도면 충분.
                  </li>
                </ul>
                {" "}
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n215">
                트레이싱 실습: OTel Java agent를 붙여 업로드 확정 훅 체인(badge→streak→mission→hotzone)이 트레이스로 어떻게 보이는지 — 이미 있는 코드가 좋은 데모.
              </li>
            </ul>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground" data-cid="n216">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n217">
                3-3. 실습 순서 (t3.small 2GB 제약 주의)
              </strong>
            </p>
            {" "}
            <ol className="block my-4 pl-[1.35rem] [list-style-type:decimal] list-outside" data-cid="n218">
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n219">
                로컬 docker-compose: Prometheus + Grafana + FillMap → 기본 대시보드
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n220">
                k6로 핫구역 조회 부하 → 병목 하나 개선 → 전후 p95 비교 (불릿 1개 완성)
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n221">
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n222">
                  pg_stat_statements
                </code>
                로 slow query 상위 추출 → 인덱스/쿼리 개선 실측
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n223">
                Loki + Alloy 추가 → 로그·메트릭 한 화면
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n224">
                Tempo + OTel agent → 훅 체인 트레이스 (dev EC2는 메모리 부족 — 로컬/별도 인스턴스)
              </li>
            </ol>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n225" data-component="heading" id="시사점">
              시사점
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n226">
              <li className="h-28 list-item my-[0.3rem] text-muted-foreground max-md:h-70 md:max-lg:h-35" data-cid="n227">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n228">
                  우선순위
                </strong>
                : ① 트랙 1(Redis) — 멘토가 “살릴 것”으로 지목한 유일한 기존 자산, 실습 4단계가 1~2주고 FillMap 접점 서사가 준비돼 있어 투자 대비 가장 빠름. ② 트랙 3-1 — Redis WAS 실험과 도구(k6)가 겹쳐 이어서 하면 싸다. ③ 트랙 3-2 LGTM/Thanos — 심화, “면접관이 모르는 최신 개념” 카드. ④ 트랙 2(알림) — 유일하게 신규 개발이 필요, PRD부터 태워 FillMap 티켓으로.
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n229">
                {"트랙 2는 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n230">
                  FillMap 신규 기능 제안
                </strong>
                이기도 하다 — 진행하려면 팀 합의·티켓화가 선행되어야 한다(현재는 개인 학습 계획 단계).
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n231">
                트랙 3의 dev EC2(t3.small 2GB) 제약 때문에 관측성 스택 실습은 로컬 또는 별도 인스턴스가 전제.
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n232" data-component="heading" id="원본-링크">
              원본 링크
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n233">
              {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
            </ul>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n246">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n247">
          <strong className="inline text-muted-foreground font-bold" data-cid="n248">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
