import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", ariacurrent: "page", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-07-21" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "AI 블러/하이라이트 처리는 어디서 실행되나?" },
    { text: "Lambda를 기각한 세 가지 이유는?" },
    { text: "왜 노트북 벤치마크를 믿으면 안 됐나?" },
    { text: "1080p 다운스케일이 왜 필수 전제인가?" },
    { text: "비용 손익분기와 재검토 조건은?" },
    { text: "동시 처리 상한과 그 한계는?" },
    { text: "아직 안 풀린 AI 품질 문제는?" }
];
const ListRow2_data2 = [
    { text: "워크로드가 분 단위(4K는 Lambda 한도의 65%, S3 I/O·이미지 pull 더하면 11~13분) — 서버형." },
    { text: "vCPU 확장 무의미(+1~10%) → Lambda의 “메모리로 시간 산다” 카드 무효." },
    { text: "프레임당 추론 시간 해상도 무관 → 다운스케일로 프레임 수만 줄이면 9.7분→3~4분, 정확도 손실 없음." },
    { text: "비용: 1,000건/월 Lambda $4.5 vs FastAPI $29.8, 10,000건이면 역전. 팀이 이미 EC2+Docker 운영 중이라 신규 파이프라인(ECR) 비용 없음. GPU $384는 과함." }
];
const ListRow2_data3 = [
    { text: "받아들임: 유휴 비용 월 ~$30, 1 vCPU 시간당 ~17건 상한(동시 부하 미측정)." },
    { text: "문서 수정: architecture.md(FastAPI 확정·다운스케일 추가), ToBe drawio(Lambda 제거), YOLO/CLIP 표기 갱신(CLIP·pHash Phase 2)." },
    { text: "재검토: 간헐적 스파이크 트래픽 → Lambda / 처리 10분 초과 → GPU." },
    { text: "⚠️ MVP 블로커 2건(범위 밖): 정면 얼굴도 다수 미탐지(conf 0.25에서도, MSG-140 미충족) · 단일 씬 영상 하이라이트 0개(MSG-141 미충족)." }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n33"],
    ["n34"],
    ["n35"],
    ["n36"],
    ["n37"],
    ["n38"],
    ["n39"]
];
const ListRow2_cids2: string[][] = [
    ["n50"],
    ["n51"],
    ["n52"],
    ["n53"]
];
const ListRow2_cids3: string[][] = [
    ["n56"],
    ["n57"],
    ["n58"],
    ["n59"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/adr">
              ← 설계 결정 기록
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              ADR — AI 처리 실행 환경, 상시 FastAPI 서버 (MSG-143)
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="h-[126.9px] block mt-[14.5px] text-muted-foreground max-md:h-[304.5px]" data-cid="n28">
                {"AI Highlight-Blur는 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n29">
                  상시 Python(FastAPI) 서버
                </strong>
                로 확정 (Lambda·GPU 기각). 필수 전제: 입력을 1080p 30fps로 다운스케일. 근거는 Graviton3(c7g.large) 실측: 1080p 30초 3
                <del className="inline text-muted line-through" data-cid="n30">
                  4분, 4K 9.7분(Lambda 15분의 65%), vCPU 늘려도 안 빨라짐(추론 비병렬), 프레임당 227
                </del>
                230ms로 해상도 무관(imgsz=640). 노트북(M5) 수치는 4배 낙관적이라 무효. 비용 손익분기 월 ~6,650건, 그 이상이면 상시 서버가 오히려 쌈. 처리 요청은 비동기(BLURRING 상태). 미해결: 얼굴 미탐지 심각·단일 씬 하이라이트 0개(MVP 블로커).
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n31" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n32">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n40" data-component="heading" id="맥락">
              맥락
            </h2>
            {" "}
            <p className="block my-4 text-muted-foreground" data-cid="n41">
              ToBe 다이어그램에 Lambda(옵션A) vs FastAPI(옵션B)가 “택1 보류”로 남아 있었음. MSG-142에서 실측 후 결정.
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n42" data-component="heading" id="선택지">
              선택지
            </h2>
            {" "}
            <p className="block my-4 text-muted-foreground" data-cid="n43">
              ① Lambda ② 상시 FastAPI ③ GPU 인스턴스.
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n44" data-component="heading" id="결정">
              결정
            </h2>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-49 md:max-lg:h-28" data-cid="n45">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n46">
                ② 상시 FastAPI
              </strong>
              {" — dev EC2에 Docker 컨테이너로, c7g.medium 이상, ASM-MSG/AI 레포(AGPL-3.0, 모델은 MSG-144: YOLOv11n 얼굴+번호판 + PySceneDetect). 처리 3~4분이므로 "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n47">
                비동기
              </strong>
              (Spring이 넘기고 processing_status=BLURRING). 파이프라인 첫 단계에 1080p 30fps 다운스케일(선택 아님).
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n48" data-component="heading" id="근거-실측">
              근거 (실측)
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n49">
              {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids2[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n54" data-component="heading" id="영향">
              영향
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n55">
              {ListRow2_data3.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids3[i]} />)}
            </ul>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n60">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n61">
          <strong className="inline text-muted-foreground font-bold" data-cid="n62">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
