import "./ditto.css";
import NavLink from "./components/nav-link";
import TextLink from "./components/text-link";
import TextLink2 from "./components/text-link2";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", ariacurrent: "page", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const TextLink_data = [
    { href: "/embeds/hotzone-load-test.html", label: "01", label2: "핫구역 설계 · 구현 · 부하 실측", label3: "Redis Sorted Set 집계 설계부터 10만 표본 부하 실측까지." },
    { href: "/embeds/notification-system.html", label: "02", label2: "알림 시스템 전체 해설", label3: "FCM 발송 파이프라인, 재시도, 카테고리 5종 옵트아웃." },
    { href: "/embeds/redis-hotzone.html", label: "03", label2: "핫구역 Redis 구현 해설", label3: "6시간 버킷, Lua 스크립트, 큐 흡수 구조를 그림으로." },
    { href: "/embeds/grid-occupation-trouble.html", label: "04", label2: "트러블슈팅: 파일 없이 격자 점령", label3: "업로드가 실패했는데 격자가 점령되던 문제의 추적 기록." }
];
const TextLink2_data = [
    { href: "/research/zone-ED-91-9C-EC-8B-9C-EB-AA-85-EB-8D-B0-EC-9D-B4-ED-84-B0-ED-8C-8C-EC-9D-B4-ED-94-84-EB-9D-BC-EC-9D-B8-ED-95-B4-EC-84-A4", label: "01", label2: "zone 표시명 데이터 파이프라인 해설 — 공공데이터에서 \"서면 A-14\"까지", label3: "zone · 구역 · 표시명 · display name · 서면 A-14 · 홍대", label4: "2026-07-31" },
    { href: "/research/zone-EC-83-81-EA-B6-8C-EA-B3-B5-EA-B3-B5-EB-8D-B0-EC-9D-B4-ED-84-B0-EA-B7-BC-EA-B1-B0", label: "02", label2: "zone 상권 데이터 — 왜 공공데이터를 쓰나 (출처·이유·한계)", label3: "zone · 상권 · 공공데이터 · public data · 소상공인시장진흥공단 · 소진공", label4: "2026-07-31" },
    { href: "/research/ai-EB-B8-94-EB-9F-AC-ED-8C-8C-EC-9D-B4-ED-94-84-EB-9D-BC-EC-9D-B8-EC-8B-A4-EC-B8-A1-ED-98-84-ED-99-A9", label: "03", label2: "AI 블러 파이프라인 — 모델·처리 시간 실측 현황", label3: "AI · 블러 · blur · 처리 시간 · latency · 실측", label4: "2026-07-23" },
    { href: "/research/2026-07-21-ai-highlight-blur-EA-B0-9C-EB-B0-9C-EA-B8-B0-EB-A1-9D", label: "04", label2: "AI Highlight-Blur 개발 기록 — 레포 생성부터 dev 배포까지", label3: "AI · 블러 · blur · 하이라이트 · highlight · YOLO", label4: "2026-07-21" },
    { href: "/research/erd-EC-A0-95-EB-A0-AC-EB-94-94-EC-9E-90-EC-9D-B8-EA-B8-B0-EC-A4-80-EB-8D-B0-EC-9D-B4-ED-84-B0-EB-AA-A8-EB-8D-B8", label: "05", label2: "ERD 정렬 — 디자인 기준 데이터모델 결정 (현재 스키마 + 변경 집약)", label3: "ERD · 데이터모델 · 스키마 변경 · V1__init.sql · 14개 테이블 · 소프트 삭제", label4: "2026-07-21" },
    { href: "/research/EB-B6-84-EC-82-B0-EB-9D-BD-EC-A0-81-EC-9A-A9-EC-A3-BC-EC-9D-98-EC-A0-90", label: "06", label2: "분산락 적용 주의점 (그라운드 플립 사례)", label3: "분산락 · distributed lock · Redisson · Redis · 동시성 · concurrency", label4: "2026-07-21" },
    { href: "/research/EB-B0-B1-EC-97-94-EB-93-9C-ED-95-99-EC-8A-B5-EB-A1-9C-EB-93-9C-EB-A7-B5-redis-ha-EC-95-8C-EB-A6-BC-EA-B4-80-EC-B8-A1-EC-84-B1", label: "07", label2: "백엔드 학습 로드맵 — Redis HA · 대규모 알림 · 관측성 (멘토링 08-01 후속)", label3: "학습 로드맵 · 공부 계획 · Redis · 고가용성 · HA · 센티널", label4: "2026-08-03" },
    { href: "/research/EC-A0-84-EA-B5-AD-EB-AC-B8-ED-99-94-EC-B6-95-EC-A0-9C-ED-91-9C-EC-A4-80-EB-8D-B0-EC-9D-B4-ED-84-B0-EB-8D-B0-EC-9D-B4-ED-84-B0-EC-85-8B", label: "08", label2: "전국문화축제표준데이터 데이터셋", label3: "축제 · festival · 문화축제 · 공공데이터 · open data · 표준데이터", label4: "2026-07-21" },
    { href: "/research/EA-B0-AD-EB-B6-84-EC-84-9D-EB-94-94-EC-9E-90-EC-9D-B8-EB-AC-B8-EC-84-9C-EC-BD-94-EB-93-9C-EC-8B-B1-ED-81-AC", label: "09", label2: "갭 분석 — 디자인 ↔ 문서·코드 싱크 (2026-07-17)", label3: "갭 분석 · gap analysis · 디자인 · Figma · 시안 · 싱크", label4: "2026-07-21" },
    { href: "/research/ED-8A-B8-EB-9F-AC-EB-B8-94-EC-8A-88-ED-8C-85-ED-8C-8C-EC-9D-BC-EC-97-86-EC-9D-B4-EA-B2-A9-EC-9E-90-EC-A0-90-EB-A0-B9-msg-132", label: "10", label2: "트러블슈팅 — 파일 없이 격자를 점령할 수 있었던 이유 (MSG-132)", label3: "트러블슈팅 · troubleshooting · MSG-132 · s3Key · 검증 · presigned URL", label4: "2026-07-21" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const TextLink_cids: string[][] = [
    ["n26", "n27", "n28", "n29", "n30", "n31", "n32"],
    ["n33", "n34", "n35", "n36", "n37", "n38", "n39"],
    ["n40", "n41", "n42", "n43", "n44", "n45", "n46"],
    ["n47", "n48", "n49", "n50", "n51", "n52", "n53"]
];
const TextLink2_cids: string[][] = [
    ["n58", "n59", "n60", "n61", "n62", "n63", "n64", "n65"],
    ["n66", "n67", "n68", "n69", "n70", "n71", "n72", "n73"],
    ["n74", "n75", "n76", "n77", "n78", "n79", "n80", "n81"],
    ["n82", "n83", "n84", "n85", "n86", "n87", "n88", "n89"],
    ["n90", "n91", "n92", "n93", "n94", "n95", "n96", "n97"],
    ["n98", "n99", "n100", "n101", "n102", "n103", "n104", "n105"],
    ["n106", "n107", "n108", "n109", "n110", "n111", "n112", "n113"],
    ["n114", "n115", "n116", "n117", "n118", "n119", "n120", "n121"],
    ["n122", "n123", "n124", "n125", "n126", "n127", "n128", "n129"],
    ["n130", "n131", "n132", "n133", "n134", "n135", "n136", "n137"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const TextLink_styles = [
    { className: "max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "max-md:h-21 md:max-lg:h-14" },
    { className: "max-md:grid-rows-[84px_27.25px]", className2: "max-md:h-21" },
    { className: "max-md:grid-rows-[56px_27.25px]", className2: "max-md:h-14" },
    { className: "max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "max-md:h-21 md:max-lg:h-14" }
];
const TextLink2_styles = [
    { className: "grid-rows-[56px] max-md:grid-rows-[112px_27.25px]", className2: "h-14 max-md:h-28" },
    { className: "grid-rows-[56px] max-md:grid-rows-[112px_27.25px]", className2: "h-14 max-md:h-28" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[56px] max-md:grid-rows-[112px_27.25px] md:max-lg:grid-rows-[84px]", className2: "h-14 max-md:h-28 md:max-lg:h-21" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[56px] max-md:grid-rows-[112px_27.25px]", className2: "h-14 max-md:h-28" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[31.5px] max-md:grid-rows-[84px_27.25px] md:max-lg:grid-rows-[56px]", className2: "h-7 max-md:h-21 md:max-lg:h-14" },
    { className: "grid-rows-[56px] max-md:grid-rows-[112px_27.25px] md:max-lg:grid-rows-[84px]", className2: "h-14 max-md:h-28 md:max-lg:h-21" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <p className="h-[1.3125rem] flex mb-3.5 items-center gap-2.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.92px] uppercase before:content-[''] before:block before:w-[0.4375rem] before:h-[0.4375rem] before:bg-primary before:rounded-tl-[50%]" data-cid="n19">
              RESEARCH NOTES
            </p>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              연구 노트
            </h1>
            {" "}
            <p className="w-full max-w-[37.175rem] block mt-3.5 text-muted-foreground" data-cid="n21">
              설계 전에 재본 것과 만든 뒤 실제로 측정한 것. 데이터셋 근거, 파이프라인 실측, 트러블슈팅 기록입니다.
            </p>
            {" "}
          </div>
          {" "}
          <div className="h-[2.3rem] flex mt-18 mb-4.5 justify-between items-baseline gap-4 max-md:mt-10 md:max-lg:mt-[2.875rem]" data-cid="n22">
            <h2 className="block text-[1.3125rem] font-bold leading-[2.3125rem] tracking-[-0.42px]" data-cid="n23" data-component="heading">
              해설 문서
            </h2>
            {" "}
            <span className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[1.1px] uppercase" data-cid="n24">
              읽는 문서 · 그림 포함
            </span>
            {" "}
          </div>
          {" "}
          <div className="border-t border-solid border-t-surface block mb-24 max-md:mb-14 md:max-lg:mb-[69.1px]" data-cid="n25">
            {TextLink_data.map((d, i) => <TextLink key={i} d={d} cids={TextLink_cids[i]} styles={TextLink_styles[i]} />)}
            {" "}
          </div>
          {" "}
          <div className="flex mt-18 mb-4.5 justify-between items-baseline gap-4 max-md:mt-10 md:max-lg:mt-[2.875rem]" data-cid="n54">
            <h2 className="block text-[1.3125rem] font-bold leading-[2.3125rem] tracking-[-0.42px]" data-cid="n55" data-component="heading">
              노트
            </h2>
            {" "}
            <span className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[1.1px] uppercase" data-cid="n56">
              팀 위키에서
            </span>
            {" "}
          </div>
          {" "}
          <div className="border-t border-solid border-t-surface block mb-24 max-md:mb-14 md:max-lg:mb-[69.1px]" data-cid="n57">
            {TextLink2_data.map((d, i) => <TextLink2 key={i} d={d} cids={TextLink2_cids[i]} styles={TextLink2_styles[i]} />)}
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n138">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n139">
          <strong className="inline text-muted-foreground font-bold" data-cid="n140">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
