import "./ditto.css";
import ListRow from "./components/list-row";
import NavLink from "./components/nav-link";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import Tile3 from "./components/tile3";
import Tile4 from "./components/tile4";
import MediaTile from "./components/media-tile";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { kind: "link", href: "/", label: "개요" },
    { kind: "button", href: "/diagrams/0", ariacurrent: "page", label: "다이어그램" },
    { kind: "link", href: "/web-ia", label: "웹 IA" },
    { kind: "link", href: "/spec", label: "기능명세서" },
    { kind: "link", href: "/adr", label: "설계 · ADR" },
    { kind: "link", href: "/dataflow", label: "데이터플로우" },
    { kind: "link", href: "/research", label: "연구노트" },
    { kind: "link", href: "/roles", label: "역할분담" },
    { kind: "link", href: "/m1", label: "M1 계획" }
];
const NavLink_data = [
    { ariacurrent: "page", href: "/diagrams/0", label: "0", label2: "유스케이스" },
    { href: "/diagrams/1", label: "1", label2: "IA · 정보 구조" },
    { href: "/diagrams/2", label: "2", label2: "유저 저니" },
    { href: "/diagrams/3", label: "3", label2: "서비스 아키텍처" },
    { href: "/diagrams/4", label: "4", label2: "시스템 아키텍처" },
    { href: "/diagrams/5", label: "5", label2: "클라우드 아키텍처 · AWS" }
];
const Tile_data = [
    { id: "f0-uc-4", text: "OBS 플러그인 설치·연결 관리", text2: "다운로드 · 키(Stream Key) 등록 · 오디오 트랙 매핑 · 연결/송출 테스트·상태 확인", text3: "UC-04", text4: "스트리머" },
    { id: "f0-uc-5", text: "스트리머 접근 요청", text2: "신청형 — 스트리머 검색 → 요청 → 승인 대기", text3: "UC-05", text4: "편집자" },
    { id: "f0-uc-6", text: "협업 종료", text2: "편집자 측 종료 · 즉시 해당 스트리머 자산 접근 불가", text3: "UC-06", text4: "편집자" },
    { id: "f0-uc-7", text: "편집자 승인·권한 관리", text2: "승인/반려 · 권한 단계 설정 · 회수(즉시 전면 차단)", text3: "UC-07", text4: "스트리머" }
];
const Tile2_data = [
    { id: "f0-uc-8", text: "알림 설정 관리", text2: "알림 종류별 on/off · 수신 채널 TBD", text3: "UC-08" },
    { id: "f0-uc-9", text: "계정 삭제", text2: "활성 구독 해지 선행 · 데이터·소유권 처리 · 보관물 정책 TBD", text3: "UC-09" },
    { id: "f0-uc-10", text: "문의·지원 요청", text2: "가입 전·후 공통 · 접수 상태·답변 확인", text3: "UC-10" }
];
const Tile3_data = [
    { id: "f0-uc-14", text: "자동 하이라이트 생성", text2: "채팅 피크 감지 · 목표 3초 이내", text3: "UC-14", text4: "편집자" },
    { id: "f0-uc-15", text: "방송 종료 시 VOD 전환·보관", text2: "60일 · 만료 카드 챕터 재활성화", text3: "UC-15", text4: "편집자" },
    { id: "f0-uc-16", text: "서비스 이벤트 알림 발송", text2: "방송 시작 · 승인 요청/결과 · 결제 실패 · VOD 만료 임박", text3: "UC-16", text4: "편집자" },
    { id: "f0-uc-17", text: "구독 갱신·종량 청구", text2: "결제 처리 한정(PG) · 사용량 계측은 내부 처리 · 종량 기준 TBD", text3: "UC-17", text4: "결제 시스템" }
];
const Tile4_data = [
    { id: "f0-uc-18", text: "라이브 시청", text2: "최대 1시간 되감기", text3: "UC-18" },
    { id: "f0-uc-19", text: "실시간 채팅량 그래프 확인", text2: "하이라이트 마커 포함 · VOD에서도 재생", text3: "UC-19" },
    { id: "f0-uc-20", text: "하이라이트 카드 목록 확인", text2: "자동+수동 · 실시간 갱신 · 만료/처리 상태 표시 · 숨김·무시 — 편집은 UC-22로 진입", text3: "UC-20" },
    { id: "f0-uc-21", text: "VOD 시청", text2: "카드 = 챕터 · 채팅량 그래프 재생 · 라이브와 동일한 편집 진입", text3: "UC-21" }
];
const MediaTile_data = [
    { id: "f0-actor-G", text: "Google", text2: "«external system»", text3: "OAuth 로그인" },
    { id: "f0-actor-C", text: "치지직 / SOOP", text2: "«external system»", text3: "방송 플랫폼 · 채팅 소스" },
    { id: "f0-actor-Y", text: "YouTube", text2: "«external system»", text3: "클립 업로드 · CC 등록" },
    { id: "f0-actor-P", text: "결제 시스템", text2: "«external · PG»", text3: "구독 결제 · 종량 과금" }
];
const ListRow_cids: string[][] = [
    ["n10", "n11"],
    ["n12", "n13"],
    ["n14", "n15"],
    ["n16", "n17"],
    ["n18", "n19"],
    ["n20", "n21"],
    ["n22", "n23"],
    ["n24", "n25"],
    ["n26", "n27"]
];
const NavLink_cids: string[][] = [
    ["n36", "n37"],
    ["n38", "n39"],
    ["n40", "n41"],
    ["n42", "n43"],
    ["n44", "n45"],
    ["n46", "n47"]
];
const Tile_cids: string[][] = [
    ["n113", "n114", "n115", "n116", "n117", "n118"],
    ["n119", "n120", "n121", "n122", "n123", "n124"],
    ["n125", "n126", "n127", "n128", "n129", "n130"],
    ["n131", "n132", "n133", "n134", "n135", "n136"]
];
const Tile2_cids: string[][] = [
    ["n137", "n138", "n139", "n140", "n141", "n142", "n143"],
    ["n144", "n145", "n146", "n147", "n148", "n149", "n150"],
    ["n151", "n152", "n153", "n154", "n155", "n156", "n157"]
];
const Tile3_cids: string[][] = [
    ["n187", "n188", "n189", "n190", "n191", "n192", "n193", "n194"],
    ["n195", "n196", "n197", "n198", "n199", "n200", "n201", "n202"],
    ["n203", "n204", "n205", "n206", "n207", "n208", "n209", "n210"],
    ["n211", "n212", "n213", "n214", "n215", "n216", "n217", "n218"]
];
const Tile4_cids: string[][] = [
    ["n223", "n224", "n225", "n226", "n227", "n228", "n229"],
    ["n230", "n231", "n232", "n233", "n234", "n235", "n236"],
    ["n237", "n238", "n239", "n240", "n241", "n242", "n243"],
    ["n244", "n245", "n246", "n247", "n248", "n249", "n250"]
];
const MediaTile_cids: string[][] = [
    ["n351", "n352", "n353", "n354", "n355"],
    ["n356", "n357", "n358", "n359", "n360"],
    ["n361", "n362", "n363", "n364", "n365"],
    ["n366", "n367", "n368", "n369", "n370"]
];
const ListRow_styles = [
    { className: "text-muted-foreground" },
    { className: "text-accent font-bold bg-surface-4" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const NavLink_styles = [
    { className: "border-foreground text-background font-semibold bg-foreground", className2: "bg-surface-7" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" }
];
const Tile_styles = [
    { className: "h-[0.9375rem]" },
    { className2: "h-3" },
    { className2: "h-3" },
    { className2: "h-3" }
];
const Tile2_styles = [
    { className: "h-3" },
    {  },
    { className: "h-3" }
];
const Tile3_styles = [
    { className: "h-[109.7px]", className3: "h-3" },
    { className: "h-[109.7px]", className2: "h-[0.9375rem]", className3: "h-3" },
    { className: "h-[109.7px]", className2: "h-[0.9375rem]", className3: "h-3" },
    { className: "h-[6.8625rem]" }
];
const Tile4_styles = [
    {  },
    { className: "h-[0.9375rem]", className2: "h-3" },
    { className: "h-[0.9375rem]" },
    {  }
];
const MediaTile_styles = [
    { className: "top-[2.6rem]" },
    { className: "top-36", className2: "h-3.5" },
    { className: "top-[32.975rem]", className2: "h-3.5" },
    { className: "top-[414.5px]", className2: "h-3.5" }
];

export default function Page() {
  return (
    <>
      <div className="h-full block" data-cid="n1" id="root">
        <a className="w-30 h-[2.7rem] block absolute -top-12 left-4 z-100 py-2 px-4 rounded-[10px] text-background bg-foreground cursor-pointer max-md:w-28.5 max-md:h-[41.3px] md:max-lg:h-[42.5px]" data-cid="n2" data-component="link" href="#main">
          본문 바로가기
        </a>
        <header className="h-[58.3px] border-b border-solid border-b-border block sticky top-0 z-40 bg-background [backdrop-filter:blur(10px)] max-md:h-[6.175rem]" data-cid="n3">
          <div className="h-full flex max-w-295 mx-auto py-[0.7rem] px-10 items-center gap-[2.4rem] max-md:px-[1.0875rem] max-md:flex-wrap max-md:gap-y-[0.2rem] max-md:gap-x-4 md:max-lg:px-[1.7rem] md:max-lg:gap-[1.4375rem]" data-cid="n4">
            <a className="h-[28.5px] flex items-baseline gap-2 text-[1.0625rem] font-extrabold leading-[1.8125rem] tracking-[-0.35px] whitespace-nowrap text-nowrap cursor-pointer" data-cid="n5" data-component="link" href="/">
              <span className="h-[9.5px] block rounded-[50%] self-center bg-color-017 shadow-[var(--clr-16)_0px_0px_0px_0.724957px] [animation-name:rec-pulse] [animation-duration:2.2s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] max-md:shadow-[var(--clr-1)_0px_0px_0px_0.0675255px] md:max-lg:shadow-[var(--clr-1)_0px_0px_0px_0.174665px] 2xl:shadow-[var(--clr-1)_0px_0px_0px_0.100444px]" data-cid="n6" aria-hidden="true" />
              PokeClip
              <span className="block text-color-005 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1rem] tracking-[1.79px] uppercase" data-cid="n7">
                Architecture
              </span>
            </a>
            <nav className="block min-w-0 max-md:order-[3]" data-cid="n8" data-component="nav" aria-label="주요 메뉴">
              <ul className="flex gap-[0.7rem] overflow-auto [list-style-type:none] list-outside max-md:-mx-2 max-md:pt-[0.15rem] max-md:pb-[0.4rem] max-md:px-2 max-md:gap-1 md:max-lg:gap-[7.7px]" data-cid="n9">
                {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
              </ul>
            </nav>
          </div>
        </header>
        <main className="block" data-cid="n28" id="main">
          <div className="block max-w-295 mx-auto pt-[3.4rem] pb-[5.6rem] px-10 max-md:pt-8 max-md:pb-14 max-md:px-[1.0875rem] md:max-lg:pt-[2.6rem] md:max-lg:pb-[69.1px] md:max-lg:px-[1.7rem] 2xl:pt-16 2xl:pb-26" data-cid="n29">
            <header className="w-full max-w-200 block mb-[2.8rem] max-md:mb-[1.8rem] md:max-lg:mb-[2.1625rem] 2xl:mb-12" data-cid="n30">
              <p className="block mb-[0.9rem] text-accent [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.3125rem] tracking-[1.75px] uppercase" data-cid="n31">
                Diagrams 0–5
              </p>
              <h1 className="block text-[2.625rem] font-extrabold leading-[3.125rem] tracking-[-0.84px] text-balance max-md:text-[1.75rem] max-md:leading-[2.0625rem] max-md:tracking-[-0.56px] md:max-lg:text-[2.125rem] md:max-lg:leading-10 md:max-lg:tracking-[-0.68px] 2xl:text-[2.6875rem] 2xl:leading-[3.1875rem] 2xl:tracking-[-0.86px]" data-cid="n32" data-component="heading">
                아키텍처 다이어그램
              </h1>
              <p className="block mt-[0.9rem] text-muted-foreground text-[1.0625rem] leading-[1.75rem] max-lg:text-base max-md:leading-[1.625rem] md:max-lg:leading-[1.6875rem]" data-cid="n33">
                self-contained HTML이 원본이다 — 다이어그램 보기는 화면 폭에 맞춰 자동 축소, 문서 보기는 같은 내용을 반응형 텍스트로 보여준다.
              </p>
            </header>
            <div className="flex mb-[1.4rem] flex-wrap justify-between items-center gap-4" data-cid="n34">
              <nav className="flex flex-wrap gap-2" data-cid="n35" data-component="nav" aria-label="다이어그램 선택">
                {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
              </nav>
              <div className="border border-solid border-color-009 flex p-[0.1875rem] rounded-[999px] bg-surface" data-cid="n48" aria-label="보기 방식" role="group">
                <button className="block py-[5.1px] px-[0.95rem] rounded-[999px] text-background text-sm font-semibold leading-[1.375rem] text-center bg-foreground cursor-pointer" data-cid="n49" data-component="button" aria-pressed="true" type="button">
                  다이어그램
                </button>
                <button className="block py-[5.1px] px-[0.95rem] rounded-[999px] text-muted-foreground text-sm leading-[1.375rem] text-center cursor-pointer" data-cid="n50" data-component="button" aria-pressed="false" type="button">
                  문서 보기
                </button>
              </div>
            </div>
            <section className="block" data-cid="n51" aria-label="유스케이스 다이어그램 뷰어">
              <div className="flex mb-[0.7rem] flex-wrap justify-between items-baseline gap-4" data-cid="n52">
                <p className="flex items-baseline gap-[0.6rem] font-bold" data-cid="n53">
                  <span className="block text-color-017 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[1.625rem] leading-[1.625rem]" data-cid="n54" aria-hidden="true">
                    0
                  </span>
                  유스케이스
                  <span className="block text-color-005 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-xs font-medium leading-[1.1875rem] tracking-[1.38px] uppercase" data-cid="n55">
                    Use Case
                  </span>
                </p>
                <div className="flex gap-[0.9rem] text-[0.8125rem] leading-[1.375rem]" data-cid="n56">
                  <button className="border-b border-solid border-b-color-009 block pb-px text-muted-foreground text-center cursor-pointer" data-cid="n57" data-component="button" type="button">
                    전체화면
                  </button>
                  <a className="border-b border-solid border-b-color-009 block pb-px text-muted-foreground cursor-pointer" data-cid="n58" data-component="link" href="https://poke-clip-architecture.vercel.app/diagrams/0_Pokeclip_UseCase.html" rel="noreferrer" target="_blank">
                    원본 새 탭 ↗
                  </a>
                </div>
              </div>
              <div className="h-156 border border-solid border-border block rounded-[10px] overflow-hidden bg-surface max-md:h-[39.5875rem] md:max-lg:h-[798.7px] 2xl:h-[52.65rem]" data-cid="n59">
                <div className="w-274.5 h-155.5 block relative max-w-full overflow-hidden max-md:w-84.5 max-md:h-[39.4375rem] md:max-lg:w-178 md:max-lg:h-[49.8125rem] 2xl:h-210" data-cid="n60" title="유스케이스 다이어그램">
                  <div className="h-full block overflow-hidden text-color-001 [font-family:'Segoe_UI',_'Malgun_Gothic',_'Apple_SD_Gothic_Neo',_sans-serif] text-[0.8125rem] leading-[1.125rem] bg-surface-5" data-cid="n61">
                    <div className="h-155.5 block absolute top-0 inset-x-0 overflow-hidden bg-surface-5 [background-size:22px_22px] cursor-grab max-md:h-[39.4375rem] md:max-lg:h-[49.8125rem] 2xl:h-210" style={{ backgroundImage: "radial-gradient(var(--clr-19) 1px, var(--clr-20) 1px)" }} data-cid="n62" id="f0-stage">
                      <div className="w-474 h-[80.125rem] block absolute pt-3.5 pb-4.5 px-4.5 transform-[matrix(0.475476,0,0,0.475476,98.2489,6.22)] origin-[0px_0px] max-md:transform-[matrix(0.174705,0,0,0.174705,3.38,203.514)] md:max-lg:transform-[matrix(0.368017,0,0,0.368017,7.12,162.601)] 2xl:transform-[matrix(0.567532,0,0,0.567532,10.98,56.2122)]" data-cid="n63" id="f0-inner">
                        <header className="w-465 block mb-3" data-cid="n64">
                          <h1 className="inline-block pt-1 pb-[0.3125rem] px-[0.9375rem] text-surface text-xl font-extrabold leading-7 tracking-[0.2px] bg-color-001" data-cid="n65" data-component="heading">
                            Use Case Diagram
                          </h1>
                          {" "}
                          <div className="block mt-[0.3125rem] text-color-003 text-xs leading-[1rem]" data-cid="n66">
                            {"PokeClip · 액터 "}
                            <b className="inline text-color-001 font-bold" data-cid="n67">
                              6
                            </b>
                            {"(사람 2 · 외부 시스템 4) · 유스케이스 "}
                            <b className="inline text-color-001 font-bold" data-cid="n68">
                              32
                            </b>
                            {" · 그룹 "}
                            <b className="inline text-color-001 font-bold" data-cid="n69">
                              6
                            </b>
                            {" · v3.1 — 실선은 액터↔역할 그룹 관여 · 유스케이스별 참여자는 박스 안 배지 · 액터나 박스를 클릭하면 관련 요소만 남습니다"}
                          </div>
                          {" "}
                        </header>
                        {" "}
                        <div className="w-465 h-295 min-h-295 flex relative items-stretch gap-6.5" data-cid="n70" id="f0-wrap">
                          <svg className="w-465 h-295 block absolute z-1 min-w-0 overflow-hidden pointer-events-none" data-cid="n71" data-component="image" height="1180" id="f0-wires" width="1860" fill="currentColor">
                            <path d="M 151.9999935427436 722.6249563614728 L 169.00000830687287 722.6249563614728 L 169.00000830687287 337.03120826838403 L 504.90623305516897 337.03120826838403" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="S" data-zone="auto" />
                            <circle cx="504.90623305516897" cy="337.03120826838403" r="2.6" fill="#16181c" opacity="0.5" data-actor="S" data-zone="auto" />
                            <path d="M 151.9999935427436 727.6249563614728 L 169.00000830687287 727.6249563614728 L 169.00000830687287 480.3359498231954 L 191.00000749512347 480.3359498231954" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="S" data-zone="acc" />
                            <circle cx="191.00000749512347" cy="480.3359498231954" r="2.6" fill="#16181c" opacity="0.5" data-actor="S" data-zone="acc" />
                            <path d="M 151.9999935427436 732.6249563614728 L 169.00000830687287 732.6249563614728 L 169.00000830687287 588.0000130509707 L 818.8280691331855 588.0000130509707" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="S" data-zone="edit" />
                            <circle cx="818.8280691331855" cy="588.0000130509707" r="2.6" fill="#16181c" opacity="0.5" data-actor="S" data-zone="edit" />
                            <path d="M 151.9999935427436 737.6249563614728 L 169.00000830687287 737.6249563614728 L 169.00000830687287 595.0000130509707 L 1400.8593282303768 595.0000130509707" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="S" data-zone="bill" />
                            <circle cx="1400.8593282303768" cy="595.0000130509707" r="2.6" fill="#16181c" opacity="0.5" data-actor="S" data-zone="bill" />
                            <path d="M 151.9999935427436 742.6249563614728 L 169.00000830687287 742.6249563614728 L 169.00000830687287 913.0312722251383 L 504.90623305516897 913.0312722251383" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="S" data-zone="view" />
                            <circle cx="504.90623305516897" cy="913.0312722251383" r="2.6" fill="#16181c" opacity="0.5" data-actor="S" data-zone="view" />
                            <path d="M 151.9999935427436 747.6249563614728 L 169.00000830687287 747.6249563614728 L 169.00000830687287 1063.3359101244519 L 191.00000749512347 1063.3359101244519" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="S" data-zone="live" />
                            <circle cx="191.00000749512347" cy="1063.3359101244519" r="2.6" fill="#16181c" opacity="0.5" data-actor="S" data-zone="live" />
                            <path d="M 151.9999935427436 613.9062511196543 L 163.00000830687287 613.9062511196543 L 163.00000830687287 351.03120826838403 L 504.90623305516897 351.03120826838403" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="E" data-zone="auto" />
                            <circle cx="504.90623305516897" cy="351.03120826838403" r="2.6" fill="#16181c" opacity="0.5" data-actor="E" data-zone="auto" />
                            <path d="M 151.9999935427436 618.9062511196543 L 163.00000830687287 618.9062511196543 L 163.00000830687287 494.3359498231954 L 191.00000749512347 494.3359498231954" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="E" data-zone="acc" />
                            <circle cx="191.00000749512347" cy="494.3359498231954" r="2.6" fill="#16181c" opacity="0.5" data-actor="E" data-zone="acc" />
                            <path d="M 151.9999935427436 623.9062511196543 L 163.00000830687287 623.9062511196543 L 163.00000830687287 602.0000130509707 L 818.8280691331855 602.0000130509707" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="E" data-zone="edit" />
                            <circle cx="818.8280691331855" cy="602.0000130509707" r="2.6" fill="#16181c" opacity="0.5" data-actor="E" data-zone="edit" />
                            <path d="M 151.9999935427436 628.9062511196543 L 163.00000830687287 628.9062511196543 L 163.00000830687287 927.0312722251383 L 504.90623305516897 927.0312722251383" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="E" data-zone="view" />
                            <circle cx="504.90623305516897" cy="927.0312722251383" r="2.6" fill="#16181c" opacity="0.5" data-actor="E" data-zone="view" />
                            <path d="M 1707.9999629153867 84.68749534643672 L 1691.0000336670432 84.68749534643672 L 1691.0000336670432 473.3359498231954 L 488.90621918545105 473.3359498231954" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="G" data-zone="acc" />
                            <circle cx="488.90621918545105" cy="473.3359498231954" r="2.6" fill="#16181c" opacity="0.5" data-actor="G" data-zone="acc" />
                            <path d="M 1707.9999629153867 184.62495813892403 L 1697.0000336670432 184.62495813892403 L 1697.0000336670432 337.03120826838403 L 802.8280552634676 337.03120826838403" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="C" data-zone="auto" />
                            <circle cx="802.8280552634676" cy="337.03120826838403" r="2.6" fill="#16181c" opacity="0.5" data-actor="C" data-zone="auto" />
                            <path d="M 1707.9999629153867 189.62495813892403 L 1697.0000336670432 189.62495813892403 L 1697.0000336670432 487.3359498231954 L 488.90621918545105 487.3359498231954" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="C" data-zone="acc" />
                            <circle cx="488.90621918545105" cy="487.3359498231954" r="2.6" fill="#16181c" opacity="0.5" data-actor="C" data-zone="acc" />
                            <path d="M 1707.9999629153867 568.1874501893783 L 1703.0000336670432 568.1874501893783 L 1703.0000336670432 501.3359498231954 L 488.90621918545105 501.3359498231954" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="Y" data-zone="acc" />
                            <circle cx="488.90621918545105" cy="501.3359498231954" r="2.6" fill="#16181c" opacity="0.5" data-actor="Y" data-zone="acc" />
                            <path d="M 1707.9999629153867 573.1874501893783 L 1703.0000336670432 573.1874501893783 L 1703.0000336670432 595.0000130509707 L 1384.8593972850572 595.0000130509707" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="Y" data-zone="edit" />
                            <circle cx="1384.8593972850572" cy="595.0000130509707" r="2.6" fill="#16181c" opacity="0.5" data-actor="Y" data-zone="edit" />
                            <path d="M 1707.9999629153867 455.07807342592275 L 1709.0000336670432 455.07807342592275 L 1709.0000336670432 351.03120826838403 L 802.8280552634676 351.03120826838403" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="P" data-zone="auto" />
                            <circle cx="802.8280552634676" cy="351.03120826838403" r="2.6" fill="#16181c" opacity="0.5" data-actor="P" data-zone="auto" />
                            <path d="M 1707.9999629153867 460.07807342592275 L 1709.0000336670432 460.07807342592275 L 1709.0000336670432 595.0000130509707 L 1668.984258112025 595.0000130509707" stroke="#16181c" fill="none" strokeWidth="1.2" opacity="0.5" strokeLinejoin="round" data-actor="P" data-zone="bill" />
                            <circle cx="1668.984258112025" cy="595.0000130509707" r="2.6" fill="#16181c" opacity="0.5" data-actor="P" data-zone="bill" />
                          </svg>
                          {" "}
                          <aside className="block relative z-2 shrink-0 basis-[148px]" data-cid="n72" id="f0-side-left">
                            <div className="h-[98.3px] block absolute top-171.5 inset-x-0 text-center cursor-pointer" data-cid="n73" id="f0-actor-S">
                              <svg className="w-auto h-9.5 inline mb-1 overflow-hidden" data-cid="n74" data-component="icon" fill="none" height="38" stroke="#16181c" viewBox="0 0 30 38" width="30" strokeWidth="2" strokeLinecap="round">
                                <circle cx="15" cy="6" r="4.6" />
                                <path d="M15 11v13M4 16h22M15 24l-8 11M15 24l8 11" />
                              </svg>
                              <div className="block text-sm font-extrabold leading-[1.25rem]" data-cid="n75">
                                스트리머
                              </div>
                              <div className="block mt-px text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.625rem] leading-[0.8125rem] tracking-[0.28px]" data-cid="n76">
                                Streamer
                              </div>
                              <div className="h-3.5 block mt-[0.1875rem] text-color-003 text-[0.6875rem] leading-[0.875rem]" data-cid="n77">
                                방송 소유자 · 모든 권한
                              </div>
                            </div>
                            <div className="h-[98.3px] block absolute top-[572.3px] inset-x-0 text-center cursor-pointer" data-cid="n78" id="f0-actor-E">
                              <svg className="w-auto h-9.5 inline mb-1 overflow-hidden" data-cid="n79" data-component="icon" fill="none" height="38" stroke="#16181c" viewBox="0 0 30 38" width="30" strokeWidth="2" strokeLinecap="round">
                                <circle cx="15" cy="6" r="4.6" />
                                <path d="M15 11v13M4 16h22M15 24l-8 11M15 24l8 11" />
                              </svg>
                              <div className="block text-sm font-extrabold leading-[1.25rem]" data-cid="n80">
                                편집자
                              </div>
                              <div className="block mt-px text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.625rem] leading-[0.8125rem] tracking-[0.28px]" data-cid="n81">
                                Editor
                              </div>
                              <div className="h-3.5 block mt-[0.1875rem] text-color-003 text-[0.6875rem] leading-[0.875rem]" data-cid="n82">
                                승인받은 협업자 · 권한 단계형
                              </div>
                            </div>
                          </aside>
                          {" "}
                          <section className="h-295 border border-dashed border-color-012 flex relative z-2 min-w-0 pt-6.5 pb-4 px-4 rounded-sm flex-col flex-1" data-cid="n83" id="f0-boundary">
                            <h2 className="w-[121.3px] h-[1.375rem] border border-solid border-color-001 block absolute -top-2.5 left-5.5 min-w-0 py-0.5 px-3 text-xs font-bold leading-[1rem] tracking-[0.57px] bg-surface-5" data-cid="n84" data-component="heading">
                              PokeClip 시스템
                            </h2>
                            {" "}
                            <div className="grid items-stretch flex-1 gap-4 grid-cols-[297.906px_297.922px_566.031px_268.125px] grid-rows-[1136px]" data-cid="n85" id="f0-zones">
                              <div className="h-284 flex min-w-0 flex-col gap-4" data-cid="n86">
                                <div className="h-[920.7px] border border-dashed border-color-015 flex relative pt-[0.9375rem] pb-[0.5625rem] px-[0.5625rem] rounded-sm flex-col grow-[10]" data-cid="n87" id="f0-zone-acc">
                                  <h3 className="w-[5.6625rem] h-[18.7px] border border-solid border-color-001 flex absolute -top-[0.5625rem] left-3 min-w-0 py-px px-[0.5625rem] items-center gap-1.5 text-[0.6875rem] font-bold leading-[0.9375rem] tracking-[0.32px] whitespace-nowrap text-nowrap bg-surface-5" data-cid="n88" data-component="heading">
                                    {"계정 · 연동 "}
                                    <span className="block text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] font-normal leading-[0.8125rem]" data-cid="n89">
                                      10
                                    </span>
                                  </h3>
                                  <div className="grid items-center flex-1 gap-[0.4375rem] grid-cols-[278px] grid-rows-[83.1562px_83.1719px_83.1719px_83.1562px_83.1719px_83.1719px_83.1562px_83.1719px_83.1719px_83.1719px] [grid-auto-rows:1fr]" data-cid="n90">
                                    <div className="h-[5.2rem] min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n91" id="f0-uc-1">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n92">
                                        구글 로그인
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n93">
                                        최초 1회 약관 동의 포함
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n94">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n95">
                                          UC-01
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n96">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n97">
                                          편집자
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n98">
                                          Google
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-[5.2rem] min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n99" id="f0-uc-2">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n100">
                                        방송 채널 연동 관리
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n101">
                                        치지직/SOOP · 연동+해제
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n102">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n103">
                                          UC-02
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n104">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n105">
                                          치지직 / SOOP
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-[5.2rem] min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n106" id="f0-uc-3">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n107">
                                        유튜브 채널 연동 관리
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n108">
                                        연동+해제 · 업로드 대상 채널 선택 · 만료 재인증
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n109">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n110">
                                          UC-03
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n111">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n112">
                                          YouTube
                                        </span>
                                      </span>
                                    </div>
                                    {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} styles={Tile_styles[i]} />)}
                                    {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} styles={Tile2_styles[i]} />)}
                                  </div>
                                </div>
                                <div className="h-[199.3px] border border-dashed border-color-015 flex relative pt-[0.9375rem] pb-[0.5625rem] px-[0.5625rem] rounded-sm flex-col grow-[2]" data-cid="n158" id="f0-zone-live">
                                  <h3 className="w-[119.7px] h-[18.7px] border border-solid border-color-001 flex absolute -top-[0.5625rem] left-3 min-w-0 py-px px-[0.5625rem] items-center gap-1.5 text-[0.6875rem] font-bold leading-[0.9375rem] tracking-[0.32px] whitespace-nowrap text-nowrap bg-surface-5" data-cid="n159" data-component="heading">
                                    {"방송 · 하이라이트 "}
                                    <span className="h-[0.7875rem] block text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] font-normal leading-[0.8125rem]" data-cid="n160">
                                      2
                                    </span>
                                  </h3>
                                  <div className="grid items-center flex-1 gap-[0.4375rem] grid-cols-[278px] grid-rows-[83.1562px_83.1719px] [grid-auto-rows:1fr]" data-cid="n161">
                                    <div className="h-[5.2rem] min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n162" id="f0-uc-11">
                                      <span className="h-[0.9375rem] block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n163">
                                        PokeClip 동시 송출 시작·종료
                                      </span>
                                      <span className="block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n164">
                                        OBS 플러그인 경유 · 영상 1 + 오디오 6트랙 — 시스템은 수신·트랙 분리 저장(되감기 1시간 버퍼)
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n165">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n166">
                                          UC-11
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n167">
                                          스트리머
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-[5.2rem] min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n168" id="f0-uc-12">
                                      <span className="h-[0.9375rem] block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n169">
                                        핫키 수동 하이라이트 표시
                                      </span>
                                      <span className="block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n170">
                                        방송 중 전역 핫키 → 앞뒤 구간이 수동 하이라이트로 승격 · 대시보드 카드 표시
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n171">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n172">
                                          UC-12
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n173">
                                          스트리머
                                        </span>
                                      </span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div className="h-284 flex min-w-0 flex-col gap-4" data-cid="n174">
                                <div className="h-[39.625rem] border border-dashed border-color-015 flex relative pt-[0.9375rem] pb-[0.5625rem] px-[0.5625rem] rounded-sm flex-col grow-[5]" data-cid="n175" id="f0-zone-auto">
                                  <h3 className="w-[5.6625rem] h-[18.7px] border border-solid border-color-001 flex absolute -top-[0.5625rem] left-3 min-w-0 py-px px-[0.5625rem] items-center gap-1.5 text-[0.6875rem] font-bold leading-[0.9375rem] tracking-[0.32px] whitespace-nowrap text-nowrap bg-surface-5" data-cid="n176" data-component="heading">
                                    {"시스템 자동 "}
                                    <span className="h-[0.7875rem] block text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] font-normal leading-[0.8125rem]" data-cid="n177">
                                      5
                                    </span>
                                  </h3>
                                  <div className="border-l-2 border-solid border-l-color-010 block mt-px mb-[0.4375rem] mx-[0.1875rem] pl-[0.4375rem] text-color-003 text-[0.5625rem] leading-[0.75rem]" data-cid="n178">
                                    시스템이 실행 · 배지는 수혜자/데이터 제공자이며 실행 주체가 아님
                                  </div>
                                  <div className="grid items-center flex-1 gap-[0.4375rem] grid-cols-[278px] grid-rows-[109.734px_109.734px_109.734px_109.734px_109.75px] [grid-auto-rows:1fr]" data-cid="n179">
                                    <div className="h-[109.7px] min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n180" id="f0-uc-13">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n181">
                                        채팅 자동 수집
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n182">
                                        방송 시작과 함께 · 플랫폼은 데이터 제공자
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n183">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n184">
                                          UC-13
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n185">
                                          치지직 / SOOP
                                        </span>
                                        <span className="border border-solid border-color-012 block px-1.5 text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem]" data-cid="n186">
                                          auto
                                        </span>
                                      </span>
                                    </div>
                                    {Tile3_data.map((d, i) => <Tile3 key={i} d={d} cids={Tile3_cids[i]} styles={Tile3_styles[i]} />)}
                                  </div>
                                </div>
                                <div className="h-[30.375rem] border border-dashed border-color-015 flex relative pt-[0.9375rem] pb-[0.5625rem] px-[0.5625rem] rounded-sm flex-col grow-[4]" data-cid="n219" id="f0-zone-view">
                                  <h3 className="w-[6.775rem] h-[18.7px] border border-solid border-color-001 flex absolute -top-[0.5625rem] left-3 min-w-0 py-px px-[0.5625rem] items-center gap-1.5 text-[0.6875rem] font-bold leading-[0.9375rem] tracking-[0.32px] whitespace-nowrap text-nowrap bg-surface-5" data-cid="n220" data-component="heading">
                                    {"시청 · 모니터링 "}
                                    <span className="h-[0.7875rem] block text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] font-normal leading-[0.8125rem]" data-cid="n221">
                                      4
                                    </span>
                                  </h3>
                                  <div className="grid items-center flex-1 gap-[0.4375rem] grid-cols-[278px] grid-rows-[109.734px_109.734px_109.734px_109.734px] [grid-auto-rows:1fr]" data-cid="n222">
                                    {Tile4_data.map((d, i) => <Tile4 key={i} d={d} cids={Tile4_cids[i]} styles={Tile4_styles[i]} />)}
                                  </div>
                                </div>
                              </div>
                              <div className="h-284 flex min-w-0 flex-col gap-4" data-cid="n251">
                                <div className="h-full border border-dashed border-color-015 flex relative pt-[0.9375rem] pb-[0.5625rem] px-[0.5625rem] rounded-sm flex-col grow-[11]" data-cid="n252" id="f0-zone-edit">
                                  <h3 className="w-[97.1px] h-[18.7px] border border-solid border-color-001 flex absolute -top-[0.5625rem] left-3 min-w-0 py-px px-[0.5625rem] items-center gap-1.5 text-[0.6875rem] font-bold leading-[0.9375rem] tracking-[0.32px] whitespace-nowrap text-nowrap bg-surface-5" data-cid="n253" data-component="heading">
                                    {"편집 · 업로드 "}
                                    <span className="h-[0.7875rem] block text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] font-normal leading-[0.8125rem]" data-cid="n254">
                                      9
                                    </span>
                                  </h3>
                                  <div className="h-277.5 grid items-center flex-1 gap-[0.4375rem] grid-cols-[269.516px_269.516px] grid-rows-[216.391px_216.406px_216.391px_216.406px_216.391px] [grid-auto-rows:1fr]" data-cid="n255">
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px col-span-full text-center bg-surface cursor-pointer" data-cid="n256" id="f0-uc-22">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n257">
                                        클립 편집
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n258">
                                        카드 또는 보관함 편집본에서 진입 · 라이브/VOD 동일
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n259">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n260">
                                          UC-22
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n261">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n262">
                                          편집자
                                        </span>
                                      </span>
                                      <div className="flex mt-1 flex-wrap justify-center gap-1" data-cid="n263">
                                        <span className="h-[17.3px] border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface max-md:h-auto" data-cid="n264">
                                          구간 선택 (5초~3분)
                                        </span>
                                        <span className="border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface" data-cid="n265">
                                          오디오 트랙 켜기/끄기
                                        </span>
                                        <span className="h-[17.3px] border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface max-md:h-auto" data-cid="n266">
                                          트랙 미리듣기·볼륨 (무음 트랙 자동 숨김)
                                        </span>
                                        <span className="border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface" data-cid="n267">
                                          웨이브폼 표시
                                        </span>
                                        <span className="h-[17.3px] border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface max-md:h-auto" data-cid="n268">
                                          AI 자막 + 직접 수정
                                        </span>
                                        <span className="h-[17.3px] border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface max-md:h-auto" data-cid="n269">
                                          자막 3모드 (번인+CC / 번인 / CC)
                                        </span>
                                        <span className="h-[17.3px] border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface max-md:h-auto" data-cid="n270">
                                          화면 비율 (가로·9:16·1:1·상하분할·크롭)
                                        </span>
                                        <span className="h-[17.3px] border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface max-md:h-auto" data-cid="n271">
                                          브라우저 미리보기 (서버 렌더 없음)
                                        </span>
                                        <span className="h-[17.3px] border border-solid border-color-010 block py-px px-1.5 text-color-003 text-[0.625rem] leading-[0.8125rem] bg-surface max-md:h-auto" data-cid="n272">
                                          제목 추천 (자막 기반)
                                        </span>
                                      </div>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n273" id="f0-uc-23">
                                      <span className="h-[0.9375rem] block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n274">
                                        편집본 저장·불러오기·재출력
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n275">
                                        재출력은 VOD 보관 60일 내
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n276">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n277">
                                          UC-23
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n278">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n279">
                                          편집자
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n280" id="f0-uc-24">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n281">
                                        업로드 템플릿 관리
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n282">
                                        저장 · 지정 · 수정 · 삭제
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n283">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n284">
                                          UC-24
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n285">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n286">
                                          편집자
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n287" id="f0-uc-25">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n288">
                                        유튜브 업로드
                                      </span>
                                      <span className="block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n289">
                                        기본 비공개 · 제목·설명 확정 · CC 등록 — 권한 없으면 UC-29로 분기
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n290">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n291">
                                          UC-25
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n292">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n293">
                                          편집자
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n294">
                                          YouTube
                                        </span>
                                        <span className="h-[0.9125rem] border border-solid border-color-012 block px-1.5 text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] max-md:h-auto" data-cid="n295">
                                          편집자: 직접 업로드 권한
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n296" id="f0-uc-26">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n297">
                                        원클릭 자동 업로드
                                      </span>
                                      <span className="block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n298">
                                        템플릿 지정 전제 · 핫키 또는 카드 액션에서 편집 화면 없이 — 권한 없으면 UC-29로 분기
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n299">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n300">
                                          UC-26
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n301">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n302">
                                          편집자
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n303">
                                          YouTube
                                        </span>
                                        <span className="border border-solid border-color-012 block px-1.5 text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem]" data-cid="n304">
                                          편집자: 원클릭 권한
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n305" id="f0-uc-27">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n306">
                                        업로드 상태 확인·복구
                                      </span>
                                      <span className="block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n307">
                                        진행·결과 확인 · 실패 시 재인증·수동 재시도·취소 · 유튜브 링크
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n308">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n309">
                                          UC-27
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n310">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n311">
                                          편집자
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n312">
                                          YouTube
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n313" id="f0-uc-28">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n314">
                                        클립·편집본 삭제
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n315">
                                        사용자 삭제권 · 업로드된 유튜브 영상은 미삭제
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n316">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n317">
                                          UC-28
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n318">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n319">
                                          편집자
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n320" id="f0-uc-29">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n321">
                                        업로드 승인 요청
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n322">
                                        UC-25·26에서 권한 부족 시 차단 대신 승인 대기함으로
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n323">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n324">
                                          UC-29
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n325">
                                          편집자
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n326" id="f0-uc-30">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n327">
                                        업로드 승인 / 반려
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n328">
                                        승인 대기함 처리 · 클립 미리보기로 판단
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n329">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n330">
                                          UC-30
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n331">
                                          스트리머
                                        </span>
                                      </span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div className="h-284 flex min-w-0 flex-col gap-4" data-cid="n332">
                                <div className="h-full border border-dashed border-color-015 flex relative pt-[0.9375rem] pb-[0.5625rem] px-[0.5625rem] rounded-sm flex-col grow-[2]" data-cid="n333" id="f0-zone-bill">
                                  <h3 className="w-[5.3625rem] h-[18.7px] border border-solid border-color-001 flex absolute -top-[0.5625rem] left-3 min-w-0 py-px px-[0.5625rem] items-center gap-1.5 text-[0.6875rem] font-bold leading-[0.9375rem] tracking-[0.32px] whitespace-nowrap text-nowrap bg-surface-5" data-cid="n334" data-component="heading">
                                    {"구독 · 결제 "}
                                    <span className="h-[0.7875rem] block text-color-003 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] font-normal leading-[0.8125rem]" data-cid="n335">
                                      2
                                    </span>
                                  </h3>
                                  <div className="h-277.5 grid items-center flex-1 gap-[0.4375rem] grid-cols-[248.1px] grid-rows-[551.5px_551.5px] [grid-auto-rows:1fr]" data-cid="n336">
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n337" id="f0-uc-31">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n338">
                                        구독 관리
                                      </span>
                                      <span className="h-3 block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n339">
                                        가입 · 플랜 변경 · 해지 · 결제 수단 · 결제 실패 복구
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n340">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n341">
                                          UC-31
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n342">
                                          스트리머
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n343">
                                          결제 시스템
                                        </span>
                                      </span>
                                    </div>
                                    <div className="h-37.5 min-h-11.5 border border-solid border-color-001 flex relative max-h-37.5 pt-1.5 pb-[0.3125rem] px-[0.5625rem] rounded-md flex-col justify-center gap-px text-center bg-surface cursor-pointer" data-cid="n344" id="f0-uc-32">
                                      <span className="block text-[0.8125rem] font-bold leading-[0.9375rem]" data-cid="n345">
                                        사용량·청구 조회
                                      </span>
                                      <span className="block text-color-003 text-[0.625rem] leading-[0.75rem]" data-cid="n346">
                                        실시간 사용량(진행 중 과금 누적) · 기간별 청구 내역
                                      </span>
                                      <span className="flex mt-0.5 flex-wrap justify-center gap-[0.3125rem]" data-cid="n347">
                                        <span className="border border-solid border-color-001 block px-1.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.5625rem] leading-[0.8125rem] tracking-[0.36px]" data-cid="n348">
                                          UC-32
                                        </span>
                                        <span className="border border-solid border-color-002 block px-1.5 text-color-007 text-[0.5625rem] leading-[0.8125rem] bg-surface-3" data-cid="n349">
                                          스트리머
                                        </span>
                                      </span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            {" "}
                          </section>
                          {" "}
                          <aside className="block relative z-2 shrink-0 basis-[148px]" data-cid="n350" id="f0-side-right">
                            {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} cids={MediaTile_cids[i]} styles={MediaTile_styles[i]} />)}
                          </aside>
                          {" "}
                        </div>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                    <div className="h-[1.8375rem] border border-solid border-color-010 flex absolute right-3 bottom-3 left-[719.5px] z-5 py-1 px-1.5 rounded-md items-center gap-1.5 text-color-007 text-[0.6875rem] leading-[0.9375rem] bg-surface shadow-[var(--clr-21)_0px_1px_3px_0px] max-md:h-[2.8rem] max-md:left-0 md:max-lg:left-[333.5px]" data-cid="n371" id="f0-hud">
                      <button className="h-full border border-solid border-color-010 block py-px px-2 rounded-sm text-center bg-surface cursor-pointer" data-cid="n372" data-component="button" id="f0-btnFit" type="button">
                        맞춤
                      </button>
                      {" "}
                      <button className="border border-solid border-color-010 block py-px px-2 rounded-sm text-center bg-surface cursor-pointer" data-cid="n373" data-component="button" id="f0-btnOut" type="button">
                        −
                      </button>
                      {" "}
                      <span className="w-10.5 block min-w-10.5 [font-family:Consolas,_'Cascadia_Mono',_monospace] text-[0.625rem] leading-3.5 text-center" data-cid="n374" id="f0-zoomPct">
                        48%
                      </span>
                      {" "}
                      <button className="border border-solid border-color-010 block py-px px-2 rounded-sm text-center bg-surface cursor-pointer" data-cid="n375" data-component="button" id="f0-btnIn" type="button">
                        ＋
                      </button>
                      {" "}
                      <span className="border-l border-solid border-l-surface-8 block ml-0.5 pl-[0.4375rem] text-color-012" data-cid="n376">
                        드래그 이동 · 휠 스크롤 · Ctrl+휠 확대
                      </span>
                      {" "}
                    </div>
                    {" "}
                  </div>
                </div>
              </div>
              <p className="block mt-[0.7rem] text-color-005 text-[0.8125rem] leading-[1.375rem]" data-cid="n377">
                빈 곳을 드래그하면 화면이 따라옵니다 · 휠은 스크롤, Ctrl+휠은 확대 · 액터나 유스케이스를 클릭하면 관련 요소만 남고 나머지는 흐려집니다 — 같은 것을 다시 클릭하거나 빈 곳 클릭·Escape로 해제.
              </p>
            </section>
          </div>
        </main>
        <footer className="border-t border-solid border-t-border block bg-surface" data-cid="n378">
          <div className="block max-w-295 mx-auto pt-[2.2rem] pb-12 px-10 text-muted-foreground text-[0.9375rem] leading-[1.5rem] max-md:px-[1.0875rem] md:max-lg:px-[1.7rem]" data-cid="n379">
            <p className="h-[24.3px] block max-md:h-[3.0375rem]" data-cid="n380">
              <strong className="inline font-bold" data-cid="n381">
                PokeClip
              </strong>
              {" — 스트리밍 하이라이트·클립 자동화 서비스의 아키텍처 산출물."}
            </p>
          </div>
        </footer>
      </div>
      {" "}
    </>
  );
}
