import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", ariacurrent: "page", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-07-21" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "파일 없이 격자를 점령할 수 있었던 원인은?" },
    { text: "인코딩이 실패해도 점령이 남는 이유는?" },
    { text: "prefix 검사만으로는 왜 못 막나?" },
    { text: "최종 검증 3종은 각각 뭘 막나?" },
    { text: "왜 UNIQUE 제약을 V1이 아닌 V2 파일로 넣었나?" },
    { text: "앱 검사와 DB 제약을 둘 다 두는 이유는?" },
    { text: "아직 안 풀린 문제는?" }
];
const ListRow2_data2 = [
    { text: "prefix 검사(소유권)와 headObject(실존)는 서로 다른 걸 막는다 — 둘 다 필요." },
    { text: "함정 2개: 기존 통합 테스트가 실제 AWS S3 호출(→ @MockitoBean S3Client), “같은 키 재업로드” 테스트가 현실과 다름(테스트가 낡음)." },
    { text: "앱 검사(existsBy)는 4xx UX용, DB UNIQUE는 동시성 최종 방어선." }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n31"],
    ["n32"],
    ["n33"],
    ["n34"],
    ["n35"],
    ["n36"],
    ["n37"]
];
const ListRow2_cids2: string[][] = [
    ["n45"],
    ["n46"],
    ["n47"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/research">
              ← 연구 노트
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              트러블슈팅 — 파일 없이 격자를 점령할 수 있었던 이유 (MSG-132)
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="block mt-[14.5px] text-muted-foreground" data-cid="n28">
                saveVideo가 s3Key를 검증 없이 저장해서 파일 업로드 없이 좌표만으로 지도 전체를 칠할 수 있었다 — 점령이 인코딩보다 먼저라 인코딩 실패도 못 막음. 수정: 검증 3종(소유권 prefix + 중복 existsBy+DB UNIQUE + 실존 headObject)을 saveVideo 진입부에 배치. prefix만으론 못 막는다(공격자가 자기 userId를 앎). UNIQUE는 새 V2 마이그레이션으로(V1 수정은 CI가 차단 — 32시간 다운 사고 재발 방지). 테스트 121건 통과. 미해결: 진짜 고아 객체(MSG-133)·기존 데이터 소급 검증.
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n29" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n30">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n38" data-component="heading" id="요약">
              요약
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n39">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n40">
                {"원인: "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n41">
                  saveVideo
                </code>
                가 s3Key 무검증 저장 + 점령(upsertUserGrid)이 인코딩 트리거보다 먼저 → 가짜 키로 200 OK·점령.
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n42">
                발견: presigned URL 고아 객체 조사 중 부수 발견. 재현 테스트 5건 중 4건 실패로 확인 후 수정.
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n43" data-component="heading" id="발견">
              발견
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n44">
              {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids2[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n48" data-component="heading" id="시사점">
              시사점
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n49">
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n50">
                적용된 Flyway V 파일은 절대 수정 금지(CI 가드, MSG-130) — 스키마 변경은 항상 새 V 파일.
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n51">
                미해결: “올렸는데 확정 안 한” 진짜 고아는 MSG-133에서(같은 prefix라 단순 만료 규칙 불가), 기존 저장 데이터 소급 검증은 운영 전 점검.
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n52" data-component="heading" id="원본-링크">
              원본 링크
            </h2>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground max-md:h-14" data-cid="n53">
              {"리포 문서: "}
              <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n54">
                docs/MSG-132-troubleshooting.html
              </code>
              {" · 관련 티켓: MSG-132·MSG-133·MSG-130"}
            </p>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n55">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n56">
          <strong className="inline text-muted-foreground font-bold" data-cid="n57">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
