import Link from "next/link";

import contributions from "@/data/contributions.json";

/**
 * Team contribution donuts on the 팀·역할 index.
 *
 * Each donut splits one area of the repo among the three members, measured
 * from the phone repo's main history — squash-only, so one commit is one PR
 * and authorship can't be blurred by merge commits. The numbers are a
 * committed snapshot (src/data/contributions.json), regenerated by hand:
 * the source repo isn't available at deploy time, and a stale-but-dated
 * number beats a build that can't run.
 */

const MEMBERS = [
  { key: "jo", label: "조재영", color: "var(--primary)" },
  { key: "ahn", label: "안XX", color: "var(--ok)" },
  { key: "kwon", label: "권XX", color: "var(--warn)" },
] as const;

/** Areas shown as donuts, in display order. android stays detail-only. */
const DONUT_AREAS = [
  "overall",
  "backend",
  "infra",
  "docs",
  "jira",
  "app",
  "ios",
] as const;

const R = 15.9155; // circumference 100 — dash values are percentages
const CIRC = 100;

type AreaData = {
  label: string;
  total: number;
  /** Counting unit shown under the donut. Defaults to PR. */
  unit?: string;
  members: Record<string, { commits: number; lines: number; pct: number }>;
};

function Donut({ area }: { area: AreaData }) {
  const segments = MEMBERS.map((m) => ({
    ...m,
    pct: area.members[m.key]?.pct ?? 0,
    commits: area.members[m.key]?.commits ?? 0,
  }));
  const mine = segments[0];

  let offset = 25; // start at 12 o'clock
  return (
    <Link
      href="/team/contributions"
      className="group flex flex-col items-center gap-2 rounded-card border border-border bg-surface-1 px-4 py-5 no-underline transition-colors hover:border-border-strong hover:bg-surface-2"
      aria-label={`${area.label} 기여 상세 — 조재영 ${mine.pct}%`}
    >
      <span className="relative inline-block size-[7.5rem]">
        <svg viewBox="0 0 42 42" className="size-full -rotate-0">
          <circle
            cx="21"
            cy="21"
            r={R}
            fill="none"
            stroke="var(--border)"
            strokeWidth="4.4"
          />
          {segments.map((s) => {
            const el = s.pct > 0 && (
              <circle
                key={s.key}
                cx="21"
                cy="21"
                r={R}
                fill="none"
                stroke={s.color}
                strokeWidth="4.4"
                strokeDasharray={`${s.pct} ${CIRC - s.pct}`}
                strokeDashoffset={offset}
              />
            );
            offset -= s.pct;
            return el;
          })}
        </svg>
        <span className="absolute inset-0 flex flex-col items-center justify-center">
          <span className="font-mono text-[1.35rem] font-bold leading-none tabular-nums text-foreground group-hover:text-primary">
            {Math.round(mine.pct)}
            <span className="text-[0.8rem] font-semibold">%</span>
          </span>
          <span className="mt-1 font-mono text-[0.5625rem] uppercase tracking-[0.08em] text-muted">
            조재영
          </span>
        </span>
      </span>

      <span className="text-center text-[0.8125rem] font-semibold leading-snug text-foreground">
        {area.label}
      </span>
      <span className="font-mono text-[0.6875rem] tabular-nums text-muted">
        {mine.commits.toLocaleString()}/{area.total.toLocaleString()} {area.unit ?? "PR"}
      </span>
    </Link>
  );
}

export function ContributionDonuts() {
  const areas = contributions.areas as Record<string, AreaData>;

  return (
    <section aria-labelledby="contrib-heading" className="mb-12">
      <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
        <h2 id="contrib-heading" className="text-[1.05rem] font-bold tracking-[-0.01em]">
          기여 분담
        </h2>
        <ul className="flex items-center gap-3">
          {MEMBERS.map((m) => (
            <li key={m.key} className="flex items-center gap-1.5 text-[0.75rem] text-muted-foreground">
              <span
                aria-hidden
                className="inline-block size-2 rounded-pill"
                style={{ backgroundColor: m.color }}
              />
              {m.label}
            </li>
          ))}
        </ul>
      </div>

      <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
        {DONUT_AREAS.map((key) => (
          <Donut key={key} area={areas[key]} />
        ))}
      </div>

      <p className="mt-3 text-[0.75rem] leading-relaxed text-muted-foreground">
        {contributions.basis} · 기준일 {contributions.asOf} · 링을 클릭하면{" "}
        <Link href="/team/contributions" className="text-primary">
          산정 방법과 영역별 상세
        </Link>
        로 이동합니다.
      </p>
    </section>
  );
}
