import "./ditto.css";
import ListRow from "./components/list-row";
import NavLink from "./components/nav-link";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import Tile3 from "./components/tile3";
import Tile4 from "./components/tile4";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { kind: "link", href: "/", label: "개요" },
    { kind: "button", href: "/diagrams/0", ariacurrent: "page", label: "다이어그램" },
    { kind: "link", href: "/web-ia", label: "웹 IA" },
    { kind: "link", href: "/spec", label: "기능명세서" },
    { kind: "link", href: "/adr", label: "설계 · ADR" },
    { kind: "link", href: "/dataflow", label: "데이터플로우" },
    { kind: "link", href: "/research", label: "연구노트" },
    { kind: "link", href: "/roles", label: "역할분담" },
    { kind: "link", href: "/m1", label: "M1 계획" }
];
const NavLink_data = [
    { href: "/diagrams/0", label: "0", label2: "유스케이스" },
    { href: "/diagrams/1", label: "1", label2: "IA · 정보 구조" },
    { href: "/diagrams/2", label: "2", label2: "유저 저니" },
    { href: "/diagrams/3", ariacurrent: "page", label: "3", label2: "서비스 아키텍처" },
    { href: "/diagrams/4", label: "4", label2: "시스템 아키텍처" },
    { href: "/diagrams/5", label: "5", label2: "클라우드 아키텍처 · AWS" }
];
const Tile_data = [
    { id: "f0-ex-google", text: "Google OAuth" },
    { id: "f0-ex-soop", text: "SOOP" },
    { id: "f0-ex-chzzk", text: "CHZZK" },
    { id: "f0-ex-youtube", text: "YouTube Data API" },
    { id: "f0-ui-setup", text: "온보딩·설정" }
];
const Tile2_data = [
    { id: "f0-ui-vod", text: "VOD 뷰", text2: "(60일)" },
    { id: "f0-sv-auth", text: "Auth·Account Service", text2: "(Spring Boot · H1~H5)" },
    { id: "f0-sv-clip", text: "Clip Service", text2: "(Spring Boot · D2·E2·E3·E8·F4)" },
    { id: "f0-sv-chat", text: "Chat Collector·Analytics", text2: "(Node·TS · C1~C6)" },
    { id: "f0-sv-media", text: "Media Origin", text2: "(Go · B1~B7)" }
];
const Tile3_data = [
    { id: "f0-q-ai", text: "AI 잡 큐" },
    { id: "f0-q-render", text: "렌더 잡 큐" },
    { id: "f0-q-upload", text: "업로드 잡 큐" },
    { id: "f0-q-evt", text: "방송이벤트 큐" }
];
const Tile4_data = [
    { id: "f0-st-pg", text: "PostgreSQL" },
    { id: "f0-st-s3", text: "S3" },
    { id: "f0-st-rd", text: "Redis" }
];
const ListRow_cids: string[][] = [
    ["n10", "n11"],
    ["n12", "n13"],
    ["n14", "n15"],
    ["n16", "n17"],
    ["n18", "n19"],
    ["n20", "n21"],
    ["n22", "n23"],
    ["n24", "n25"],
    ["n26", "n27"]
];
const NavLink_cids: string[][] = [
    ["n36", "n37"],
    ["n38", "n39"],
    ["n40", "n41"],
    ["n42", "n43"],
    ["n44", "n45"],
    ["n46", "n47"]
];
const Tile_cids: string[][] = [
    ["n79", "n80"],
    ["n81", "n82"],
    ["n83", "n84"],
    ["n85", "n86"],
    ["n87", "n88"]
];
const Tile2_cids: string[][] = [
    ["n99", "n100", "n101"],
    ["n102", "n103", "n104"],
    ["n105", "n106", "n107"],
    ["n108", "n109", "n110"],
    ["n111", "n112", "n113"]
];
const Tile3_cids: string[][] = [
    ["n114", "n115"],
    ["n116", "n117"],
    ["n118", "n119"],
    ["n120", "n121"]
];
const Tile4_cids: string[][] = [
    ["n128", "n129"],
    ["n130", "n131"],
    ["n132", "n133"]
];
const ListRow_styles = [
    { className: "text-muted-foreground" },
    { className: "text-accent font-bold bg-surface-4" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const NavLink_styles = [
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-foreground text-background font-semibold bg-foreground", className2: "bg-surface-7" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" },
    { className: "border-border text-muted-foreground bg-surface", className2: "text-foreground bg-surface-2" }
];
const Tile_styles = [
    { className: "w-62.5 h-15.5 top-12 left-[5.9375rem]" },
    { className: "w-50 h-15.5 top-12 left-360" },
    { className: "w-55 h-15.5 top-12 left-457.5" },
    { className: "w-62.5 h-15.5 top-12 left-595" },
    { className: "w-55 h-20.5 top-50 left-75" }
];
const Tile2_styles = [
    { className: "w-57.5 h-20.5 border top-50 left-540", className2: "font-bold" },
    { className: "w-80 h-26 border top-117.5 left-37.5", className2: "font-bold" },
    { className: "w-190 h-26 border top-117.5 left-140", className2: "font-bold" },
    { className: "w-135 h-26 border top-117.5 left-372.5", className2: "font-bold" },
    { className: "w-107.5 h-26 border-2 top-117.5 left-532.5", className2: "font-extrabold" }
];
const Tile3_styles = [
    { className: "w-45 left-162.5" },
    { className: "w-45 left-230" },
    { className: "w-40 left-290" },
    { className: "w-65 left-390" }
];
const Tile4_styles = [
    { className: "w-105 left-97.5" },
    { className: "w-140 left-310" },
    { className: "w-95 left-527.5" }
];

export default function Page() {
  return (
    <>
      <div className="h-full block" data-cid="n1" id="root">
        <a className="w-30 h-[2.7rem] block absolute -top-12 left-4 z-100 py-2 px-4 rounded-[10px] text-background bg-foreground cursor-pointer max-md:w-28.5 max-md:h-[41.3px] md:max-lg:h-[42.5px]" data-cid="n2" data-component="link" href="#main">
          본문 바로가기
        </a>
        <header className="h-[58.3px] border-b border-solid border-b-border block sticky top-0 z-40 bg-background [backdrop-filter:blur(10px)] max-md:h-[6.175rem]" data-cid="n3">
          <div className="h-full flex max-w-295 mx-auto py-[0.7rem] px-10 items-center gap-[2.4rem] max-md:px-[1.0875rem] max-md:flex-wrap max-md:gap-y-[0.2rem] max-md:gap-x-4 md:max-lg:px-[1.7rem] md:max-lg:gap-[1.4375rem]" data-cid="n4">
            <a className="h-[28.5px] flex items-baseline gap-2 text-[1.0625rem] font-extrabold leading-[1.8125rem] tracking-[-0.35px] whitespace-nowrap text-nowrap cursor-pointer" data-cid="n5" data-component="link" href="/">
              <span className="h-[9.5px] block rounded-[50%] self-center bg-color-017 shadow-[var(--clr-9)_0px_0px_0px_3.77028px] [animation-name:rec-pulse] [animation-duration:2.2s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] max-md:shadow-[var(--clr-5)_0px_0px_0px_4.34734px] md:max-lg:shadow-[var(--clr-7)_0px_0px_0px_5.98934px] 2xl:shadow-[var(--clr-11)_0px_0px_0px_1.50924px]" data-cid="n6" aria-hidden="true" />
              PokeClip
              <span className="block text-color-005 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1rem] tracking-[1.79px] uppercase" data-cid="n7">
                Architecture
              </span>
            </a>
            <nav className="block min-w-0 max-md:order-[3]" data-cid="n8" data-component="nav" aria-label="주요 메뉴">
              <ul className="flex gap-[0.7rem] overflow-auto [list-style-type:none] list-outside max-md:-mx-2 max-md:pt-[0.15rem] max-md:pb-[0.4rem] max-md:px-2 max-md:gap-1 md:max-lg:gap-[7.7px]" data-cid="n9">
                {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
              </ul>
            </nav>
          </div>
        </header>
        <main className="block" data-cid="n28" id="main">
          <div className="block max-w-295 mx-auto pt-[3.4rem] pb-[5.6rem] px-10 max-md:pt-8 max-md:pb-14 max-md:px-[1.0875rem] md:max-lg:pt-[2.6rem] md:max-lg:pb-[69.1px] md:max-lg:px-[1.7rem] 2xl:pt-16 2xl:pb-26" data-cid="n29">
            <header className="w-full max-w-200 block mb-[2.8rem] max-md:mb-[1.8rem] md:max-lg:mb-[2.1625rem] 2xl:mb-12" data-cid="n30">
              <p className="block mb-[0.9rem] text-accent [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.3125rem] tracking-[1.75px] uppercase" data-cid="n31">
                Diagrams 0–5
              </p>
              <h1 className="block text-[2.625rem] font-extrabold leading-[3.125rem] tracking-[-0.84px] text-balance max-md:text-[1.75rem] max-md:leading-[2.0625rem] max-md:tracking-[-0.56px] md:max-lg:text-[2.125rem] md:max-lg:leading-10 md:max-lg:tracking-[-0.68px] 2xl:text-[2.6875rem] 2xl:leading-[3.1875rem] 2xl:tracking-[-0.86px]" data-cid="n32" data-component="heading">
                아키텍처 다이어그램
              </h1>
              <p className="block mt-[0.9rem] text-muted-foreground text-[1.0625rem] leading-[1.75rem] max-lg:text-base max-md:leading-[1.625rem] md:max-lg:leading-[1.6875rem]" data-cid="n33">
                self-contained HTML이 원본이다 — 다이어그램 보기는 화면 폭에 맞춰 자동 축소, 문서 보기는 같은 내용을 반응형 텍스트로 보여준다.
              </p>
            </header>
            <div className="flex mb-[1.4rem] flex-wrap justify-between items-center gap-4" data-cid="n34">
              <nav className="flex flex-wrap gap-2" data-cid="n35" data-component="nav" aria-label="다이어그램 선택">
                {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
              </nav>
              <div className="border border-solid border-color-009 flex p-[0.1875rem] rounded-[999px] bg-surface" data-cid="n48" aria-label="보기 방식" role="group">
                <button className="block py-[5.1px] px-[0.95rem] rounded-[999px] text-background text-sm font-semibold leading-[1.375rem] text-center bg-foreground cursor-pointer" data-cid="n49" data-component="button" aria-pressed="true" type="button">
                  다이어그램
                </button>
                <button className="block py-[5.1px] px-[0.95rem] rounded-[999px] text-muted-foreground text-sm leading-[1.375rem] text-center cursor-pointer" data-cid="n50" data-component="button" aria-pressed="false" type="button">
                  문서 보기
                </button>
              </div>
            </div>
            <section className="block" data-cid="n51" aria-label="서비스 아키텍처 다이어그램 뷰어">
              <div className="flex mb-[0.7rem] flex-wrap justify-between items-baseline gap-4" data-cid="n52">
                <p className="h-[1.825rem] flex items-baseline gap-[0.6rem] font-bold max-md:h-[28.3px] md:max-lg:h-[29.5px]" data-cid="n53">
                  <span className="block text-color-017 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-[1.625rem] leading-[1.625rem]" data-cid="n54" aria-hidden="true">
                    3
                  </span>
                  서비스 아키텍처
                  <span className="block text-color-005 [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-xs font-medium leading-[1.1875rem] tracking-[1.38px] uppercase" data-cid="n55">
                    Service Architecture
                  </span>
                </p>
                <div className="flex gap-[0.9rem] text-[0.8125rem] leading-[1.375rem]" data-cid="n56">
                  <div className="border border-solid border-color-009 flex rounded-[999px] items-stretch overflow-hidden bg-surface" data-cid="n57" aria-label="확대/축소" role="group">
                    <button className="block py-0.5 px-[0.6rem] text-muted-foreground text-sm leading-[1.25rem] text-center cursor-pointer" data-cid="n58" data-component="button" aria-label="축소" title="축소" type="button">
                      −
                    </button>
                    <button className="w-[3.4rem] border-r border-solid border-r-border border-l border-l-border block min-w-[3.4rem] py-0.5 px-[0.6rem] text-muted-foreground [font-family:ui-monospace,_'SF_Mono',_'Cascadia_Mono',_Menlo,_monospace] text-xs leading-[1rem] text-center cursor-pointer" data-cid="n59" data-component="button" title="화면 폭에 맞춤" type="button">
                      100%
                    </button>
                    <button className="block py-0.5 px-[0.6rem] text-muted-foreground text-sm leading-[1.25rem] text-center cursor-pointer" data-cid="n60" data-component="button" aria-label="확대" title="확대" type="button">
                      ＋
                    </button>
                  </div>
                  <button className="border-b border-solid border-b-color-009 block pb-px text-muted-foreground text-center cursor-pointer" data-cid="n61" data-component="button" type="button">
                    전체화면
                  </button>
                  <a className="border-b border-solid border-b-color-009 block pb-px text-muted-foreground cursor-pointer" data-cid="n62" data-component="link" href="https://poke-clip-architecture.vercel.app/diagrams/3_Pokeclip_SA.html" rel="noreferrer" target="_blank">
                    원본 새 탭 ↗
                  </a>
                </div>
              </div>
              <div className="h-148 border border-solid border-border block rounded-[10px] overflow-hidden bg-surface max-md:h-46 md:max-lg:h-96" data-cid="n63">
                <div className="h-full block relative" data-cid="n64">
                  <div className="w-675 h-362.5 block absolute overflow-hidden transform-[matrix(0.406667,0,0,0.406667,0,0)] origin-[0px_0px] pointer-events-none max-md:transform-[matrix(0.125278,0,0,0.125278,0,0)] md:max-lg:transform-[matrix(0.263565,0,0,0.263565,0,0)]" data-cid="n65" title="서비스 아키텍처 다이어그램">
                    <div className="w-675 h-362.5 block relative text-color-004 [font-family:Pretendard,_'Noto_Sans_KR',_'Noto_Sans_CJK_KR',_'Apple_SD_Gothic_Neo',_sans-serif] text-base leading-4.5 bg-surface-5 [background-size:30px_30px] [background-position:15px_15px]" style={{ backgroundImage: "radial-gradient(circle, var(--clr-24) 1.2px, var(--clr-20) 1.2px)" }} data-cid="n66">
                      <div className="w-665 h-30.5 border border-dashed border-color-016 block absolute top-4.5 left-5 z-0 rounded-2xl bg-color-038" data-cid="n67" />
                      {" "}
                      <div className="w-665 h-36.5 border border-dashed border-color-016 block absolute top-42 left-5 z-0 rounded-2xl bg-color-038" data-cid="n68" />
                      {" "}
                      <div className="w-665 h-42 border border-dashed border-color-016 block absolute top-109.5 left-5 z-0 rounded-2xl bg-color-038" data-cid="n69" />
                      {" "}
                      <div className="w-665 h-37 border border-dashed border-color-016 block absolute top-182 left-5 z-0 rounded-2xl bg-color-038" data-cid="n70" />
                      {" "}
                      <div className="w-665 h-42 border border-dashed border-color-016 block absolute top-242 left-5 z-0 rounded-2xl bg-color-038" data-cid="n71" />
                      {" "}
                      <div className="w-665 h-43.5 border border-dashed border-color-016 block absolute top-314.5 left-5 z-0 rounded-2xl bg-color-038" data-cid="n72" />
                      {" "}
                      <div className="w-[4.675rem] h-3 block absolute top-7 left-10 z-1 text-color-039 text-xs font-extrabold leading-3 tracking-[1.6px]" data-cid="n73">
                        EXTERNAL
                      </div>
                      {" "}
                      <div className="w-[51.1px] h-3 block absolute top-44.5 left-10 z-1 text-color-039 text-xs font-extrabold leading-3 tracking-[1.6px]" data-cid="n74">
                        CLIENT
                      </div>
                      {" "}
                      <div className="w-[61.5px] h-3 block absolute top-112 left-10 z-1 text-color-039 text-xs font-extrabold leading-3 tracking-[1.6px]" data-cid="n75">
                        SERVICE
                      </div>
                      {" "}
                      <div className="w-[3.0625rem] h-3 block absolute top-184.5 left-10 z-1 text-color-039 text-xs font-extrabold leading-3 tracking-[1.6px]" data-cid="n76">
                        QUEUE
                      </div>
                      {" "}
                      <div className="w-15.5 h-3 block absolute top-244.5 left-10 z-1 text-color-039 text-xs font-extrabold leading-3 tracking-[1.6px]" data-cid="n77">
                        WORKER
                      </div>
                      {" "}
                      <div className="w-[2.2875rem] h-3 block absolute top-317 left-10 z-1 text-color-039 text-xs font-extrabold leading-3 tracking-[1.6px]" data-cid="n78">
                        DATA
                      </div>
                      {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} styles={Tile_styles[i]} />)}
                      {" "}
                      <div className="w-55 h-20.5 border border-solid border-color-004 flex absolute top-50 left-145 z-3 py-1.5 px-2 rounded-[3px] flex-col justify-center items-center text-center bg-surface cursor-pointer" data-cid="n89" data-component="button" id="f0-ui-ops" role="button">
                        <div className="block text-[0.8125rem] font-bold leading-[1rem]" data-cid="n90">
                          운영 콘솔
                        </div>
                        <div className="block mt-[0.1875rem] text-color-029 text-[0.625rem] font-medium leading-[0.8125rem]" data-cid="n91">
                          (운영자)
                        </div>
                      </div>
                      {" "}
                      <div className="w-65 h-20.5 border border-solid border-color-004 flex absolute top-50 left-215 z-3 py-1.5 px-2 rounded-[3px] flex-col justify-center items-center text-center bg-surface cursor-pointer" data-cid="n92" data-component="button" id="f0-ui-plugin" role="button">
                        <div className="block text-[0.8125rem] font-bold leading-[1rem]" data-cid="n93">
                          OBS 플러그인
                        </div>
                        <div className="block mt-[0.1875rem] text-color-029 text-[0.625rem] font-medium leading-[0.8125rem]" data-cid="n94">
                          (SRT 송출)
                        </div>
                      </div>
                      {" "}
                      <div className="w-57.5 h-20.5 border border-solid border-color-004 flex absolute top-50 left-295 z-3 py-1.5 px-2 rounded-[3px] flex-col justify-center items-center text-center bg-surface cursor-pointer" data-cid="n95" data-component="button" id="f0-ui-editor" role="button">
                        <div className="block text-[0.8125rem] font-bold leading-[1rem]" data-cid="n96">
                          클립 에디터·보관함
                        </div>
                      </div>
                      {" "}
                      <div className="w-75 h-20.5 border border-solid border-color-004 flex absolute top-50 left-400 z-3 py-1.5 px-2 rounded-[3px] flex-col justify-center items-center text-center bg-surface cursor-pointer" data-cid="n97" data-component="button" id="f0-ui-live" role="button">
                        <div className="block text-[0.8125rem] font-bold leading-[1rem]" data-cid="n98">
                          라이브 뷰
                        </div>
                      </div>
                      {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} styles={Tile2_styles[i]} />)}
                      {Tile3_data.map((d, i) => <Tile3 key={i} d={d} cids={Tile3_cids[i]} styles={Tile3_styles[i]} />)}
                      {" "}
                      <div className="w-60 h-26 border border-solid border-color-004 flex absolute top-250 left-163 z-3 py-1.5 px-2 rounded-[3px] flex-col justify-center items-center text-center bg-surface cursor-pointer" data-cid="n122" data-component="button" id="f0-sv-ai" role="button">
                        <div className="block text-[0.8125rem] font-bold leading-[1rem]" data-cid="n123">
                          AI Worker
                        </div>
                        <div className="block mt-[0.1875rem] text-color-029 text-[0.625rem] font-medium leading-[0.8125rem]" data-cid="n124">
                          (Python·Whisper · E4·E7)
                        </div>
                      </div>
                      {" "}
                      <div className="w-75 h-26 border border-solid border-color-004 flex absolute top-250 left-279.5 z-3 py-1.5 px-2 rounded-[3px] flex-col justify-center items-center text-center bg-surface cursor-pointer" data-cid="n125" data-component="button" id="f0-sv-render" role="button">
                        <div className="block text-[0.8125rem] font-bold leading-[1rem]" data-cid="n126">
                          Render·Upload Worker
                        </div>
                        <div className="block mt-[0.1875rem] text-color-029 text-[0.625rem] font-medium leading-[0.8125rem]" data-cid="n127">
                          (Spring+FFmpeg · F1~F5)
                        </div>
                      </div>
                      {Tile4_data.map((d, i) => <Tile4 key={i} d={d} cids={Tile4_cids[i]} styles={Tile4_styles[i]} />)}
                      {" "}
                      <svg className="w-675 h-362.5 block absolute z-2 overflow-hidden pointer-events-none" data-cid="n134" data-component="image" id="f0-wires" fill="currentColor">
                        <defs>
                          <marker id="ar" markerWidth="9" markerHeight="9" refX="7" refY="3.6" orient="auto" markerUnits="userSpaceOnUse">
                            <path d="M1,1 L7,3.6 L1,6.2" fill="none" stroke="#8f8f8f" strokeWidth="1.15" />
                          </marker>
                          <marker id="ar-r" markerWidth="9" markerHeight="9" refX="7" refY="3.6" orient="auto" markerUnits="userSpaceOnUse">
                            <path d="M1,1 L7,3.6 L1,6.2" fill="none" stroke="#e02424" strokeWidth="1.4" />
                          </marker>
                        </defs>
                        <path d="M 220 470 L 220 290 L 220 290 L 220 110" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-auth" data-b="ex-google" />
                        <path d="M 1540 470 L 1540 272 L 1540 272 L 1540 110" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-chat" data-b="ex-soop" />
                        <path d="M 1940 470 L 1940 326 L 1940 326 L 1940 110" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-chat" data-b="ex-chzzk" />
                        <path d="M 1418 1052 L 2660 1052 L 2660 160 L 2505 160 L 2505 110" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-render" data-b="ex-youtube" />
                        <path d="M 312 282 L 312 376 L 298 376 L 298 470" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-setup" data-b="sv-auth" />
                        <path d="M 872 282 L 872 394 L 322 394 L 322 470" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-plugin" data-b="sv-auth" />
                        <path d="M 788 282 L 788 358 L 916 358 L 916 470" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-ops" data-b="sv-clip" />
                        <path d="M 940 282 L 940 412 L 940 412 L 940 470" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-plugin" data-b="sv-clip" />
                        <path d="M 1120 270 L 1144 270 L 1144 155 L 2106 155 L 2106 522 L 2130 522" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-plugin" data-b="sv-media" />
                        <path d="M 1192 282 L 1192 340 L 964 340 L 964 470" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-editor" data-b="sv-clip" />
                        <path d="M 1600 270 L 1576 270 L 1576 380 L 1344 380 L 1344 501.2 L 1320 501.2" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-live" data-b="sv-clip" />
                        <path d="M 1760 282 L 1760 430 L 1760 430 L 1760 470" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-live" data-b="sv-chat" />
                        <path d="M 1888 282 L 1888 452 L 2333 452 L 2333 470" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-live" data-b="sv-media" />
                        <path d="M 2345 282 L 2345 376 L 2357 376 L 2357 470" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="ui-vod" data-b="sv-media" />
                        <path d="M 458 574 L 458 932 L 588 932 L 588 1290" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-auth" data-b="st-pg" />
                        <path d="M 600 574 L 600 950 L 612 950 L 612 1290" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-clip" data-b="st-pg" />
                        <path d="M 1320 562 L 1364 562 L 1364 912 L 2086 912 L 2086 1345 L 2110 1345" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-clip" data-b="st-rd" />
                        <path d="M 1490 562 L 1466 562 L 1466 1212 L 834 1212 L 834 1345 L 810 1345" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-chat" data-b="st-pg" />
                        <path d="M 1520 574 L 1520 914 L 1520 914 L 1520 1290" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-chat" data-b="st-s3" />
                        <path d="M 2130 561 L 2066 561 L 2066 1244 L 1824 1244 L 1824 1345 L 1800 1345" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-media" data-b="st-s3" />
                        <path d="M 2300 574 L 2300 896 L 2300 896 L 2300 1290" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-media" data-b="st-rd" />
                        <path d="M 1418 1092 L 1442 1092 L 1442 1150 L 1216 1150 L 1216 1333 L 1240 1333" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-render" data-b="st-s3" />
                        <path d="M 892 1092 L 916 1092 L 916 1180 L 1196 1180 L 1196 1357 L 1240 1357" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-ai" data-b="st-s3" />
                        <path d="M 1118 1012 L 1136 1012 L 1136 522 L 1320 522" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-render" data-b="sv-clip" />
                        <path d="M 880 1000 L 880 733 L 940 733 L 940 574" fill="none" stroke="#8f8f8f" strokeWidth="1" markerEnd="url(#ar)" data-a="sv-ai" data-b="sv-clip" />
                        <path d="M 2130 483 L 2041 483 L 2041 802 L 1820 802" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="sv-media" data-b="q-evt" />
                        <path d="M 1760 760 L 1760 667 L 1760 667 L 1760 574" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="q-evt" data-b="sv-chat" />
                        <path d="M 1560 772 L 1536 772 L 1536 648 L 1384 648 L 1384 542.8 L 1320 542.8" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="q-evt" data-b="sv-clip" />
                        <path d="M 1010 574 L 1010 685 L 1010 685 L 1010 760" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="sv-clip" data-b="q-render" />
                        <path d="M 1088 844 L 1088 886 L 1256 886 L 1256 1000" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="q-render" data-b="sv-render" />
                        <path d="M 740 574 L 740 649 L 740 649 L 740 760" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="sv-clip" data-b="q-ai" />
                        <path d="M 772 844 L 772 976 L 772 976 L 772 1000" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="q-ai" data-b="sv-ai" />
                        <path d="M 1240 574 L 1240 703 L 1240 703 L 1240 760" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="sv-clip" data-b="q-upload" />
                        <path d="M 1268 844 L 1268 868 L 1280 868 L 1280 1000" fill="none" stroke="#8f8f8f" strokeWidth="1" strokeDasharray="5 4" markerEnd="url(#ar)" data-a="q-upload" data-b="sv-render" />
                      </svg>
                      {" "}
                    </div>
                  </div>
                </div>
              </div>
              <p className="block mt-[0.7rem] text-color-005 text-[0.8125rem] leading-[1.375rem]" data-cid="n135">
                박스를 클릭하면 화살표로 연결된 요소들이 떠오르며 강조됩니다 — 빈 곳이나 같은 박스를 다시 클릭하면 해제.
              </p>
            </section>
          </div>
        </main>
        <footer className="border-t border-solid border-t-border block bg-surface" data-cid="n136">
          <div className="block max-w-295 mx-auto pt-[2.2rem] pb-12 px-10 text-muted-foreground text-[0.9375rem] leading-[1.5rem] max-md:px-[1.0875rem] md:max-lg:px-[1.7rem]" data-cid="n137">
            <p className="h-[24.3px] block max-md:h-[3.0375rem]" data-cid="n138">
              <strong className="inline font-bold" data-cid="n139">
                PokeClip
              </strong>
              {" — 스트리밍 하이라이트·클립 자동화 서비스의 아키텍처 산출물."}
            </p>
          </div>
        </footer>
      </div>
      {" "}
    </>
  );
}
