import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", ariacurrent: "page", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-07-21" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "지도 SDK를 왜 네이버로 바꾸나?" },
    { text: "백엔드는 뭘 바꿔야 하나? (답: 없음)" },
    { text: "네이버 신규 Maps 상품에서 주의할 점은 (레거시와 차이)?" },
    { text: "무료 한도와 과금 방지책은?" },
    { text: "네이버에 키워드 검색이 없는데 괜찮은 이유는?" },
    { text: "구글 지도를 기각한 이유는?" },
    { text: "FE 연동에 필요한 값과 함정은?" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n31"],
    ["n32"],
    ["n33"],
    ["n34"],
    ["n35"],
    ["n36"],
    ["n37"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/adr">
              ← 설계 결정 기록
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              ADR — 지도 SDK를 카카오에서 네이버로 전환
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="block mt-[14.5px] text-muted-foreground" data-cid="n28">
                웹 지도 SDK를 카카오→네이버로 전환 (상태: 제안됨 — 규호·멘토 확인 필요). 영향은 FE 전용, 백엔드 변경 0 (격자 양자화는 SDK 무관). 이유: ① 카카오는 베이스맵 POI를 끌 수 없어 “노이즈 최소화” UI 정책과 충돌, 네이버 Style Editor는 symbol visibility OFF 가능 ② 카카오 RN 공식 SDK 부재(래퍼 1년 방치) — 앱 로드맵과 충돌 ③ 네이버 무료 월 600만 건(구글의 600배), 한도 설정으로 과금 차단 가능. 주의: 신규 Maps 상품은 호스트 oapi.map.naver.com + ncpKeyId (레거시 예제 그대로 쓰면 인증 실패). 네이버엔 키워드 검색이 없지만 행정동 검색은 우리 DB로 완결. 카카오 OAuth 로그인은 유지.
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n29" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n30">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n38" data-component="heading" id="맥락">
              맥락
            </h2>
            {" "}
            <p className="block my-4 text-muted-foreground" data-cid="n39">
              카카오맵 웹 SDK 사용 중. 문제: ① POI/라벨 끄기·다크모드 불가 — glossary의 “시각적 노이즈 최소화” 정책과 도구 충돌 ② RN 공식 SDK 없음(웹 출시 후 RN 앱 계획과 충돌). 네이버는 2025년 Maps 독립 상품으로 개편 — 신규 가입은 자동으로 신규 Maps(레거시 신청 차단).
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n40" data-component="heading" id="선택지">
              선택지
            </h2>
            {" "}
            <p className="block my-4 text-muted-foreground" data-cid="n41">
              ① 카카오 유지 ② 네이버 ③ 구글.
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n42" data-component="heading" id="결정">
              결정
            </h2>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-49" data-cid="n43">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n44">
                ② 네이버.
              </strong>
              {" Style Editor(10개 카테고리 visibility, symbol 전체 OFF 가능, Style ID를 웹·앱 공유) + 한국 지도 품질 유지 + 월 600만 무료(카운팅도 로딩 시 1건). 구글은 무료 1만 maploads(100명×3회/일이면 소진, 성장 시나리오 월 $980)·한국 품질 미검증·웹/RN 스타일 이원화로 기각."}
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n45" data-component="heading" id="근거">
              근거
            </h2>
            {" "}
            <p className="h-14 block my-4 text-muted-foreground max-md:h-35 md:max-lg:h-21" data-cid="n46">
              {"카카오 탈출은 앱 로드맵상 어차피 필요 · 네이버는 카카오 장점(품질·무료) 유지 · 검색은 SDK 무관(행정동은 regions+PostGIS로 완결, "}
              <a className="inline text-primary underline cursor-pointer" data-cid="n47" data-component="link" href="/adr/adr-EA-B2-A9-EC-9E-90-ED-91-9C-EC-8B-9C-EB-AA-85-zone">
                ADR 격자 표시명 zone
              </a>
              의 자체 zones가 랜드마크 검색도 해결).
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n48" data-component="heading" id="영향">
              영향
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n49">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n50">
                {"FE 연동: Client ID만 전달(Secret 금지), "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n51">
                  oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=
                </code>
                , Dynamic Map만 등록, Web 서비스 URL에 로컬 origin 필수.
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n52">
                후속: 한도 설정(600만) · 운영 계정 결정(무료는 계정 단위, 대표 계정 자동 지정) · Style ID 제작 · 웹 PoC · RN 2.4.x PoC.
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n53">
                재검토 트리거: 랜드마크를 외부 API 의존으로 결정하면 카카오 Local API 재평가(현재 zone 자체 보유로 무관) · RN 라이브러리(1인 메인테이너) 막히면 재검토 · 구글 한국 품질 개선 시.
              </li>
            </ul>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n54">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n55">
          <strong className="inline text-muted-foreground font-bold" data-cid="n56">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
