import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", ariacurrent: "page", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-07-21" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "현재 14개 테이블 구조와 관계는?" },
    { text: "MVP를 막는 스키마 변경 항목은 뭐고 어떤 순서로 정해야 하나?" },
    { text: "격자와 행정동 경계가 걸칠 때 어떻게 귀속하기로 제안됐나?" },
    { text: "신고 기능에 스키마 변경이 필요한가? (답: 불필요 — enum·status 이미 존재)" },
    { text: "regions.total_grid_count와 region_stats.total_count 중 정본은?" },
    { text: "Phase 2로 미뤄도 되는 항목은?" }
];
const ListRow3_data = [
    { text: "D. 게임화", text2: ": D-1 스트릭 갱신 주체(KST 주의) · D-2 뱃지 시딩+JSONB 포맷 · D-3 지급 주체(P2)." },
    { text: "E. Social/알림", text2: ": 전부 P2 (초대코드·친구 도감·알림 설정·이력)." },
    { text: "F. Auth/Moderation", text2: ": F-1 Redis+Refresh · F-2 블랙리스트 영속화 · F-3 신고는 API만." }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n32"],
    ["n33"],
    ["n34"],
    ["n35"],
    ["n36"],
    ["n37"]
];
const ListRow3_cids: string[][] = [
    ["n47", "n48"],
    ["n49", "n50"],
    ["n51", "n52"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];
const ListRow3_styles = [
    { className: "max-md:h-21" },
    { className: "max-md:h-14" },
    { className: "max-md:h-14" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/research">
              ← 연구 노트
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              ERD 정렬 — 디자인 기준 데이터모델 결정 (현재 스키마 + 변경 집약)
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="h-[152.3px] block mt-[14.5px] text-muted-foreground max-md:h-[355.3px]" data-cid="n28">
                현재 스키마(V1__init.sql 14개 테이블, users가 허브·reports만 CASCADE 예외)와 디자인 실현에 필요한 스키마 변경을 한곳에 집약한 팀 합의용 문서 — 결정을 대신하지 않음. MVP를 막는 스키마 변경: Apple provider(A-2)·계정 소프트 삭제(A-1)·닉네임 길이(A-3)·zones(C-1)·regions 시딩(C-2)·
                <strong className="inline text-foreground [font-weight:650]" data-cid="n29">
                  격자↔행정동 경계 귀속 = 격자 중심점 규칙(C-5, 핵심)
                </strong>
                ·카운트 정본(C-3)·뱃지 마스터(D-2)·스트릭 갱신(D-1). 스키마 그대로 가능: 공개범위(B-1)·신고(F-3, enum 이미 있음)·grid_color 매핑. 인프라 선행: Redis(F-1·F-2). 확정되면 V2 마이그레이션 하나로 묶는다.
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n30" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n31">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n38" data-component="heading" id="발견-변경-집약">
              발견 (변경 집약)
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n39">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n40">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n41">
                  A. users
                </strong>
                : A-1 계정 삭제 막힘(reports FK) → soft delete 권장 · A-2 Apple CHECK 추가 · A-3 닉네임 20 vs 50 · A-4 닉네임 UNIQUE(P2) · A-5 grid_color 엔티티 매핑 누락.
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n42">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n43">
                  B. videos
                </strong>
                : B-1 공개범위 API 부재(전 영상 비공개 상태, MVP) · B-2 태그 컬럼 전무(P2?) · B-3 like_count 비정규화(P2) · B-4 AI 결과 저장 스키마 미설계.
              </li>
              <li className="h-28 list-item my-[0.3rem] text-muted-foreground max-md:h-63" data-cid="n44">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n45">
                  C. 지역/표시명
                </strong>
                {": C-1 zones 신설 · C-2 GeoJSON 시딩(전국/서울 결정) · "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n46">
                  C-5 경계 귀속 — 격자 대표 동 = ST_Contains(boundary, center_geom), 오차 ≤ ~50m, videos.region_code는 “실제 찍은 동” 기록으로 역할 분리, 저장은 grids.region_code 시딩 1회 vs 조회 시 계산 택1
                </strong>
                {" · C-3 카운트 정본(C-5 선행) · C-4 집계 레벨(행정동 vs 시/도)."}
              </li>
              {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n53" data-component="heading" id="시사점">
              시사점
            </h2>
            {" "}
            <p className="block my-4 text-muted-foreground" data-cid="n54">
              팀 회의에서 🔧 항목부터 “간다/안 간다” 확정 → V2__*.sql 하나로 묶기 → 이 문서를 “확정 ERD”로 승격.
            </p>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n55">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n56">
          <strong className="inline text-muted-foreground font-bold" data-cid="n57">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
