import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", ariacurrent: "page", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-07-21" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "축제 데이터는 어디서 구했고 어떤 필드가 있나?" },
    { text: "축제를 격자에 매핑할 좌표 정보가 있나? (있음 — 위도/경도)" },
    { text: "데이터 규모와 기준일은?" }
];
const ListRow2_data2 = [
    { text: "위도/경도 → FillMap 격자 ID 양자화로 “축제 격자” 지정 가능." },
    { text: "시작/종료일자 → 기간 한정 이벤트 노출." },
    { text: "상세 판단·범위는 설계검토 미션·이벤트 기능 추가 참고." }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n31"],
    ["n32"],
    ["n33"]
];
const ListRow2_cids2: string[][] = [
    ["n43"],
    ["n44"],
    ["n45"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/research">
              ← 연구 노트
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              전국문화축제표준데이터 데이터셋
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="block mt-[14.5px] text-muted-foreground" data-cid="n28">
                공공데이터포털의 전국 문화축제 표준데이터 (약 1,300행, CSV+JSON 동일 내용, CSV는 EUC-KR 인코딩). 축제명·개최장소·시작/종료일·내용·주최기관·위도/경도·데이터기준일자(2026-06-16, 한국관광공사 제공) 포함 — 좌표가 있어 격자 매핑에 바로 사용 가능. 설계검토 미션·이벤트 기능 추가에서 축제 이벤트를 격자 위에 올리는 검증에 쓰인 그 데이터.
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n29" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n30">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n34">
                {"CSV가 깨져 보이는 이유는? (EUC-KR — "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n35">
                  iconv -f euc-kr -t utf-8
                </code>
                로 변환)
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n36" data-component="heading" id="필드">
              필드
            </h2>
            {" "}
            <p className="h-14 block my-4 text-muted-foreground max-md:h-35" data-cid="n37">
              {"축제명 · 개최장소 · 축제시작일자 · 축제종료일자 · 축제내용 · 주관/주최/후원기관명 · 전화번호 · 홈페이지주소 · 소재지도로명/지번주소 · "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n38">
                위도 · 경도
              </strong>
              {" · 데이터기준일자 · 제공기관코드/명"}
            </p>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground max-md:h-14" data-cid="n39">
              {"예시 행: "}
              <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n40">
                구미라면축제, 구미역 일원, 2026-11-06~08, ..., 36.12940328, 128.331413
              </code>
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n41" data-component="heading" id="활용-미션이벤트-기능">
              활용 (미션·이벤트 기능)
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n42">
              {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids2[i]} />)}
            </ul>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n46">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n47">
          <strong className="inline text-muted-foreground font-bold" data-cid="n48">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
