import "./ditto.css";
import NavLink from "./components/nav-link";
import Tile from "./components/tile";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", ariacurrent: "page", label: " 구현 현황 " }
];
const Tile_data = [
    { text: "언어", text2: "Java 21 (toolchain)" },
    { text: "프레임워크", text2: "Spring Boot 4.1.0 (Web MVC, Data JPA, Validation, Security)" },
    { text: "DB", text2: "PostgreSQL 16 + PostGIS 3.4" },
    { text: "공간", text2: "Hibernate Spatial" }
];
const Tile_data2 = [
    { text: "인증", text2: "Spring Security + JJWT 0.13.0 + OAuth2 Resource Server (OIDC ID Token 검증)" },
    { text: "빌드", text2: "Gradle (wrapper)" },
    { text: "로컬 인프라", text2: "Docker Compose (postgis 컨테이너)" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const Tile_cids: string[][] = [
    ["n36", "n37", "n38"],
    ["n39", "n40", "n41"],
    ["n42", "n43", "n44"],
    ["n45", "n46", "n47"]
];
const Tile_cids2: string[][] = [
    ["n52", "n53", "n54"],
    ["n55", "n56", "n57"],
    ["n58", "n59", "n60"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" }
];
const Tile_styles = [
    { className: "h-[2.4625rem]", className2: "h-[2.4625rem]" },
    {  },
    { className: "h-[2.4625rem]", className2: "h-[2.4625rem]" },
    { className: "h-[2.4625rem]", className2: "h-[2.4625rem]" }
];
const Tile_styles2 = [
    {  },
    { className: "h-[2.4625rem]", className2: "h-[2.4625rem]" },
    {  }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/status">
              ← 구현 현황
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              프로젝트 개요 · 기술 스택
            </h1>
            {" "}
            <ul className="flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              <li className="border border-solid border-surface list-item py-[0.1875rem] px-[0.5625rem] rounded-[999px] text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[0.88px] uppercase whitespace-nowrap text-nowrap" data-cid="n22">
                출처 저장소
              </li>
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n23">
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n24" data-component="heading" id="개요">
              개요
            </h2>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-42" data-cid="n25">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n26">
                FillMap
              </strong>
              {" — 사용자가 방문한 장소를 짧은 영상(자유 길이, 최대 30초)으로 기록하고, 지도 위 약 100×100m 격자를 수집(개인 점령)하는 서비스. 확장 순서: Web → Android → iOS. 본 저장소는 백엔드(Spring Boot + PostgreSQL/PostGIS)."}
            </p>
            {" "}
            <p className="h-14 block my-4 text-muted-foreground max-md:h-21" data-cid="n27">
              {"핵심 도메인 개념은 "}
              <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n28">
                .claude/rules/glossary.md
              </code>
              {" 참조 (격자 · 개인 점령 · 전역 격자 등록 · 도감 · 방문 등)."}
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n29" data-component="heading" id="기술-스택">
              기술 스택
            </h2>
            {" "}
            <table className="h-[355.5px] block min-w-full max-w-full my-[1.05rem] overflow-auto text-sm leading-[1.5625rem] [border-collapse:collapse] [border-spacing:2px] max-md:h-[467.5px]" data-cid="n30">
              <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n31">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n32">
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n33">
                    영역
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n34">
                    사용 기술
                  </th>
                </tr>
              </thead>
              <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n35">
                {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} styles={Tile_styles[i]} />)}
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n48">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n49">
                    마이그레이션
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n50">
                    Flyway (
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n51">
                      db/migration
                    </code>
                    )
                  </td>
                </tr>
                {Tile_data2.map((d, i) => <Tile key={i} d={d} cids={Tile_cids2[i]} styles={Tile_styles2[i]} />)}
              </tbody>
            </table>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n61" data-component="heading" id="빌드--실행">
              빌드 · 실행
            </h2>
            {" "}
            <pre className="h-[7.4375rem] border border-solid border-surface block my-[13.5px] py-3.5 px-4 rounded-[10px] overflow-auto text-color-005 [font-family:monospace] text-sm leading-[1.375rem] whitespace-pre-wrap [overflow-wrap:break-word] bg-surface-9 max-md:h-52" data-cid="n62">
              <code className="inline rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace]" data-cid="n63">
                <span className="inline" data-cid="n64">
                  <span className="inline text-color-020" data-cid="n65">
                    ./gradlew
                  </span>
                  <span className="inline text-color-019" data-cid="n66">
                    {" build"}
                  </span>
                  <span className="inline text-color-021" data-cid="n67">
                    {"              # 빌드 (git hook 자동 설치 포함)"}
                  </span>
                </span>
                {"\n"}
                <span className="inline" data-cid="n68">
                  <span className="inline text-color-020" data-cid="n69">
                    ./gradlew
                  </span>
                  <span className="inline text-color-019" data-cid="n70">
                    {" build"}
                  </span>
                  <span className="inline text-clr-7" data-cid="n71">
                    {" -x"}
                  </span>
                  <span className="inline text-color-019" data-cid="n72">
                    {" test"}
                  </span>
                  <span className="inline text-color-021" data-cid="n73">
                    {"      # 테스트 제외 빌드"}
                  </span>
                </span>
                {"\n"}
                <span className="inline" data-cid="n74">
                  <span className="inline text-color-020" data-cid="n75">
                    ./gradlew
                  </span>
                  <span className="inline text-color-019" data-cid="n76">
                    {" test"}
                  </span>
                  <span className="inline text-color-021" data-cid="n77">
                    {"               # 전체 테스트 (JUnit 5 + AssertJ)"}
                  </span>
                </span>
                {"\n"}
                <span className="inline" data-cid="n78">
                  <span className="inline text-color-020" data-cid="n79">
                    ./gradlew
                  </span>
                  <span className="inline text-color-019" data-cid="n80">
                    {" bootRun"}
                  </span>
                  <span className="inline text-color-021" data-cid="n81">
                    {"            # 앱 실행 (Flyway 자동 마이그레이션)"}
                  </span>
                </span>
              </code>
            </pre>
            {" "}
            <p className="block my-4 text-muted-foreground" data-cid="n82">
              로컬 실행 절차:
            </p>
            {" "}
            <pre className="h-[74.5px] border border-solid border-surface block my-[13.5px] py-3.5 px-4 rounded-[10px] overflow-auto text-color-005 [font-family:monospace] text-sm leading-[1.375rem] whitespace-pre-wrap [overflow-wrap:break-word] bg-surface-9 max-md:h-[7.4375rem]" data-cid="n83">
              <code className="inline rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace]" data-cid="n84">
                <span className="inline" data-cid="n85">
                  <span className="inline text-color-020" data-cid="n86">
                    docker
                  </span>
                  <span className="inline text-color-019" data-cid="n87">
                    {" compose"}
                  </span>
                  <span className="inline text-color-019" data-cid="n88">
                    {" up"}
                  </span>
                  <span className="inline text-clr-7" data-cid="n89">
                    {" -d"}
                  </span>
                  <span className="inline text-color-021" data-cid="n90">
                    {"         # PostGIS 컨테이너 기동 (fillmap DB)"}
                  </span>
                </span>
                {"\n"}
                <span className="inline" data-cid="n91">
                  <span className="inline text-color-020" data-cid="n92">
                    ./gradlew
                  </span>
                  <span className="inline text-color-019" data-cid="n93">
                    {" bootRun"}
                  </span>
                  <span className="inline text-color-021" data-cid="n94">
                    {"            # http://localhost:8080"}
                  </span>
                </span>
              </code>
            </pre>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n95">
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n96">
                {"앱 포트: "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n97">
                  8080
                </code>
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n98">
                {"활성 프로파일: "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n99">
                  local
                </code>
                {" (기본, "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n100">
                  application.yml
                </code>
                )
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n101">
                {"패키지 구조 · 오너십 · 로컬 DB 상세: "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n102">
                  .claude/docs/infrastructure.md
                </code>
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n103" data-component="heading" id="설정--시크릿">
              설정 · 시크릿
            </h2>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground max-md:h-14" data-cid="n104">
              {"프로파일별 설정은 "}
              <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n105">
                src/main/resources/application*.yml
              </code>
              .
            </p>
            {" "}
            <table className="h-[9.9125rem] block min-w-full max-w-full my-[1.05rem] overflow-auto text-sm leading-[1.5625rem] [border-collapse:collapse] [border-spacing:2px] max-md:h-[270.5px]" data-cid="n106">
              <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n107">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n108">
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n109">
                    값
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n110">
                    local
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n111">
                    운영(prod)
                  </th>
                </tr>
              </thead>
              <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n112">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n113">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n114">
                    DB 접속
                  </td>
                  <td className="h-[2.4625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[5.2625rem]" data-cid="n115">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n116">
                      application-local.yml
                    </code>
                    {" (Docker)"}
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n117">
                    RDS + 환경변수
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n118">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n119">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n120">
                      jwt.secret
                    </code>
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n121">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n122">
                      application-local.yml
                    </code>
                  </td>
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n123">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n124">
                      JWT_SECRET
                    </code>
                    {" 환경변수"}
                  </td>
                </tr>
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n125">
                  <td className="border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px]" data-cid="n126">
                    {"카카오 "}
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n127">
                      client-id
                    </code>
                  </td>
                  <td className="h-[2.4625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[5.2625rem]" data-cid="n128">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n129">
                      application-local.yml
                    </code>
                  </td>
                  <td className="h-[2.4625rem] border border-solid border-surface table-cell py-2 px-3 align-top leading-[1.375rem] text-left [border-collapse:collapse] [border-spacing:2px] max-md:h-[5.2625rem]" data-cid="n130">
                    <code className="inline py-[1.7px] px-[0.3rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.1875rem] bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n131">
                      KAKAO_CLIENT_ID
                    </code>
                    {" 환경변수"}
                  </td>
                </tr>
              </tbody>
            </table>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n132">
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground" data-cid="n133">
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n134">
                  jwt.access-token-ttl
                </code>
                {": "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n135">
                  PT1H
                </code>
                {" (공통)"}
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n136">
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n137">
                  spring.jpa.hibernate.ddl-auto
                </code>
                {": "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n138">
                  validate
                </code>
                {" (스키마는 Flyway가 소유)"}
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n139" data-component="heading" id="커밋--브랜치-규칙">
              커밋 · 브랜치 규칙
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n140">
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n141">
                {"커밋: "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n142">
                  {"MSG-{번호} {타입}: {요약}"}
                </code>
                {" (git hook 강제, "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n143">
                  core.hooksPath=.githooks
                </code>
                )
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n144">
                {"브랜치: "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n145">
                  {"feature|fix|refactor|chore/MSG-{번호}/{설명}"}
                </code>
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n146">
                {"상세 컨벤션: "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n147">
                  .claude/rules/project-conventions.md
                </code>
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n148" data-component="heading" id="배포">
              배포
            </h2>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground max-md:h-14" data-cid="n149">
              {"환경 분리(local/dev/prod) 및 AWS 아키텍처 로드맵: "}
              <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n150">
                .claude/docs/deploy.md
              </code>
            </p>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n151">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n152">
          <strong className="inline text-muted-foreground font-bold" data-cid="n153">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
