import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import Tile from "./components/tile";
import ListRow3 from "./components/list-row3";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", ariacurrent: "page", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-08-01" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "MSG-234가 왜 멈춰 있었고 어떻게 풀렸나?" },
    { text: "zone 초안 데이터는 어디서 와서 어떻게 변환되나?" },
    { text: "실제로 초안 몇 건이 나왔고 남은 사람 작업은 뭔가?" },
    { text: "왜 카카오 API로는 상권 범위를 못 만드나?" },
    { text: "공공데이터 상권 경계의 한계(공백 지역·이름 품질)는?" },
    { text: "좌표계(CRS) 문제는 어떻게 종결됐나?" }
];
const Tile_data = [
    { text: "데이터 확보", text2: "✅ 주요상권현황 CSV(전국 1,227, 위경도 원본) + 소상공인365 회식상권 SHP(904)" },
    { text: "라이선스", text2: "✅ 이용허락범위 제한 없음 — DB 저장 가능" },
    { text: "커버리지", text2: "✅ 서면·전포·홍대·강남·성수 확인 · ⚠️ 광안리·해운대 없음" },
    { text: "변환", text2: "✅ 서울 176 + 부산 55 = 231건 · 26행 캡 초과 0건" },
    { text: "좌표계", text2: "✅ 위경도 원본 + 5181 교차 검증 일치(오차 ~9m) — CRS 종결" }
];
const ListRow3_data = [
    { text: "순수 수동 작도", text2: " — 며칠 소요, 경계 근거 자의적. 지금 방식의 열화판" },
    { text: "AI 좌표 생성", text2: " — 환각 위험, 공공 실측 데이터에 열위" },
    { text: "행정동 이름으로 버티기", text2: " — 디자인 ver 6의 “서면 A-14” 표기 불가, 보류 연장일 뿐" },
    { text: "카카오 로컬 API를 초안 소스로", text2: " — 범위 정보 없음(점만 반환) + 저장 즉시 약관 위반(데브톡 150397). 검색(점 좌표)은 MSG-251 카카오, 범위 저장은 공공데이터로 역할 분리" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n35"],
    ["n36"],
    ["n37"],
    ["n38"],
    ["n39"],
    ["n40"]
];
const Tile_cids: string[][] = [
    ["n67", "n68", "n69"],
    ["n70", "n71", "n72"],
    ["n73", "n74", "n75"],
    ["n76", "n77", "n78"],
    ["n79", "n80", "n81"]
];
const ListRow3_cids: string[][] = [
    ["n84", "n85"],
    ["n86", "n87"],
    ["n88", "n89"],
    ["n90", "n91"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];
const ListRow3_styles = [
    { className: "h-7 max-md:h-14" },
    { className: "h-7 max-md:h-14" },
    { className: "h-7 max-md:h-14" },
    { className: "h-14 max-md:h-35" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/adr">
              ← 설계 결정 기록
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              MSG-234 상권 작도 결정 — 그리지 않고, 그려진 것을 검수한다
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="h-[11.1rem] block mt-[14.5px] text-muted-foreground max-md:h-[26.9625rem]" data-cid="n28">
                {"“서면 A-14” 격자 이름표(MSG-234)의 블로커였던 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n29">
                  상권 30~50개 범위 작도
                </strong>
                {"를 해결: 사람이 며칠간 그리는 대신, "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n30">
                  소상공인시장진흥공단 공공데이터(상권 경계)를 자동 변환해 초안을 만들고 사람은 검수만
                </strong>
                {" 한다(팀 분담 1~2시간). 실증 완료(7/28): 주요상권현황 CSV(1,227상권, 위경도 원본) + 회식상권 SHP(EPSG:5181 교차 검증)로 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n31">
                  서울 176 + 부산 55 = 초안 231건 자동 생성
                </strong>
                {", 라이선스 제한 없음, 26행 캡 초과 0건. → "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n32">
                  MSG-234 보류 해제, WIP 브랜치 재개
                </strong>
                (V8__zones.sql). 한계: 이름이 역 출구 단위로 잘게 쪼개짐(통명화는 사람 몫) · 광안리·해운대 등 해변 관광 상권 공백(검수 때 소수 수동 추가) · 폴리곤→사각형 근사. 카카오 API는 원천 불가(범위 정보 없음 + 저장 즉시 약관 위반).
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n33" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n34">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n41" data-component="heading" id="맥락">
              맥락
            </h2>
            {" "}
            <p className="h-21 block my-4 text-muted-foreground max-md:h-49" data-cid="n42">
              <a className="inline text-primary underline cursor-pointer" data-cid="n43" data-component="link" href="/adr/adr-EA-B2-A9-EC-9E-90-ED-91-9C-EC-8B-9C-EB-AA-85-zone">
                ADR 격자 표시명 zone
              </a>
              {"이 확정한 “서면 A-14” 체계는 코드 완성(테스트 36건, WIP 브랜치 보존) 상태였지만, zones 데이터 0행 — “서면이 어디까지인가”는 좌표 공식이 아니라 사람의 지역 지식이라 "}
              <strong className="inline text-foreground [font-weight:650]" data-cid="n44">
                누가 30~50개를 그리나
              </strong>
              가 미확정으로 보류됨(7/23 MSG-167 후속에서 보류 확인).
            </p>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n45" data-component="heading" id="결정">
              결정
            </h2>
            {" "}
            <p className="h-7 block my-4 text-muted-foreground max-md:h-14" data-cid="n46">
              <strong className="inline text-foreground [font-weight:650]" data-cid="n47">
                공공데이터 초안 + 사람 검수
              </strong>
              {" (제안 문서 cf-26116098의 ③안 채택, 폴백은 수동 작도):"}
            </p>
            {" "}
            <ol className="block my-4 pl-[1.35rem] [list-style-type:decimal] list-outside" data-cid="n48">
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-35" data-cid="n49">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n50">
                  자동 초안
                </strong>
                {" ✅ — 상권 경계 폴리곤 bbox → GridEncoder 양자화("}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n51">
                  floor(lat/0.0009)
                </code>
                {", "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n52">
                  floor(lng/0.00115)
                </code>
                {") → min/max_grid_y/x. 산출물 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n53">
                  zones-draft.json
                </code>
                ·
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n54">
                  zones-draft.geojson
                </code>
                (검수용, 231건).
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n55">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n56">
                  사람 검수
                </strong>
                {" — geojson.io에 올려 30"}
                <del className="inline text-muted line-through" data-cid="n57">
                  50개 선정 + 이름 다듬기(“서면역7번 출구”→“서면”) + 경계 조정. 3인 분담 1
                </del>
                2시간.
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n58">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n59">
                  시딩
                </strong>
                {" — 확정본을 ZoneSeeder에 투입, WIP 브랜치(feature/MSG-234-zone-naming) 재개. 마이그레이션은 V8__zones.sql(V7은 MSG-238 선점)."}
              </li>
            </ol>
            {" "}
            <h3 className="block mt-[2.025rem] mb-[0.5625rem] text-lg font-bold leading-[2rem] tracking-[-0.36px]" data-cid="n60" data-component="heading" id="실증-결과-2026-07-28">
              실증 결과 (2026-07-28)
            </h3>
            {" "}
            <table className="h-[237.3px] block min-w-full max-w-full my-[1.05rem] overflow-auto text-sm leading-[1.5625rem] [border-collapse:collapse] [border-spacing:2px] max-md:h-[371.7px]" data-cid="n61">
              <thead className="table-header-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n62">
                <tr className="table-row align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n63">
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n64">
                    확인
                  </th>
                  <th className="border border-solid border-surface table-cell py-2 px-3 align-top [font-weight:650] leading-[1.375rem] text-left whitespace-nowrap text-nowrap bg-surface-2 [border-collapse:collapse] [border-spacing:2px]" data-cid="n65">
                    결과
                  </th>
                </tr>
              </thead>
              <tbody className="table-row-group align-middle [border-collapse:collapse] [border-spacing:2px]" data-cid="n66">
                {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} />)}
              </tbody>
            </table>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n82" data-component="heading" id="기각된-대안">
              기각된 대안
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n83">
              {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n92" data-component="heading" id="영향남은-일">
              영향·남은 일
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n93">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n94">
                <a className="inline text-primary underline cursor-pointer" data-cid="n95" data-component="link" href="/adr/adr-EA-B2-A9-EC-9E-90-ED-91-9C-EC-8B-9C-EB-AA-85-zone">
                  ADR 격자 표시명 zone
                </a>
                의 “MSG-234 보류” 상태 해제 — FE 행정동 폴백 전제도 zone 시딩 후 표시명으로 승격 예정
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n96">
                스크럼 안건: 검수 분담 · 광안리·해운대 수동 보강(한 자릿수) · 검수 후 MSG-234 종결
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n97">
                데이터 최신성: 주요상권현황 2024-01 기준 — 연 1회 재수집이면 충분
              </li>
              <li className="h-28 list-item my-[0.3rem] text-muted-foreground max-md:h-56" data-cid="n98">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n99">
                  후속 (2026-07-30/31, MSG-259)
                </strong>
                {": 기계장치는 develop 머지 완료, 데이터 롤아웃은 MSG-259로 이관 — 초안 233건(해변 갭필 2 추가)·후보 29곳(공공 17+수동 12) validate PASS, 검수 규칙 4·검증 3층 확정(PR BE#76). 정본 "}
                <a className="inline text-primary underline cursor-pointer" data-cid="n100" data-component="link" href="/research/zone-ED-91-9C-EC-8B-9C-EB-AA-85-EB-8D-B0-EC-9D-B4-ED-84-B0-ED-8C-8C-EC-9D-B4-ED-94-84-EB-9D-BC-EC-9D-B8-ED-95-B4-EC-84-A4">
                  zone 표시명 데이터 파이프라인 해설
                </a>
                {" · 공공데이터 근거 "}
                <a className="inline text-primary underline cursor-pointer" data-cid="n101" data-component="link" href="/research/zone-EC-83-81-EA-B6-8C-EA-B3-B5-EA-B3-B5-EB-8D-B0-EC-9D-B4-ED-84-B0-EA-B7-BC-EA-B1-B0">
                  zone 상권 공공데이터 근거
                </a>
              </li>
            </ul>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n102">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n103">
          <strong className="inline text-muted-foreground font-bold" data-cid="n104">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
