import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", ariacurrent: "page", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-07-22" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "격자의 행정동 이름은 어디에 저장하고 언제 판정하나? (grids.region_code, lazy insert 시 1회)" },
    { text: "왜 user_grids가 아니라 grids에 저장하나? (함수 종속·중복)" },
    { text: "MSG-155에서 폐기한 안을 왜 다시 채택해도 모순이 아닌가?" },
    { text: "목록 라벨 조인 비용은 얼마고 어떤 대안을 기각했나? (MSG-164 실측 근거)" },
    { text: "격자 클릭 → 동 단위 내 영상 모아보기는 어떤 축으로 귀속되나? (격자 중심점)" },
    { text: "region_stats를 라이브 집계로 바꾸지 않은 이유는? (검증된 코드 churn + 156 계약 의미 변화)" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n39"],
    ["n40"],
    ["n41"],
    ["n42"],
    ["n43"],
    ["n44"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/adr">
              ← 설계 결정 기록
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              ADR 격자 행정동 라벨 — grids.region_code 저장 (MSG-167)
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="h-[12.6875rem] block mt-[14.5px] text-muted-foreground max-md:h-[28.55rem]" data-cid="n28">
                {"도감 갤러리 30개 셀에 행정동 이름(“역삼1동”)을 붙이기 위해 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n29">
                  {"격자의 행정동을 "}
                  <code className="inline py-[1.7px] px-[0.3125rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.375rem] bg-surface-2" data-cid="n30">
                    grids.region_code
                  </code>
                  {" 컬럼(V4, nullable FK)에 저장"}
                </strong>
                {"하기로 확정 (2026-07-22, 팀원 K). 핵심 논리: ① 행정동은 격자 중심점만으로 정해지는 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n31">
                  격자 자체의 속성
                </strong>
                {"(함수 종속 "}
                <code className="inline py-[1.7px] px-[0.3125rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.375rem] bg-surface-2" data-cid="n32">
                  grid_id → region_code
                </code>
                {") — user_grids에 두면 점령자 수만큼 중복 ② MSG-155 때 폐기했던 안의 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n33">
                  정당한 부활
                </strong>
                {"(당시엔 쓰기 경로뿐이라 저장 불필요 → 지금은 조회 경로 요구 발생, “조회 경로 geospatial 금지” ADR상 저장 필수) ③ 조회는 PK equi-join 2개 ≈0.4~0.5ms(MSG-164 실측) — 비정규화·조회 시 ST_Covers 안 기각. "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n34">
                  같은 티켓에 동 단위 내 영상 조회 API 신설
                </strong>
                {"(예: "}
                <code className="inline py-[1.7px] px-[0.3125rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.375rem] bg-surface-2" data-cid="n35">
                  GET /api/collections/videos?regionCode=
                </code>
                {") — 귀속 축은 영상 GPS가 아니라 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n36">
                  격자 중심점
                </strong>
                이라 탐험률과 어긋날 수 없음. region_stats 라이브 집계 전환은 백로그 보류.
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n37" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n38">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n45" data-component="heading" id="결정-요약">
              결정 요약
            </h2>
            {" "}
            <ol className="block my-4 pl-[1.35rem] [list-style-type:decimal] list-outside" data-cid="n46">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-35 md:max-lg:h-21" data-cid="n47">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n48">
                  저장 위치
                </strong>
                {": "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n49">
                  grids.region_code VARCHAR(10) NULL REFERENCES regions(region_code)
                </code>
                {" (V4 마이그레이션) — 격자당 1회, lazy insert 시 ST_Covers 판정(격자 생애 1회), 기존 격자는 멱등 백필."}
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-35 md:max-lg:h-21" data-cid="n50">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n51">
                  판정 규칙 통일
                </strong>
                {": 격자 중심점 ST_Covers + "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n52">
                  ORDER BY region_code LIMIT 1
                </code>
                {" — MSG-93/155/153과 동일해 목록 라벨·동 단위 영상·클릭 탐험률(by-grid) 귀속이 항상 일치. 무귀속(해안)은 NULL."}
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n53">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n54">
                  조회 방식
                </strong>
                : grids+regions PK equi-join 2개(≈0.4~0.5ms/요청, geospatial 0) 채택. region_name 비정규화(개편 시 이중 갱신 리스크), 조회 시 ST_Covers(ADR 위반) 기각.
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n55">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n56">
                  동 단위 내 영상 조회 신설
                </strong>
                {": "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n57">
                  videos ⨝ grids
                </code>
                {"에 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n58">
                  g.region_code
                </code>
                {" 필터 — FE 동선: 격자 클릭 → by-grid(동+탐험률) → 동 단위 내 영상. 내 영상만·ACTIVE·최신순."}
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n59">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n60">
                  보류
                </strong>
                : region_stats → 라이브 집계 전환은 백로그 (착수 조건: 운영 부담 발생 or 156 계약 변경 시).
              </li>
            </ol>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n61" data-component="heading" id="시사점">
              시사점
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n62">
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-35" data-cid="n63">
                <a className="inline text-primary underline cursor-pointer" data-cid="n64" data-component="link" href="/spec/EA-B0-9C-EC-9D-B8-EB-8F-84-EA-B0-90-ED-99-94-EB-A9-B4-ED-99-95-EC-A0-95-ux-api-EC-84-A4-EA-B3-84">
                  FillMap API 스펙 통합
                </a>
                {" 갱신 대상: "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n65">
                  GET /api/regions/stats/by-grid
                </code>
                (격자 클릭 응답 — MSG-153 스펙에서 확정된 신규 경로)와 동 단위 내 영상 API(MSG-167 예정)가 현재 통합 명세판에 없음.
              </li>
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n66">
                MSG-153의 쟁점 ②(행정동 표기 축)가 이 결정으로 종결 — 격자 중심점 축으로 통일.
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-14" data-cid="n67">
                {"갤러리 목록 응답에 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n68">
                  regionName
                </code>
                (nullable) 필드 추가 예정.
              </li>
            </ul>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n69">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n70">
          <strong className="inline text-muted-foreground font-bold" data-cid="n71">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
