import "./ditto.css";
import NavLink from "./components/nav-link";
import FeatureCard from "./components/feature-card";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", ariacurrent: "page", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const FeatureCard_data = [
    { title: "PostgreSQL + PostGIS", description: "격자·점령·영상 메타·구역·행정동 통계. 무결성은 DB가 소유하고 JPA는 검증만 합니다." },
    { title: "Redis", description: "핫구역 6시간 버킷 집계, 조회 캐시, 분산 락. 유실을 허용하는 근사값 계층입니다." },
    { title: "S3", description: "원본 영상과 변환 결과. 업로드는 presigned URL로 서버를 거치지 않습니다." }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const FeatureCard_cids: string[][] = [
    ["n41", "n42", "n43"],
    ["n44", "n45", "n46"],
    ["n47", "n48", "n49"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <p className="flex mb-3.5 items-center gap-2.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.92px] uppercase before:content-[''] before:block before:w-[0.4375rem] before:h-[0.4375rem] before:bg-primary before:rounded-tl-[50%]" data-cid="n19">
              DATA FLOW
            </p>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              데이터 플로우
            </h1>
            {" "}
            <p className="w-full max-w-[37.175rem] block mt-3.5 text-muted-foreground" data-cid="n21">
              {" 한 번의 업로드와 한 번의 재생이 서버 안에서 어떤 순서로 흐르는지. 요청 하나가 지나는 계층과 그때 남는 데이터를 따라갑니다. "}
            </p>
            {" "}
          </div>
          {" "}
          <div className="border-t border-solid border-t-surface block mb-24 max-md:mb-14 md:max-lg:mb-[69.1px]" data-cid="n22">
            <a className="border-b border-solid border-b-surface-2 grid py-[1.0625rem] px-2 items-center gap-4 grid-rows-[31.5px] cursor-pointer grid-cols-[46px_1fr_auto] max-md:grid-cols-[34px_269px] max-md:grid-rows-[56px_27.25px]" data-cid="n23" data-component="link" href="/embeds/upload-flow.html">
              {" "}
              <span className="block min-w-0 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-lg leading-[2rem]" data-cid="n24">
                01
              </span>
              {" "}
              <span className="h-7 block min-w-0 max-md:h-14" data-cid="n25">
                {" "}
                <span className="inline [font-weight:650] tracking-[-0.24px]" data-cid="n26">
                  영상 업로드 플로우
                </span>
                {" "}
                <span className="inline mt-0.5 text-muted text-sm leading-[1.375rem]" data-cid="n27">
                  presigned URL 발급부터 점령 확정까지의 순서.
                </span>
                {" "}
              </span>
              {" "}
              <span className="flex min-w-0 justify-end items-center gap-3 text-muted text-[0.8125rem] leading-[1.4375rem] whitespace-nowrap text-nowrap max-md:col-start-2" data-cid="n28">
                {" "}
                <span className="border border-solid border-clr-1 block max-w-33 py-[0.1875rem] px-[0.5625rem] rounded-[999px] overflow-hidden text-primary [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[0.88px] uppercase bg-surface-6" data-cid="n29">
                  플로우
                </span>
                {"→ "}
              </span>
              {" "}
            </a>
            <a className="border-b border-solid border-b-surface-2 grid py-[1.0625rem] px-2 items-center gap-4 grid-rows-[31.5px] cursor-pointer grid-cols-[46px_1fr_auto] max-md:grid-cols-[34px_269px] max-md:grid-rows-[56px_27.25px]" data-cid="n30" data-component="link" href="/embeds/playback-flow.html">
              {" "}
              <span className="block min-w-0 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-lg leading-[2rem]" data-cid="n31">
                02
              </span>
              {" "}
              <span className="h-7 block min-w-0 max-md:h-14" data-cid="n32">
                {" "}
                <span className="inline [font-weight:650] tracking-[-0.24px]" data-cid="n33">
                  영상 재생 플로우
                </span>
                {" "}
                <span className="inline mt-0.5 text-muted text-sm leading-[1.375rem]" data-cid="n34">
                  공개범위 판정과 재생 URL 발급 경로.
                </span>
                {" "}
              </span>
              {" "}
              <span className="flex min-w-0 justify-end items-center gap-3 text-muted text-[0.8125rem] leading-[1.4375rem] whitespace-nowrap text-nowrap max-md:col-start-2" data-cid="n35">
                {" "}
                <span className="border border-solid border-clr-1 block max-w-33 py-[0.1875rem] px-[0.5625rem] rounded-[999px] overflow-hidden text-primary [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[0.88px] uppercase bg-surface-6" data-cid="n36">
                  플로우
                </span>
                {"→ "}
              </span>
              {" "}
            </a>
            {" "}
          </div>
          {" "}
          <div className="flex mt-18 mb-4.5 justify-between items-baseline gap-4 max-md:mt-10 md:max-lg:mt-[2.875rem]" data-cid="n37">
            <h2 className="block text-[1.3125rem] font-bold leading-[2.3125rem] tracking-[-0.42px]" data-cid="n38" data-component="heading">
              저장 구조
            </h2>
            {" "}
            <span className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] leading-[1.1875rem] tracking-[1.1px] uppercase" data-cid="n39">
              한눈에
            </span>
            {" "}
          </div>
          {" "}
          <div className="grid mb-24 gap-3.5 grid-rows-[139.5px] grid-cols-[repeat(auto-fit,_minmax(318px,_1fr))] max-md:mb-14 max-md:grid-rows-[116.438px_116.438px_116.438px] md:max-lg:mb-[69.1px] md:max-lg:grid-rows-[116.438px_116.438px]" data-cid="n40">
            {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} cids={FeatureCard_cids[i]} />)}
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n50">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n51">
          <strong className="inline text-muted-foreground font-bold" data-cid="n52">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
