import "./ditto.css";
import NavLink from "./components/nav-link";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", ariacurrent: "page", label: " 구현 현황 " }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <p className="h-[1.3125rem] flex mb-3.5 items-center gap-2.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.92px] uppercase before:content-[''] before:block before:w-[0.4375rem] before:h-[0.4375rem] before:bg-primary before:rounded-tl-[50%]" data-cid="n19">
              IMPLEMENTATION STATUS
            </p>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              구현 현황
            </h1>
            {" "}
            <p className="w-full max-w-[37.175rem] block mt-3.5 text-muted-foreground" data-cid="n21">
              지금 코드에 실제로 무엇이 있는지. 위키나 옛 명세와 어긋나면 이 문서가 이깁니다.
            </p>
            {" "}
          </div>
          {" "}
          <div className="border-t border-solid border-t-surface block mb-24 max-md:mb-14 md:max-lg:mb-[69.1px]" data-cid="n22">
            <a className="border-b border-solid border-b-surface-2 grid py-[1.0625rem] px-2 items-center gap-4 grid-rows-[31.5px] cursor-pointer grid-cols-[46px_1fr_auto] max-md:grid-cols-[34px_269px] max-md:grid-rows-[31.5px_22.75px]" data-cid="n23" data-component="link" href="/status/status">
              {" "}
              <span className="block min-w-0 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-lg leading-[2rem]" data-cid="n24">
                01
              </span>
              {" "}
              <span className="block min-w-0" data-cid="n25">
                {" "}
                <span className="inline [font-weight:650] tracking-[-0.24px]" data-cid="n26">
                  구현 현황
                </span>
                {" "}
              </span>
              {" "}
              <span className="flex min-w-0 justify-end items-center gap-3 text-muted text-[0.8125rem] leading-[1.4375rem] whitespace-nowrap text-nowrap max-md:col-start-2" data-cid="n27">
                {" → "}
              </span>
              {" "}
            </a>
            <a className="border-b border-solid border-b-surface-2 grid py-[1.0625rem] px-2 items-center gap-4 grid-rows-[31.5px] cursor-pointer grid-cols-[46px_1fr_auto] max-md:grid-cols-[34px_269px] max-md:grid-rows-[31.5px_22.75px]" data-cid="n28" data-component="link" href="/status/project">
              {" "}
              <span className="block min-w-0 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-lg leading-[2rem]" data-cid="n29">
                02
              </span>
              {" "}
              <span className="h-7 block min-w-0" data-cid="n30">
                {" "}
                <span className="inline [font-weight:650] tracking-[-0.24px]" data-cid="n31">
                  프로젝트 개요 · 기술 스택
                </span>
                {" "}
              </span>
              {" "}
              <span className="flex min-w-0 justify-end items-center gap-3 text-muted text-[0.8125rem] leading-[1.4375rem] whitespace-nowrap text-nowrap max-md:col-start-2" data-cid="n32">
                {" → "}
              </span>
              {" "}
            </a>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n33">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n34">
          <strong className="inline text-muted-foreground font-bold" data-cid="n35">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
