import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", ariacurrent: "page", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-07-21" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "AI 블러·하이라이트 서버는 지금 어떤 상태인가? (답: dev 배포 완료, BE 연동 대기)" },
    { text: "왜 AI 서버가 별도 레포인가? (AGPL)" },
    { text: "얼굴 미탐지는 어떻게 해결했나? (conf 하향, 실험표)" },
    { text: "BE는 AI 서버와 어떻게 통신하나? (jobs API 계약·상태 매핑)" },
    { text: "처리 시간은 얼마나 걸리나? (1080p 30초 ≈ 3~4분, 실측)" },
    { text: "x86 Docker 배포에서 뭘 조심해야 하나? (torch·torchvision CPU 인덱스)" }
];
const ListRow3_data = [
    { text: "모델", text2: ": 얼굴 YOLOv11n-face + 번호판 YOLOv11n-plate + PySceneDetect — 런타임 ultralytics 1벌 (MSG-144)" },
    { text: "라이선스 분리", text2: ": Ultralytics AGPL-3.0 → AI만 별도 레포(AGPL)·HTTP 통신, BE MIT 유지" },
    { text: "실측 (MSG-142)", text2: ": Graviton3 기준 1080p 30초 3.1~3.8분 / 4K 9.7분, vCPU 증설 무효 → 다운스케일이 정답" },
    { text: "얼굴 미탐지 (MSG-158)", text2: ": conf 0.05 채택 — recall 0.980, 시간 1.01×. 모델 확대·imgsz 상향은 기각" },
    { text: "하이라이트 폴백 (MSG-159)", text2: ": 장면 전환 없으면 균등 3분할" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n36"],
    ["n37"],
    ["n38"],
    ["n39"],
    ["n40"],
    ["n41"]
];
const ListRow3_cids: string[][] = [
    ["n44", "n45"],
    ["n46", "n47"],
    ["n48", "n49"],
    ["n50", "n51"],
    ["n52", "n53"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];
const ListRow3_styles = [
    { className: "h-14 max-md:h-21" },
    { className: "h-7 max-md:h-14" },
    { className: "h-14 max-md:h-21" },
    { className: "h-14 max-md:h-21" },
    { className: "h-7 max-md:h-14" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/research">
              ← 연구 노트
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              AI Highlight-Blur 개발 기록 — 레포 생성부터 dev 배포까지
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="h-[152.3px] block mt-[14.5px] text-muted-foreground max-md:h-[329.9px]" data-cid="n28">
                얼굴·번호판 자동 블러 + 하이라이트 추천 서버(ASM-MSG/AI)를 이틀 만에 측정→결정→구현→
                <strong className="inline text-foreground [font-weight:650]" data-cid="n29">
                  dev 배포 완료
                </strong>
                {". 1080p 30초 실영상 E2E 4.3분, 하이라이트 3구간. 핵심 결정: ① Ultralytics AGPL 때문에 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n30">
                  AI 서버만 별도 레포·별도 프로세스로 분리
                </strong>
                {"(BE는 MIT 유지) ② Lambda 기각·상시 FastAPI (MSG-143 ADR) ③ 얼굴 미탐지는 모델 키우기가 아니라 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n31">
                  conf 0.25→0.05 하향
                </strong>
                {"으로 해결 (recall 0.72→0.98, 시간 불변). API 계약: "}
                <code className="inline py-[1.7px] px-[0.3125rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.375rem] bg-surface-2" data-cid="n32">
                  POST /jobs
                </code>
                {" → 폴링 → "}
                <code className="inline py-[1.7px] px-[0.3125rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.375rem] bg-surface-2" data-cid="n33">
                  {"GET /jobs/{id}/video"}
                </code>
                , 상태 QUEUED→PROCESSING→DONE|FAILED. 남은 것: BE 연동·부하 테스트·S3 연동.
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n34" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n35">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n42" data-component="heading" id="요약">
              요약
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n43">
              {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} cids={ListRow3_cids[i]} styles={ListRow3_styles[i]} />)}
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n54">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n55">
                  서버 (MSG-161)
                </strong>
                {": FastAPI 단일 워커 큐, "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n56">
                  POST /jobs
                </code>
                {"→폴링→비디오 다운로드, PROCESSING = BE의 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n57">
                  BLURRING
                </code>
              </li>
              <li className="h-7 list-item my-[0.3rem] text-muted-foreground max-md:h-21" data-cid="n58">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n59">
                  배포
                </strong>
                : dev EC2(x86) Docker, E2E 통과. torch·torchvision은 CPU 전용 인덱스로 함께 설치할 것
              </li>
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n60" data-component="heading" id="시사점">
              시사점
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n61">
              <li className="list-item my-[0.3rem] text-muted-foreground" data-cid="n62">
                MSG-143 ADR의 전제(1080p 다운스케일 → 3~4분)가 E2E 실측(4.3분)으로 검증됨
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-28" data-cid="n63">
                {"PRD의 “AI 하이라이트·블러 [미구현]” 항목이 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n64">
                  서버 측 완료 → BE 연동 대기
                </strong>
                로 진전 — SA v2 다이어그램의 AI 파이프라인 행 상태 갱신 대상
              </li>
            </ul>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n65">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n66">
          <strong className="inline text-muted-foreground font-bold" data-cid="n67">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
