import "./ditto.css";
import NavLink from "./components/nav-link";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const NavLink_data = [
    { href: "/", label: " 개요 " },
    { href: "/diagrams/0", label: " 다이어그램 " },
    { href: "/spec", label: " 설계 · 명세 " },
    { href: "/prd", label: " PRD " },
    { href: "/adr", ariacurrent: "page", label: " 설계 결정 " },
    { href: "/dataflow", label: " 데이터플로우 " },
    { href: "/research", label: " 연구노트 " },
    { href: "/roles", label: " 역할분담 " },
    { href: "/status", label: " 구현 현황 " }
];
const ListRow_data = [
    { text: "유효" },
    { text: "갱신 2026-07-28" },
    { text: "출처 팀 위키" }
];
const ListRow2_data = [
    { text: "장소 검색은 어느 공급자로, 왜 카카오인가? (네이버 오픈API 대비)" },
    { text: "네이버 지도 위에 카카오 검색 결과를 표시해도 되나? (공식 근거)" },
    { text: "왜 검색 결과를 캐시하면 안 되나? (약관 조건)" },
    { text: "카카오 좌표가 우리 격자·행정동에 맞는다는 근거는? (스모크 실측)" },
    { text: "MSG-234(zone)·MSG-238(전역 탐색)과 검색의 스코프 경계는?" }
];
const NavLink_cids: string[][] = [
    ["n7"],
    ["n8"],
    ["n9"],
    ["n10"],
    ["n11"],
    ["n12"],
    ["n13"],
    ["n14"],
    ["n15"]
];
const ListRow_cids: string[][] = [
    ["n22"],
    ["n23"],
    ["n24"]
];
const ListRow2_cids: string[][] = [
    ["n36"],
    ["n37"],
    ["n38"],
    ["n39"],
    ["n40"]
];
const NavLink_styles = [
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-primary font-semibold bg-surface-6" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" },
    { className: "text-muted-foreground" }
];
const ListRow_styles = [
    { className: "border-clr-1 text-primary bg-surface-6" },
    { className: "border-surface text-muted" },
    { className: "border-surface text-muted" }
];

export default function Page() {
  return (
    <>
      <header className="h-[3.8125rem] border-b border-solid border-b-surface-2 block sticky top-0 z-40 bg-clr-0 [backdrop-filter:blur(12px)]" data-cid="n1">
        <div className="h-15 flex max-w-270 mx-auto px-12 items-center gap-6 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n2">
          <a className="h-[1.8625rem] flex items-baseline shrink-0 gap-[0.5625rem] text-[1.0625rem] font-extrabold leading-[1.875rem] tracking-[-0.34px] cursor-pointer" data-cid="n3" data-component="link" href="/">
            {" "}
            <img className="w-[1.0625rem] h-[1.0625rem] block overflow-clip aspect-[auto_17/17]" data-cid="n4" data-component="image" alt="" height="17" src="/assets/cloned/svg/1247e2bc3750.svg" width="17" />
            {" FillMap "}
            <small className="block text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.625rem] font-medium leading-[1.125rem] tracking-[1.8px]" data-cid="n5">
              DOCS
            </small>
            {" "}
          </a>
          {" "}
          <nav className="flex ml-[107.7px] gap-0.5 overflow-auto max-lg:ml-0" data-cid="n6" data-component="nav">
            {NavLink_data.map((d, i) => <NavLink key={i} d={d} cids={NavLink_cids[i]} styles={NavLink_styles[i]} />)}
            {" "}
          </nav>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <main className="block" data-cid="n16">
        <div className="block max-w-270 mx-auto px-12 max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n17">
          <div className="block pt-23 pb-10 max-md:pt-12 max-md:pb-6 md:max-lg:pt-[69.1px] md:max-lg:pb-[30.7px]" data-cid="n18">
            <a className="inline-block mb-4.5 text-muted [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-xs leading-[1.3125rem] tracking-[1.2px] uppercase cursor-pointer" data-cid="n19" data-component="link" href="/adr">
              ← 설계 결정 기록
            </a>
            {" "}
            <h1 className="block text-[2.75rem] font-extrabold leading-[3.3125rem] tracking-[-1.54px] max-md:text-3xl max-md:leading-9 max-md:tracking-[-1.05px] md:max-lg:text-[2.375rem] md:max-lg:leading-[2.875rem] md:max-lg:tracking-[-1.34px]" data-cid="n20" data-component="heading">
              ADR 장소 검색 — 카카오 로컬 프록시 (MSG-251)
            </h1>
            {" "}
            <ul className="h-[27.3px] flex mt-4.5 flex-wrap gap-2 [list-style-type:none] list-outside" data-cid="n21">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} styles={ListRow_styles[i]} />)}
            </ul>
            {" "}
          </div>
          {" "}
          <article className="w-full max-w-[44.375rem] block pb-24 max-md:pb-14 md:max-lg:pb-[69.1px]" data-cid="n25">
            <aside className="border-t border-solid border-t-surface border-r border-r-surface border-b border-b-surface border-l-[3px] border-l-primary block my-[20.3px] py-3.5 px-4.5 rounded-tr-[10px] rounded-br-[10px] text-[0.9375rem] leading-[1.5625rem] bg-surface-8" data-cid="n26">
              <p className="block mb-1.5 text-muted-foreground [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.6875rem] font-semibold leading-[1.1875rem] tracking-[1.54px] uppercase" data-cid="n27">
                요약
              </p>
              {" "}
              <p className="h-[12.6875rem] block mt-[14.5px] text-muted-foreground max-md:h-[28.55rem]" data-cid="n28">
                {"검색바의 자유 텍스트 장소 검색(“부산대·홍대”)은 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n29">
                  카카오 로컬 키워드 검색을 BE 프록시
                </strong>
                (
                <code className="inline py-[1.7px] px-[0.3125rem] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-[0.8125rem] leading-[1.375rem] bg-surface-2" data-cid="n30">
                  GET /api/search/places?q=
                </code>
                {")로 채택 (2026-07-28, 정민). 지도는 네이버 유지 — 혼용은 카카오 데브톡 150397 "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n31">
                  스태프 공식 답변으로 허용 확인
                </strong>
                {"(조건: 실시간 호출 기반만, 저장 목적 호출 불가 → "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n32">
                  결과 캐시·DB 저장 금지
                </strong>
                {"). "}
                <a className="inline text-primary underline cursor-pointer" data-cid="n33" data-component="link" href="/adr/adr-EC-A7-80-EB-8F-84-sdk-EB-84-A4-EC-9D-B4-EB-B2-84-EC-A0-84-ED-99-98">
                  ADR 지도 SDK 네이버 전환
                </a>
                의 재검토 트리거(“랜드마크를 외부 API 의존으로 결정하면 카카오 Local 재평가”)가 zone(MSG-234) 보류로 발동된 사례. 234의 “지역 검색”은 MSG-251로 이관, 234는 순수 표시명으로 축소. 스모크 실측(4곳): 카카오 WGS84 좌표가 변환 없이 우리 행정동 폴리곤·GridEncoder에 하위 행정동 단위까지 정확 매핑 — 부산대→장전2동·서면역→부전2동·홍대입구역→서교동(법정동 동교동을 행정동으로 정확 변환)·광안리→광안2동.
              </p>
              {" "}
            </aside>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n34" data-component="heading" id="이-노트로-답할-수-있는-질문">
              이 노트로 답할 수 있는 질문
            </h2>
            {" "}
            <ul className="block my-4 pl-[1.35rem] [list-style-type:disc] list-outside" data-cid="n35">
              {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
            </ul>
            {" "}
            <h2 className="border-t border-solid border-t-surface-2 block mt-[3.3rem] mb-[0.9rem] pt-3 text-2xl font-bold leading-10.5 tracking-[-0.6px]" data-cid="n41" data-component="heading" id="결정-요약">
              결정 요약
            </h2>
            {" "}
            <ol className="block my-4 pl-[1.35rem] [list-style-type:decimal] list-outside" data-cid="n42">
              <li className="h-28 list-item my-[0.3rem] text-muted-foreground max-md:h-56" data-cid="n43">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n44">
                  공급자 = 카카오 로컬 키워드 검색
                </strong>
                : 일 10만/월 300만 무료 · WGS84 직결(x=lng, y=lat) · 페이지당 15건 · POI 커버리지(카카오맵 기반). 네이버 지역검색 오픈API(일 25,000 합산·display≤5·mapx÷1e7 변환)는 폴백 기록만. 카카오 앱은 OAuth용 “필맵” 앱 재사용(로컬 API 활성화 완료, 2026-07-28).
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-42" data-cid="n45">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n46">
                  혼용 약관
                </strong>
                {": 데브톡 150397 스태프 답변 “타사 지도 SDK와 혼용하여 사용하셔도 약관 상 이슈 없음” — 조건 준수 설계: "}
                <strong className="inline text-foreground [font-weight:650]" data-cid="n47">
                  실시간 패스스루 프록시, Redis 캐시·place 저장 금지
                </strong>
                , REST 키 서버 보관, FE 디바운스 300ms.
              </li>
              <li className="h-21 list-item my-[0.3rem] text-muted-foreground max-md:h-42" data-cid="n48">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n49">
                  응답 합성
                </strong>
                {": 좌표 → "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n50">
                  GridEncoder.encode
                </code>
                {" 즉석 계산으로 "}
                <code className="inline py-0.5 px-[5.5px] rounded-[5px] [font-family:ui-monospace,_SFMono-Regular,_'SF_Mono',_'JetBrains_Mono',_Menlo,_monospace] text-sm leading-6 bg-surface-2" data-cid="n51">
                  gridId
                </code>
                {" 포함(저장 아님) — FE는 선택 즉시 지도 이동+격자 하이라이트. 지도 이동과 격자 판정을 같은 카카오 좌표 하나로 해 내부 일관성 보장(공급자 간 대표 좌표 편차는 100m 격자 MVP 수용)."}
              </li>
              <li className="h-14 list-item my-[0.3rem] text-muted-foreground max-md:h-35 md:max-lg:h-21" data-cid="n52">
                <strong className="inline text-foreground [font-weight:650]" data-cid="n53">
                  스코프 경계(ver6 검색 화면)
                </strong>
                : 자유 텍스트 POI = MSG-251 / 무입력 “전체 지역(행정동별 격자 수)” = MSG-238(축=행정동 확정 — 디자인의 구 단위 리스트는 오기) / 최근 방문·검색 = FE 로컬.
              </li>
            </ol>
            {" "}
          </article>
          {" "}
        </div>
        {" "}
      </main>
      {" "}
      <footer className="border-t border-solid border-t-surface-2 block pt-8.5 pb-14 text-muted text-sm leading-[1.5rem]" data-cid="n54">
        <div className="h-[47.3px] block max-w-270 mx-auto px-12 max-md:h-[94.5px] max-md:px-5 md:max-lg:px-[2.4rem]" data-cid="n55">
          <strong className="inline text-muted-foreground font-bold" data-cid="n56">
            FillMap
          </strong>
          {"은 방문한 장소를 짧은 영상으로 남기고 지도 위 100×100m 격자를 채우는 서비스입니다. 이 사이트는 그 설계 산출물을 모아 발행합니다. 지금 실린 것은 백엔드 문서입니다. "}
        </div>
        {" "}
      </footer>
      {" "}
    </>
  );
}
